// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActionType defines the possible actions for rules and defaults
type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	ActionType_ACTION_TYPE_ALLOW       ActionType = 1
	ActionType_ACTION_TYPE_BLOCK       ActionType = 2
	ActionType_ACTION_TYPE_MOCK        ActionType = 3
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ACTION_TYPE_ALLOW",
		2: "ACTION_TYPE_BLOCK",
		3: "ACTION_TYPE_MOCK",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"ACTION_TYPE_ALLOW":       1,
		"ACTION_TYPE_BLOCK":       2,
		"ACTION_TYPE_MOCK":        3,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

// FallbackAction defines what to do when a primary action fails or is not applicable
type FallbackAction int32

const (
	FallbackAction_FALLBACK_ACTION_UNSPECIFIED FallbackAction = 0
	FallbackAction_FALLBACK_ACTION_CLOSE       FallbackAction = 1
	FallbackAction_FALLBACK_ACTION_MOCK        FallbackAction = 2
)

// Enum value maps for FallbackAction.
var (
	FallbackAction_name = map[int32]string{
		0: "FALLBACK_ACTION_UNSPECIFIED",
		1: "FALLBACK_ACTION_CLOSE",
		2: "FALLBACK_ACTION_MOCK",
	}
	FallbackAction_value = map[string]int32{
		"FALLBACK_ACTION_UNSPECIFIED": 0,
		"FALLBACK_ACTION_CLOSE":       1,
		"FALLBACK_ACTION_MOCK":        2,
	}
)

func (x FallbackAction) Enum() *FallbackAction {
	p := new(FallbackAction)
	*p = x
	return p
}

func (x FallbackAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FallbackAction) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[1].Descriptor()
}

func (FallbackAction) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[1]
}

func (x FallbackAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FallbackAction.Descriptor instead.
func (FallbackAction) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

// MockPreset defines pre-configured mock responses
type MockPreset int32

const (
	MockPreset_MOCK_PRESET_UNSPECIFIED   MockPreset = 0
	MockPreset_MOCK_PRESET_SSH_SECURE    MockPreset = 1
	MockPreset_MOCK_PRESET_SSH_TARPIT    MockPreset = 2
	MockPreset_MOCK_PRESET_HTTP_403      MockPreset = 3
	MockPreset_MOCK_PRESET_HTTP_404      MockPreset = 4
	MockPreset_MOCK_PRESET_HTTP_401      MockPreset = 5
	MockPreset_MOCK_PRESET_REDIS_SECURE  MockPreset = 6
	MockPreset_MOCK_PRESET_MYSQL_SECURE  MockPreset = 7
	MockPreset_MOCK_PRESET_MYSQL_TARPIT  MockPreset = 8
	MockPreset_MOCK_PRESET_RDP_SECURE    MockPreset = 9
	MockPreset_MOCK_PRESET_TELNET_SECURE MockPreset = 10
	MockPreset_MOCK_PRESET_RAW_TARPIT    MockPreset = 11
)

// Enum value maps for MockPreset.
var (
	MockPreset_name = map[int32]string{
		0:  "MOCK_PRESET_UNSPECIFIED",
		1:  "MOCK_PRESET_SSH_SECURE",
		2:  "MOCK_PRESET_SSH_TARPIT",
		3:  "MOCK_PRESET_HTTP_403",
		4:  "MOCK_PRESET_HTTP_404",
		5:  "MOCK_PRESET_HTTP_401",
		6:  "MOCK_PRESET_REDIS_SECURE",
		7:  "MOCK_PRESET_MYSQL_SECURE",
		8:  "MOCK_PRESET_MYSQL_TARPIT",
		9:  "MOCK_PRESET_RDP_SECURE",
		10: "MOCK_PRESET_TELNET_SECURE",
		11: "MOCK_PRESET_RAW_TARPIT",
	}
	MockPreset_value = map[string]int32{
		"MOCK_PRESET_UNSPECIFIED":   0,
		"MOCK_PRESET_SSH_SECURE":    1,
		"MOCK_PRESET_SSH_TARPIT":    2,
		"MOCK_PRESET_HTTP_403":      3,
		"MOCK_PRESET_HTTP_404":      4,
		"MOCK_PRESET_HTTP_401":      5,
		"MOCK_PRESET_REDIS_SECURE":  6,
		"MOCK_PRESET_MYSQL_SECURE":  7,
		"MOCK_PRESET_MYSQL_TARPIT":  8,
		"MOCK_PRESET_RDP_SECURE":    9,
		"MOCK_PRESET_TELNET_SECURE": 10,
		"MOCK_PRESET_RAW_TARPIT":    11,
	}
)

func (x MockPreset) Enum() *MockPreset {
	p := new(MockPreset)
	*p = x
	return p
}

func (x MockPreset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MockPreset) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[2].Descriptor()
}

func (MockPreset) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[2]
}

func (x MockPreset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MockPreset.Descriptor instead.
func (MockPreset) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{2}
}

// ConditionType defines the type of condition in a rule
type ConditionType int32

const (
	ConditionType_CONDITION_TYPE_UNSPECIFIED     ConditionType = 0
	ConditionType_CONDITION_TYPE_SOURCE_IP       ConditionType = 1
	ConditionType_CONDITION_TYPE_GEO_COUNTRY     ConditionType = 2
	ConditionType_CONDITION_TYPE_GEO_CITY        ConditionType = 3
	ConditionType_CONDITION_TYPE_GEO_ISP         ConditionType = 4
	ConditionType_CONDITION_TYPE_TIME_RANGE      ConditionType = 5 // Format: "HH:MM-HH:MM" (24h)
	ConditionType_CONDITION_TYPE_TLS_FINGERPRINT ConditionType = 6
	ConditionType_CONDITION_TYPE_TLS_CN          ConditionType = 7
	ConditionType_CONDITION_TYPE_TLS_SERIAL      ConditionType = 8
	ConditionType_CONDITION_TYPE_TLS_PRESENT     ConditionType = 9  // Client presented any valid cert (value: "true" or "false")
	ConditionType_CONDITION_TYPE_TLS_CA          ConditionType = 10 // Issuing CA CommonName matches
	ConditionType_CONDITION_TYPE_TLS_SAN         ConditionType = 11 // Subject Alternative Name matches (DNS or email)
	ConditionType_CONDITION_TYPE_TLS_OU          ConditionType = 12 // Organizational Unit matches
)

// Enum value maps for ConditionType.
var (
	ConditionType_name = map[int32]string{
		0:  "CONDITION_TYPE_UNSPECIFIED",
		1:  "CONDITION_TYPE_SOURCE_IP",
		2:  "CONDITION_TYPE_GEO_COUNTRY",
		3:  "CONDITION_TYPE_GEO_CITY",
		4:  "CONDITION_TYPE_GEO_ISP",
		5:  "CONDITION_TYPE_TIME_RANGE",
		6:  "CONDITION_TYPE_TLS_FINGERPRINT",
		7:  "CONDITION_TYPE_TLS_CN",
		8:  "CONDITION_TYPE_TLS_SERIAL",
		9:  "CONDITION_TYPE_TLS_PRESENT",
		10: "CONDITION_TYPE_TLS_CA",
		11: "CONDITION_TYPE_TLS_SAN",
		12: "CONDITION_TYPE_TLS_OU",
	}
	ConditionType_value = map[string]int32{
		"CONDITION_TYPE_UNSPECIFIED":     0,
		"CONDITION_TYPE_SOURCE_IP":       1,
		"CONDITION_TYPE_GEO_COUNTRY":     2,
		"CONDITION_TYPE_GEO_CITY":        3,
		"CONDITION_TYPE_GEO_ISP":         4,
		"CONDITION_TYPE_TIME_RANGE":      5,
		"CONDITION_TYPE_TLS_FINGERPRINT": 6,
		"CONDITION_TYPE_TLS_CN":          7,
		"CONDITION_TYPE_TLS_SERIAL":      8,
		"CONDITION_TYPE_TLS_PRESENT":     9,
		"CONDITION_TYPE_TLS_CA":          10,
		"CONDITION_TYPE_TLS_SAN":         11,
		"CONDITION_TYPE_TLS_OU":          12,
	}
)

func (x ConditionType) Enum() *ConditionType {
	p := new(ConditionType)
	*p = x
	return p
}

func (x ConditionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConditionType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[3].Descriptor()
}

func (ConditionType) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[3]
}

func (x ConditionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConditionType.Descriptor instead.
func (ConditionType) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{3}
}

// Operator defines how to match the value in a condition
type Operator int32

const (
	Operator_OPERATOR_UNSPECIFIED Operator = 0
	Operator_OPERATOR_EQ          Operator = 1 // Equals
	Operator_OPERATOR_CONTAINS    Operator = 2 // String contains
	Operator_OPERATOR_REGEX       Operator = 3 // Regular expression
	Operator_OPERATOR_CIDR        Operator = 4 // IP CIDR match (e.g., 192.168.1.0/24)
)

// Enum value maps for Operator.
var (
	Operator_name = map[int32]string{
		0: "OPERATOR_UNSPECIFIED",
		1: "OPERATOR_EQ",
		2: "OPERATOR_CONTAINS",
		3: "OPERATOR_REGEX",
		4: "OPERATOR_CIDR",
	}
	Operator_value = map[string]int32{
		"OPERATOR_UNSPECIFIED": 0,
		"OPERATOR_EQ":          1,
		"OPERATOR_CONTAINS":    2,
		"OPERATOR_REGEX":       3,
		"OPERATOR_CIDR":        4,
	}
)

func (x Operator) Enum() *Operator {
	p := new(Operator)
	*p = x
	return p
}

func (x Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[4].Descriptor()
}

func (Operator) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[4]
}

func (x Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operator.Descriptor instead.
func (Operator) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{4}
}

// SortOrder defines sorting options for statistics queries
type SortOrder int32

const (
	SortOrder_SORT_LAST_SEEN_DESC        SortOrder = 0 // Default
	SortOrder_SORT_LAST_SEEN_ASC         SortOrder = 1
	SortOrder_SORT_CONNECTION_COUNT_DESC SortOrder = 2
	SortOrder_SORT_BYTES_TOTAL_DESC      SortOrder = 3
	SortOrder_SORT_RECENCY_WEIGHT_DESC   SortOrder = 4
)

// Enum value maps for SortOrder.
var (
	SortOrder_name = map[int32]string{
		0: "SORT_LAST_SEEN_DESC",
		1: "SORT_LAST_SEEN_ASC",
		2: "SORT_CONNECTION_COUNT_DESC",
		3: "SORT_BYTES_TOTAL_DESC",
		4: "SORT_RECENCY_WEIGHT_DESC",
	}
	SortOrder_value = map[string]int32{
		"SORT_LAST_SEEN_DESC":        0,
		"SORT_LAST_SEEN_ASC":         1,
		"SORT_CONNECTION_COUNT_DESC": 2,
		"SORT_BYTES_TOTAL_DESC":      3,
		"SORT_RECENCY_WEIGHT_DESC":   4,
	}
)

func (x SortOrder) Enum() *SortOrder {
	p := new(SortOrder)
	*p = x
	return p
}

func (x SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[5].Descriptor()
}

func (SortOrder) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[5]
}

func (x SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOrder.Descriptor instead.
func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{5}
}

// PemLabel defines PEM block types
type PemLabel int32

const (
	PemLabel_PEM_LABEL_UNSPECIFIED           PemLabel = 0
	PemLabel_PEM_LABEL_CERTIFICATE           PemLabel = 1
	PemLabel_PEM_LABEL_PUBLIC_KEY            PemLabel = 2
	PemLabel_PEM_LABEL_PRIVATE_KEY           PemLabel = 3
	PemLabel_PEM_LABEL_ENCRYPTED_PRIVATE_KEY PemLabel = 4
)

// Enum value maps for PemLabel.
var (
	PemLabel_name = map[int32]string{
		0: "PEM_LABEL_UNSPECIFIED",
		1: "PEM_LABEL_CERTIFICATE",
		2: "PEM_LABEL_PUBLIC_KEY",
		3: "PEM_LABEL_PRIVATE_KEY",
		4: "PEM_LABEL_ENCRYPTED_PRIVATE_KEY",
	}
	PemLabel_value = map[string]int32{
		"PEM_LABEL_UNSPECIFIED":           0,
		"PEM_LABEL_CERTIFICATE":           1,
		"PEM_LABEL_PUBLIC_KEY":            2,
		"PEM_LABEL_PRIVATE_KEY":           3,
		"PEM_LABEL_ENCRYPTED_PRIVATE_KEY": 4,
	}
)

func (x PemLabel) Enum() *PemLabel {
	p := new(PemLabel)
	*p = x
	return p
}

func (x PemLabel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PemLabel) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[6].Descriptor()
}

func (PemLabel) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[6]
}

func (x PemLabel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PemLabel.Descriptor instead.
func (PemLabel) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{6}
}

// ApprovalDuration defines how long an approval decision lasts
type ApprovalDuration int32

const (
	ApprovalDuration_APPROVAL_DURATION_UNSPECIFIED ApprovalDuration = 0
	ApprovalDuration_APPROVAL_DURATION_ONCE        ApprovalDuration = 1 // Single connection only (no caching)
	ApprovalDuration_APPROVAL_DURATION_1_MINUTE    ApprovalDuration = 2 // 60 seconds
	ApprovalDuration_APPROVAL_DURATION_10_MINUTES  ApprovalDuration = 3 // 600 seconds
	ApprovalDuration_APPROVAL_DURATION_1_HOUR      ApprovalDuration = 4 // 3600 seconds
	ApprovalDuration_APPROVAL_DURATION_24_HOURS    ApprovalDuration = 5 // 86400 seconds
)

// Enum value maps for ApprovalDuration.
var (
	ApprovalDuration_name = map[int32]string{
		0: "APPROVAL_DURATION_UNSPECIFIED",
		1: "APPROVAL_DURATION_ONCE",
		2: "APPROVAL_DURATION_1_MINUTE",
		3: "APPROVAL_DURATION_10_MINUTES",
		4: "APPROVAL_DURATION_1_HOUR",
		5: "APPROVAL_DURATION_24_HOURS",
	}
	ApprovalDuration_value = map[string]int32{
		"APPROVAL_DURATION_UNSPECIFIED": 0,
		"APPROVAL_DURATION_ONCE":        1,
		"APPROVAL_DURATION_1_MINUTE":    2,
		"APPROVAL_DURATION_10_MINUTES":  3,
		"APPROVAL_DURATION_1_HOUR":      4,
		"APPROVAL_DURATION_24_HOURS":    5,
	}
)

func (x ApprovalDuration) Enum() *ApprovalDuration {
	p := new(ApprovalDuration)
	*p = x
	return p
}

func (x ApprovalDuration) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalDuration) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[7].Descriptor()
}

func (ApprovalDuration) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[7]
}

func (x ApprovalDuration) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalDuration.Descriptor instead.
func (ApprovalDuration) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{7}
}

// ApprovalActionType defines the user's decision for an approval request
type ApprovalActionType int32

const (
	ApprovalActionType_APPROVAL_ACTION_TYPE_UNSPECIFIED    ApprovalActionType = 0
	ApprovalActionType_APPROVAL_ACTION_TYPE_ALLOW          ApprovalActionType = 1 // Allow connection
	ApprovalActionType_APPROVAL_ACTION_TYPE_BLOCK          ApprovalActionType = 2 // Block connection
	ApprovalActionType_APPROVAL_ACTION_TYPE_BLOCK_ADD_RULE ApprovalActionType = 3 // Block and create permanent rule
)

// Enum value maps for ApprovalActionType.
var (
	ApprovalActionType_name = map[int32]string{
		0: "APPROVAL_ACTION_TYPE_UNSPECIFIED",
		1: "APPROVAL_ACTION_TYPE_ALLOW",
		2: "APPROVAL_ACTION_TYPE_BLOCK",
		3: "APPROVAL_ACTION_TYPE_BLOCK_ADD_RULE",
	}
	ApprovalActionType_value = map[string]int32{
		"APPROVAL_ACTION_TYPE_UNSPECIFIED":    0,
		"APPROVAL_ACTION_TYPE_ALLOW":          1,
		"APPROVAL_ACTION_TYPE_BLOCK":          2,
		"APPROVAL_ACTION_TYPE_BLOCK_ADD_RULE": 3,
	}
)

func (x ApprovalActionType) Enum() *ApprovalActionType {
	p := new(ApprovalActionType)
	*p = x
	return p
}

func (x ApprovalActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[8].Descriptor()
}

func (ApprovalActionType) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[8]
}

func (x ApprovalActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalActionType.Descriptor instead.
func (ApprovalActionType) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{8}
}

// P2PMode defines the peer-to-peer connection strategy
type P2PMode int32

const (
	P2PMode_P2P_MODE_UNSPECIFIED P2PMode = 0
	P2PMode_P2P_MODE_AUTO        P2PMode = 1 // Try P2P first, fallback to Hub if fails
	P2PMode_P2P_MODE_DIRECT      P2PMode = 2 // P2P only, show error if fails (no fallback)
	P2PMode_P2P_MODE_HUB         P2PMode = 3 // Hub relay only, no P2P
)

// Enum value maps for P2PMode.
var (
	P2PMode_name = map[int32]string{
		0: "P2P_MODE_UNSPECIFIED",
		1: "P2P_MODE_AUTO",
		2: "P2P_MODE_DIRECT",
		3: "P2P_MODE_HUB",
	}
	P2PMode_value = map[string]int32{
		"P2P_MODE_UNSPECIFIED": 0,
		"P2P_MODE_AUTO":        1,
		"P2P_MODE_DIRECT":      2,
		"P2P_MODE_HUB":         3,
	}
)

func (x P2PMode) Enum() *P2PMode {
	p := new(P2PMode)
	*p = x
	return p
}

func (x P2PMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (P2PMode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[9].Descriptor()
}

func (P2PMode) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[9]
}

func (x P2PMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use P2PMode.Descriptor instead.
func (P2PMode) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{9}
}

// CryptoAlgorithm for forward compatibility
type CryptoAlgorithm int32

const (
	CryptoAlgorithm_ALGO_UNKNOWN CryptoAlgorithm = 0
	CryptoAlgorithm_ALGO_ED25519 CryptoAlgorithm = 1 // Ed25519 Signing + X25519 ECDH + AES-GCM Encryption
)

// Enum value maps for CryptoAlgorithm.
var (
	CryptoAlgorithm_name = map[int32]string{
		0: "ALGO_UNKNOWN",
		1: "ALGO_ED25519",
	}
	CryptoAlgorithm_value = map[string]int32{
		"ALGO_UNKNOWN": 0,
		"ALGO_ED25519": 1,
	}
)

func (x CryptoAlgorithm) Enum() *CryptoAlgorithm {
	p := new(CryptoAlgorithm)
	*p = x
	return p
}

func (x CryptoAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CryptoAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[10].Descriptor()
}

func (CryptoAlgorithm) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[10]
}

func (x CryptoAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CryptoAlgorithm.Descriptor instead.
func (CryptoAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{10}
}

// EncryptedPayload wraps E2E encrypted data using X25519 ECDH + AES-256-GCM.
// The sender generates an ephemeral X25519 keypair, derives a shared secret
// with the recipient's public key using ECDH, then encrypts with AES-GCM.
type EncryptedPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EphemeralPubkey   []byte                 `protobuf:"bytes,1,opt,name=ephemeral_pubkey,json=ephemeralPubkey,proto3" json:"ephemeral_pubkey,omitempty"`       // X25519 ephemeral public key (32 bytes)
	Nonce             []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`                                                  // AES-GCM nonce (12 bytes)
	Ciphertext        []byte                 `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`                                        // AES-256-GCM encrypted payload with auth tag
	SenderFingerprint string                 `protobuf:"bytes,4,opt,name=sender_fingerprint,json=senderFingerprint,proto3" json:"sender_fingerprint,omitempty"` // SHA256 of sender's cert for key lookup
	Signature         []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`                                          // Ed25519 signature of ciphertext (optional)
	Algorithm         CryptoAlgorithm        `protobuf:"varint,6,opt,name=algorithm,proto3,enum=nitella.CryptoAlgorithm" json:"algorithm,omitempty"`            // Algorithm identifier for forward compat
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EncryptedPayload) Reset() {
	*x = EncryptedPayload{}
	mi := &file_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedPayload) ProtoMessage() {}

func (x *EncryptedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedPayload.ProtoReflect.Descriptor instead.
func (*EncryptedPayload) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedPayload) GetEphemeralPubkey() []byte {
	if x != nil {
		return x.EphemeralPubkey
	}
	return nil
}

func (x *EncryptedPayload) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedPayload) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *EncryptedPayload) GetSenderFingerprint() string {
	if x != nil {
		return x.SenderFingerprint
	}
	return ""
}

func (x *EncryptedPayload) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *EncryptedPayload) GetAlgorithm() CryptoAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return CryptoAlgorithm_ALGO_UNKNOWN
}

// SecureCommandPayload is the inner structure that gets encrypted.
// It includes anti-replay fields that are only visible after decryption.
type SecureCommandPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Unique ID for this request
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // Unix timestamp (seconds)
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                            // The actual command content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecureCommandPayload) Reset() {
	*x = SecureCommandPayload{}
	mi := &file_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecureCommandPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureCommandPayload) ProtoMessage() {}

func (x *SecureCommandPayload) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureCommandPayload.ProtoReflect.Descriptor instead.
func (*SecureCommandPayload) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *SecureCommandPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SecureCommandPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SecureCommandPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Alert (encrypted content for Zero-Trust)
type Alert struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeId string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Plaintext fields for Hub routing only
	Severity      string `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"` // info, warning, critical (Hub needs this for priority)
	TimestampUnix int64  `protobuf:"varint,4,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Acknowledged  bool   `protobuf:"varint,5,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// Encrypted content (title, description) - only Mobile can decrypt
	Encrypted     *EncryptedPayload `protobuf:"bytes,6,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Routing info (e.g. type=approval, tag=production)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *Alert) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *Alert) GetEncrypted() *EncryptedPayload {
	if x != nil {
		return x.Encrypted
	}
	return nil
}

func (x *Alert) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// GeoInfo contains geographical information for an IP address.
type GeoInfo struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Country string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	City    string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Isp     string                 `protobuf:"bytes,3,opt,name=isp,proto3" json:"isp,omitempty"`
	// Extended fields
	CountryCode string  `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Region      string  `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	RegionName  string  `protobuf:"bytes,6,opt,name=region_name,json=regionName,proto3" json:"region_name,omitempty"`
	Zip         string  `protobuf:"bytes,7,opt,name=zip,proto3" json:"zip,omitempty"`
	Latitude    float64 `protobuf:"fixed64,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude   float64 `protobuf:"fixed64,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Timezone    string  `protobuf:"bytes,10,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Org         string  `protobuf:"bytes,11,opt,name=org,proto3" json:"org,omitempty"`
	As          string  `protobuf:"bytes,12,opt,name=as,proto3" json:"as,omitempty"`
	// Metadata
	Source        string `protobuf:"bytes,13,opt,name=source,proto3" json:"source,omitempty"` // e.g., "cache-l1", "cache-l2", "local-db", "remote:ip-api"
	LatencyMs     int64  `protobuf:"varint,14,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoInfo) Reset() {
	*x = GeoInfo{}
	mi := &file_common_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoInfo) ProtoMessage() {}

func (x *GeoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoInfo.ProtoReflect.Descriptor instead.
func (*GeoInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *GeoInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GeoInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GeoInfo) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

func (x *GeoInfo) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *GeoInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GeoInfo) GetRegionName() string {
	if x != nil {
		return x.RegionName
	}
	return ""
}

func (x *GeoInfo) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *GeoInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoInfo) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *GeoInfo) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *GeoInfo) GetAs() string {
	if x != nil {
		return x.As
	}
	return ""
}

func (x *GeoInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GeoInfo) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_common_common_proto protoreflect.FileDescriptor

const file_common_common_proto_rawDesc = "" +
	"\n" +
	"\x13common/common.proto\x12\anitella\"\xf8\x01\n" +
	"\x10EncryptedPayload\x12)\n" +
	"\x10ephemeral_pubkey\x18\x01 \x01(\fR\x0fephemeralPubkey\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\fR\n" +
	"ciphertext\x12-\n" +
	"\x12sender_fingerprint\x18\x04 \x01(\tR\x11senderFingerprint\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\x126\n" +
	"\talgorithm\x18\x06 \x01(\x0e2\x18.nitella.CryptoAlgorithmR\talgorithm\"g\n" +
	"\x14SecureCommandPayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xc7\x02\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12%\n" +
	"\x0etimestamp_unix\x18\x04 \x01(\x03R\rtimestampUnix\x12\"\n" +
	"\facknowledged\x18\x05 \x01(\bR\facknowledged\x127\n" +
	"\tencrypted\x18\x06 \x01(\v2\x19.nitella.EncryptedPayloadR\tencrypted\x128\n" +
	"\bmetadata\x18\a \x03(\v2\x1c.nitella.Alert.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x02\n" +
	"\aGeoInfo\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x10\n" +
	"\x03isp\x18\x03 \x01(\tR\x03isp\x12!\n" +
	"\fcountry_code\x18\x04 \x01(\tR\vcountryCode\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1f\n" +
	"\vregion_name\x18\x06 \x01(\tR\n" +
	"regionName\x12\x10\n" +
	"\x03zip\x18\a \x01(\tR\x03zip\x12\x1a\n" +
	"\blatitude\x18\b \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\t \x01(\x01R\tlongitude\x12\x1a\n" +
	"\btimezone\x18\n" +
	" \x01(\tR\btimezone\x12\x10\n" +
	"\x03org\x18\v \x01(\tR\x03org\x12\x0e\n" +
	"\x02as\x18\f \x01(\tR\x02as\x12\x16\n" +
	"\x06source\x18\r \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x0e \x01(\x03R\tlatencyMs*m\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACTION_TYPE_ALLOW\x10\x01\x12\x15\n" +
	"\x11ACTION_TYPE_BLOCK\x10\x02\x12\x14\n" +
	"\x10ACTION_TYPE_MOCK\x10\x03*f\n" +
	"\x0eFallbackAction\x12\x1f\n" +
	"\x1bFALLBACK_ACTION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FALLBACK_ACTION_CLOSE\x10\x01\x12\x18\n" +
	"\x14FALLBACK_ACTION_MOCK\x10\x02*\xe0\x02\n" +
	"\n" +
	"MockPreset\x12\x1b\n" +
	"\x17MOCK_PRESET_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MOCK_PRESET_SSH_SECURE\x10\x01\x12\x1a\n" +
	"\x16MOCK_PRESET_SSH_TARPIT\x10\x02\x12\x18\n" +
	"\x14MOCK_PRESET_HTTP_403\x10\x03\x12\x18\n" +
	"\x14MOCK_PRESET_HTTP_404\x10\x04\x12\x18\n" +
	"\x14MOCK_PRESET_HTTP_401\x10\x05\x12\x1c\n" +
	"\x18MOCK_PRESET_REDIS_SECURE\x10\x06\x12\x1c\n" +
	"\x18MOCK_PRESET_MYSQL_SECURE\x10\a\x12\x1c\n" +
	"\x18MOCK_PRESET_MYSQL_TARPIT\x10\b\x12\x1a\n" +
	"\x16MOCK_PRESET_RDP_SECURE\x10\t\x12\x1d\n" +
	"\x19MOCK_PRESET_TELNET_SECURE\x10\n" +
	"\x12\x1a\n" +
	"\x16MOCK_PRESET_RAW_TARPIT\x10\v*\x95\x03\n" +
	"\rConditionType\x12\x1e\n" +
	"\x1aCONDITION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONDITION_TYPE_SOURCE_IP\x10\x01\x12\x1e\n" +
	"\x1aCONDITION_TYPE_GEO_COUNTRY\x10\x02\x12\x1b\n" +
	"\x17CONDITION_TYPE_GEO_CITY\x10\x03\x12\x1a\n" +
	"\x16CONDITION_TYPE_GEO_ISP\x10\x04\x12\x1d\n" +
	"\x19CONDITION_TYPE_TIME_RANGE\x10\x05\x12\"\n" +
	"\x1eCONDITION_TYPE_TLS_FINGERPRINT\x10\x06\x12\x19\n" +
	"\x15CONDITION_TYPE_TLS_CN\x10\a\x12\x1d\n" +
	"\x19CONDITION_TYPE_TLS_SERIAL\x10\b\x12\x1e\n" +
	"\x1aCONDITION_TYPE_TLS_PRESENT\x10\t\x12\x19\n" +
	"\x15CONDITION_TYPE_TLS_CA\x10\n" +
	"\x12\x1a\n" +
	"\x16CONDITION_TYPE_TLS_SAN\x10\v\x12\x19\n" +
	"\x15CONDITION_TYPE_TLS_OU\x10\f*s\n" +
	"\bOperator\x12\x18\n" +
	"\x14OPERATOR_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOPERATOR_EQ\x10\x01\x12\x15\n" +
	"\x11OPERATOR_CONTAINS\x10\x02\x12\x12\n" +
	"\x0eOPERATOR_REGEX\x10\x03\x12\x11\n" +
	"\rOPERATOR_CIDR\x10\x04*\x95\x01\n" +
	"\tSortOrder\x12\x17\n" +
	"\x13SORT_LAST_SEEN_DESC\x10\x00\x12\x16\n" +
	"\x12SORT_LAST_SEEN_ASC\x10\x01\x12\x1e\n" +
	"\x1aSORT_CONNECTION_COUNT_DESC\x10\x02\x12\x19\n" +
	"\x15SORT_BYTES_TOTAL_DESC\x10\x03\x12\x1c\n" +
	"\x18SORT_RECENCY_WEIGHT_DESC\x10\x04*\x9a\x01\n" +
	"\bPemLabel\x12\x19\n" +
	"\x15PEM_LABEL_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PEM_LABEL_CERTIFICATE\x10\x01\x12\x18\n" +
	"\x14PEM_LABEL_PUBLIC_KEY\x10\x02\x12\x19\n" +
	"\x15PEM_LABEL_PRIVATE_KEY\x10\x03\x12#\n" +
	"\x1fPEM_LABEL_ENCRYPTED_PRIVATE_KEY\x10\x04*\xd1\x01\n" +
	"\x10ApprovalDuration\x12!\n" +
	"\x1dAPPROVAL_DURATION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16APPROVAL_DURATION_ONCE\x10\x01\x12\x1e\n" +
	"\x1aAPPROVAL_DURATION_1_MINUTE\x10\x02\x12 \n" +
	"\x1cAPPROVAL_DURATION_10_MINUTES\x10\x03\x12\x1c\n" +
	"\x18APPROVAL_DURATION_1_HOUR\x10\x04\x12\x1e\n" +
	"\x1aAPPROVAL_DURATION_24_HOURS\x10\x05*\xa3\x01\n" +
	"\x12ApprovalActionType\x12$\n" +
	" APPROVAL_ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aAPPROVAL_ACTION_TYPE_ALLOW\x10\x01\x12\x1e\n" +
	"\x1aAPPROVAL_ACTION_TYPE_BLOCK\x10\x02\x12'\n" +
	"#APPROVAL_ACTION_TYPE_BLOCK_ADD_RULE\x10\x03*]\n" +
	"\aP2PMode\x12\x18\n" +
	"\x14P2P_MODE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rP2P_MODE_AUTO\x10\x01\x12\x13\n" +
	"\x0fP2P_MODE_DIRECT\x10\x02\x12\x10\n" +
	"\fP2P_MODE_HUB\x10\x03*5\n" +
	"\x0fCryptoAlgorithm\x12\x10\n" +
	"\fALGO_UNKNOWN\x10\x00\x12\x10\n" +
	"\fALGO_ED25519\x10\x01B+Z)github.com/ivere27/nitella/pkg/api/commonb\x06proto3"

var (
	file_common_common_proto_rawDescOnce sync.Once
	file_common_common_proto_rawDescData []byte
)

func file_common_common_proto_rawDescGZIP() []byte {
	file_common_common_proto_rawDescOnce.Do(func() {
		file_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)))
	})
	return file_common_common_proto_rawDescData
}

var file_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 11)
var file_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_common_proto_goTypes = []any{
	(ActionType)(0),              // 0: nitella.ActionType
	(FallbackAction)(0),          // 1: nitella.FallbackAction
	(MockPreset)(0),              // 2: nitella.MockPreset
	(ConditionType)(0),           // 3: nitella.ConditionType
	(Operator)(0),                // 4: nitella.Operator
	(SortOrder)(0),               // 5: nitella.SortOrder
	(PemLabel)(0),                // 6: nitella.PemLabel
	(ApprovalDuration)(0),        // 7: nitella.ApprovalDuration
	(ApprovalActionType)(0),      // 8: nitella.ApprovalActionType
	(P2PMode)(0),                 // 9: nitella.P2PMode
	(CryptoAlgorithm)(0),         // 10: nitella.CryptoAlgorithm
	(*EncryptedPayload)(nil),     // 11: nitella.EncryptedPayload
	(*SecureCommandPayload)(nil), // 12: nitella.SecureCommandPayload
	(*Alert)(nil),                // 13: nitella.Alert
	(*GeoInfo)(nil),              // 14: nitella.GeoInfo
	nil,                          // 15: nitella.Alert.MetadataEntry
}
var file_common_common_proto_depIdxs = []int32{
	10, // 0: nitella.EncryptedPayload.algorithm:type_name -> nitella.CryptoAlgorithm
	11, // 1: nitella.Alert.encrypted:type_name -> nitella.EncryptedPayload
	15, // 2: nitella.Alert.metadata:type_name -> nitella.Alert.MetadataEntry
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_common_common_proto_init() }
func file_common_common_proto_init() {
	if File_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)),
			NumEnums:      11,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_proto_goTypes,
		DependencyIndexes: file_common_common_proto_depIdxs,
		EnumInfos:         file_common_common_proto_enumTypes,
		MessageInfos:      file_common_common_proto_msgTypes,
	}.Build()
	File_common_common_proto = out.File
	file_common_common_proto_goTypes = nil
	file_common_common_proto_depIdxs = nil
}
