// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GeoInfo contains geographical information for an IP address.
type GeoInfo struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Country string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	City    string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Isp     string                 `protobuf:"bytes,3,opt,name=isp,proto3" json:"isp,omitempty"`
	// Extended fields
	CountryCode string  `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Region      string  `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	RegionName  string  `protobuf:"bytes,6,opt,name=region_name,json=regionName,proto3" json:"region_name,omitempty"`
	Zip         string  `protobuf:"bytes,7,opt,name=zip,proto3" json:"zip,omitempty"`
	Latitude    float64 `protobuf:"fixed64,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude   float64 `protobuf:"fixed64,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Timezone    string  `protobuf:"bytes,10,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Org         string  `protobuf:"bytes,11,opt,name=org,proto3" json:"org,omitempty"`
	As          string  `protobuf:"bytes,12,opt,name=as,proto3" json:"as,omitempty"`
	// Metadata
	Source        string `protobuf:"bytes,13,opt,name=source,proto3" json:"source,omitempty"` // e.g., "cache-l1", "cache-l2", "local-db", "remote:ip-api"
	LatencyMs     int64  `protobuf:"varint,14,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoInfo) Reset() {
	*x = GeoInfo{}
	mi := &file_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoInfo) ProtoMessage() {}

func (x *GeoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoInfo.ProtoReflect.Descriptor instead.
func (*GeoInfo) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *GeoInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GeoInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GeoInfo) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

func (x *GeoInfo) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *GeoInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GeoInfo) GetRegionName() string {
	if x != nil {
		return x.RegionName
	}
	return ""
}

func (x *GeoInfo) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *GeoInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoInfo) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *GeoInfo) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *GeoInfo) GetAs() string {
	if x != nil {
		return x.As
	}
	return ""
}

func (x *GeoInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GeoInfo) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

var File_common_common_proto protoreflect.FileDescriptor

const file_common_common_proto_rawDesc = "" +
	"\n" +
	"\x13common/common.proto\x12\anitella\"\xe6\x02\n" +
	"\aGeoInfo\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x10\n" +
	"\x03isp\x18\x03 \x01(\tR\x03isp\x12!\n" +
	"\fcountry_code\x18\x04 \x01(\tR\vcountryCode\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1f\n" +
	"\vregion_name\x18\x06 \x01(\tR\n" +
	"regionName\x12\x10\n" +
	"\x03zip\x18\a \x01(\tR\x03zip\x12\x1a\n" +
	"\blatitude\x18\b \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\t \x01(\x01R\tlongitude\x12\x1a\n" +
	"\btimezone\x18\n" +
	" \x01(\tR\btimezone\x12\x10\n" +
	"\x03org\x18\v \x01(\tR\x03org\x12\x0e\n" +
	"\x02as\x18\f \x01(\tR\x02as\x12\x16\n" +
	"\x06source\x18\r \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x0e \x01(\x03R\tlatencyMsB+Z)github.com/ivere27/nitella/pkg/api/commonb\x06proto3"

var (
	file_common_common_proto_rawDescOnce sync.Once
	file_common_common_proto_rawDescData []byte
)

func file_common_common_proto_rawDescGZIP() []byte {
	file_common_common_proto_rawDescOnce.Do(func() {
		file_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)))
	})
	return file_common_common_proto_rawDescData
}

var file_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_common_proto_goTypes = []any{
	(*GeoInfo)(nil), // 0: nitella.GeoInfo
}
var file_common_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_common_proto_init() }
func file_common_common_proto_init() {
	if File_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_proto_goTypes,
		DependencyIndexes: file_common_common_proto_depIdxs,
		MessageInfos:      file_common_common_proto_msgTypes,
	}.Build()
	File_common_common_proto = out.File
	file_common_common_proto_goTypes = nil
	file_common_common_proto_depIdxs = nil
}
