// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: geoip/geoip.proto

package geoip

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	common "github.com/ivere27/nitella/pkg/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheLayer int32

const (
	CacheLayer_CACHE_LAYER_ALL CacheLayer = 0
	CacheLayer_CACHE_LAYER_L1  CacheLayer = 1
	CacheLayer_CACHE_LAYER_L2  CacheLayer = 2
)

// Enum value maps for CacheLayer.
var (
	CacheLayer_name = map[int32]string{
		0: "CACHE_LAYER_ALL",
		1: "CACHE_LAYER_L1",
		2: "CACHE_LAYER_L2",
	}
	CacheLayer_value = map[string]int32{
		"CACHE_LAYER_ALL": 0,
		"CACHE_LAYER_L1":  1,
		"CACHE_LAYER_L2":  2,
	}
)

func (x CacheLayer) Enum() *CacheLayer {
	p := new(CacheLayer)
	*p = x
	return p
}

func (x CacheLayer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CacheLayer) Descriptor() protoreflect.EnumDescriptor {
	return file_geoip_geoip_proto_enumTypes[0].Descriptor()
}

func (CacheLayer) Type() protoreflect.EnumType {
	return &file_geoip_geoip_proto_enumTypes[0]
}

func (x CacheLayer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CacheLayer.Descriptor instead.
func (CacheLayer) EnumDescriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{0}
}

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_geoip_geoip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{0}
}

func (x *LookupRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ServiceStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ready           bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	L1CacheSize     int64                  `protobuf:"varint,2,opt,name=l1_cache_size,json=l1CacheSize,proto3" json:"l1_cache_size,omitempty"`
	L2CacheSize     int64                  `protobuf:"varint,3,opt,name=l2_cache_size,json=l2CacheSize,proto3" json:"l2_cache_size,omitempty"`
	ActiveProviders []string               `protobuf:"bytes,4,rep,name=active_providers,json=activeProviders,proto3" json:"active_providers,omitempty"`
	Strategy        string                 `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	LocalDbLoaded   bool                   `protobuf:"varint,6,opt,name=local_db_loaded,json=localDbLoaded,proto3" json:"local_db_loaded,omitempty"`
	L2TtlHours      int32                  `protobuf:"varint,7,opt,name=l2_ttl_hours,json=l2TtlHours,proto3" json:"l2_ttl_hours,omitempty"` // 0 = permanent
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_geoip_geoip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ServiceStatus) GetL1CacheSize() int64 {
	if x != nil {
		return x.L1CacheSize
	}
	return 0
}

func (x *ServiceStatus) GetL2CacheSize() int64 {
	if x != nil {
		return x.L2CacheSize
	}
	return 0
}

func (x *ServiceStatus) GetActiveProviders() []string {
	if x != nil {
		return x.ActiveProviders
	}
	return nil
}

func (x *ServiceStatus) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *ServiceStatus) GetLocalDbLoaded() bool {
	if x != nil {
		return x.LocalDbLoaded
	}
	return false
}

func (x *ServiceStatus) GetL2TtlHours() int32 {
	if x != nil {
		return x.L2TtlHours
	}
	return 0
}

type LoadLocalDBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CityDbPath    string                 `protobuf:"bytes,1,opt,name=city_db_path,json=cityDbPath,proto3" json:"city_db_path,omitempty"`
	IspDbPath     string                 `protobuf:"bytes,2,opt,name=isp_db_path,json=ispDbPath,proto3" json:"isp_db_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadLocalDBRequest) Reset() {
	*x = LoadLocalDBRequest{}
	mi := &file_geoip_geoip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadLocalDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadLocalDBRequest) ProtoMessage() {}

func (x *LoadLocalDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadLocalDBRequest.ProtoReflect.Descriptor instead.
func (*LoadLocalDBRequest) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{2}
}

func (x *LoadLocalDBRequest) GetCityDbPath() string {
	if x != nil {
		return x.CityDbPath
	}
	return ""
}

func (x *LoadLocalDBRequest) GetIspDbPath() string {
	if x != nil {
		return x.IspDbPath
	}
	return ""
}

type LocalDBStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loaded        bool                   `protobuf:"varint,1,opt,name=loaded,proto3" json:"loaded,omitempty"`
	CityDbPath    string                 `protobuf:"bytes,2,opt,name=city_db_path,json=cityDbPath,proto3" json:"city_db_path,omitempty"`
	IspDbPath     string                 `protobuf:"bytes,3,opt,name=isp_db_path,json=ispDbPath,proto3" json:"isp_db_path,omitempty"`
	CityDbSize    int64                  `protobuf:"varint,4,opt,name=city_db_size,json=cityDbSize,proto3" json:"city_db_size,omitempty"`
	IspDbSize     int64                  `protobuf:"varint,5,opt,name=isp_db_size,json=ispDbSize,proto3" json:"isp_db_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalDBStatus) Reset() {
	*x = LocalDBStatus{}
	mi := &file_geoip_geoip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalDBStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalDBStatus) ProtoMessage() {}

func (x *LocalDBStatus) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalDBStatus.ProtoReflect.Descriptor instead.
func (*LocalDBStatus) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{3}
}

func (x *LocalDBStatus) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *LocalDBStatus) GetCityDbPath() string {
	if x != nil {
		return x.CityDbPath
	}
	return ""
}

func (x *LocalDBStatus) GetIspDbPath() string {
	if x != nil {
		return x.IspDbPath
	}
	return ""
}

func (x *LocalDBStatus) GetCityDbSize() int64 {
	if x != nil {
		return x.CityDbSize
	}
	return 0
}

func (x *LocalDBStatus) GetIspDbSize() int64 {
	if x != nil {
		return x.IspDbSize
	}
	return 0
}

type ProviderNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderNameRequest) Reset() {
	*x = ProviderNameRequest{}
	mi := &file_geoip_geoip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderNameRequest) ProtoMessage() {}

func (x *ProviderNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderNameRequest.ProtoReflect.Descriptor instead.
func (*ProviderNameRequest) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{4}
}

func (x *ProviderNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderInfo        `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_geoip_geoip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{5}
}

func (x *ListProvidersResponse) GetProviders() []*ProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

type ProviderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	FieldMapping  *FieldMapping          `protobuf:"bytes,5,opt,name=field_mapping,json=fieldMapping,proto3" json:"field_mapping,omitempty"`
	Stats         *ProviderStats         `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_geoip_geoip_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{6}
}

func (x *ProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProviderInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ProviderInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ProviderInfo) GetFieldMapping() *FieldMapping {
	if x != nil {
		return x.FieldMapping
	}
	return nil
}

func (x *ProviderInfo) GetStats() *ProviderStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type AddProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	FieldMapping  *FieldMapping          `protobuf:"bytes,4,opt,name=field_mapping,json=fieldMapping,proto3" json:"field_mapping,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProviderRequest) Reset() {
	*x = AddProviderRequest{}
	mi := &file_geoip_geoip_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProviderRequest) ProtoMessage() {}

func (x *AddProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProviderRequest.ProtoReflect.Descriptor instead.
func (*AddProviderRequest) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{7}
}

func (x *AddProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProviderRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AddProviderRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *AddProviderRequest) GetFieldMapping() *FieldMapping {
	if x != nil {
		return x.FieldMapping
	}
	return nil
}

type RemoveProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProviderRequest) Reset() {
	*x = RemoveProviderRequest{}
	mi := &file_geoip_geoip_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProviderRequest) ProtoMessage() {}

func (x *RemoveProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProviderRequest.ProtoReflect.Descriptor instead.
func (*RemoveProviderRequest) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	FieldMapping  *FieldMapping          `protobuf:"bytes,4,opt,name=field_mapping,json=fieldMapping,proto3" json:"field_mapping,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProviderRequest) Reset() {
	*x = UpdateProviderRequest{}
	mi := &file_geoip_geoip_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderRequest) ProtoMessage() {}

func (x *UpdateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderRequest.ProtoReflect.Descriptor instead.
func (*UpdateProviderRequest) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProviderRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateProviderRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *UpdateProviderRequest) GetFieldMapping() *FieldMapping {
	if x != nil {
		return x.FieldMapping
	}
	return nil
}

func (x *UpdateProviderRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ReorderProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderNames []string               `protobuf:"bytes,1,rep,name=provider_names,json=providerNames,proto3" json:"provider_names,omitempty"` // Names in new priority order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderProvidersRequest) Reset() {
	*x = ReorderProvidersRequest{}
	mi := &file_geoip_geoip_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderProvidersRequest) ProtoMessage() {}

func (x *ReorderProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderProvidersRequest.ProtoReflect.Descriptor instead.
func (*ReorderProvidersRequest) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{10}
}

func (x *ReorderProvidersRequest) GetProviderNames() []string {
	if x != nil {
		return x.ProviderNames
	}
	return nil
}

type ProviderStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LookupCount    int64                  `protobuf:"varint,2,opt,name=lookup_count,json=lookupCount,proto3" json:"lookup_count,omitempty"`
	SuccessCount   int64                  `protobuf:"varint,3,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	ErrorCount     int64                  `protobuf:"varint,4,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	TotalLatencyMs int64                  `protobuf:"varint,5,opt,name=total_latency_ms,json=totalLatencyMs,proto3" json:"total_latency_ms,omitempty"`
	AvgLatencyMs   int64                  `protobuf:"varint,6,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	LastUsedUnix   int64                  `protobuf:"varint,7,opt,name=last_used_unix,json=lastUsedUnix,proto3" json:"last_used_unix,omitempty"`
	LastError      string                 `protobuf:"bytes,8,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProviderStats) Reset() {
	*x = ProviderStats{}
	mi := &file_geoip_geoip_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStats) ProtoMessage() {}

func (x *ProviderStats) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStats.ProtoReflect.Descriptor instead.
func (*ProviderStats) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{11}
}

func (x *ProviderStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderStats) GetLookupCount() int64 {
	if x != nil {
		return x.LookupCount
	}
	return 0
}

func (x *ProviderStats) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *ProviderStats) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *ProviderStats) GetTotalLatencyMs() int64 {
	if x != nil {
		return x.TotalLatencyMs
	}
	return 0
}

func (x *ProviderStats) GetAvgLatencyMs() int64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *ProviderStats) GetLastUsedUnix() int64 {
	if x != nil {
		return x.LastUsedUnix
	}
	return 0
}

func (x *ProviderStats) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type FieldMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       []string               `protobuf:"bytes,1,rep,name=country,proto3" json:"country,omitempty"`
	CountryCode   []string               `protobuf:"bytes,2,rep,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Region        []string               `protobuf:"bytes,3,rep,name=region,proto3" json:"region,omitempty"`
	RegionName    []string               `protobuf:"bytes,4,rep,name=region_name,json=regionName,proto3" json:"region_name,omitempty"`
	City          []string               `protobuf:"bytes,5,rep,name=city,proto3" json:"city,omitempty"`
	Zip           []string               `protobuf:"bytes,6,rep,name=zip,proto3" json:"zip,omitempty"`
	Timezone      []string               `protobuf:"bytes,7,rep,name=timezone,proto3" json:"timezone,omitempty"`
	Latitude      []string               `protobuf:"bytes,8,rep,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     []string               `protobuf:"bytes,9,rep,name=longitude,proto3" json:"longitude,omitempty"`
	Isp           []string               `protobuf:"bytes,10,rep,name=isp,proto3" json:"isp,omitempty"`
	Org           []string               `protobuf:"bytes,11,rep,name=org,proto3" json:"org,omitempty"`
	As            []string               `protobuf:"bytes,12,rep,name=as,proto3" json:"as,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldMapping) Reset() {
	*x = FieldMapping{}
	mi := &file_geoip_geoip_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMapping) ProtoMessage() {}

func (x *FieldMapping) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMapping.ProtoReflect.Descriptor instead.
func (*FieldMapping) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{12}
}

func (x *FieldMapping) GetCountry() []string {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *FieldMapping) GetCountryCode() []string {
	if x != nil {
		return x.CountryCode
	}
	return nil
}

func (x *FieldMapping) GetRegion() []string {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *FieldMapping) GetRegionName() []string {
	if x != nil {
		return x.RegionName
	}
	return nil
}

func (x *FieldMapping) GetCity() []string {
	if x != nil {
		return x.City
	}
	return nil
}

func (x *FieldMapping) GetZip() []string {
	if x != nil {
		return x.Zip
	}
	return nil
}

func (x *FieldMapping) GetTimezone() []string {
	if x != nil {
		return x.Timezone
	}
	return nil
}

func (x *FieldMapping) GetLatitude() []string {
	if x != nil {
		return x.Latitude
	}
	return nil
}

func (x *FieldMapping) GetLongitude() []string {
	if x != nil {
		return x.Longitude
	}
	return nil
}

func (x *FieldMapping) GetIsp() []string {
	if x != nil {
		return x.Isp
	}
	return nil
}

func (x *FieldMapping) GetOrg() []string {
	if x != nil {
		return x.Org
	}
	return nil
}

func (x *FieldMapping) GetAs() []string {
	if x != nil {
		return x.As
	}
	return nil
}

type CacheStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	L1Size        int64                  `protobuf:"varint,1,opt,name=l1_size,json=l1Size,proto3" json:"l1_size,omitempty"`
	L1Capacity    int64                  `protobuf:"varint,2,opt,name=l1_capacity,json=l1Capacity,proto3" json:"l1_capacity,omitempty"`
	L1Hits        int64                  `protobuf:"varint,3,opt,name=l1_hits,json=l1Hits,proto3" json:"l1_hits,omitempty"`
	L1Misses      int64                  `protobuf:"varint,4,opt,name=l1_misses,json=l1Misses,proto3" json:"l1_misses,omitempty"`
	L2Size        int64                  `protobuf:"varint,5,opt,name=l2_size,json=l2Size,proto3" json:"l2_size,omitempty"`
	L2Enabled     bool                   `protobuf:"varint,6,opt,name=l2_enabled,json=l2Enabled,proto3" json:"l2_enabled,omitempty"`
	L2Path        string                 `protobuf:"bytes,7,opt,name=l2_path,json=l2Path,proto3" json:"l2_path,omitempty"`
	L2Hits        int64                  `protobuf:"varint,8,opt,name=l2_hits,json=l2Hits,proto3" json:"l2_hits,omitempty"`
	L2Misses      int64                  `protobuf:"varint,9,opt,name=l2_misses,json=l2Misses,proto3" json:"l2_misses,omitempty"`
	L2TtlHours    int32                  `protobuf:"varint,10,opt,name=l2_ttl_hours,json=l2TtlHours,proto3" json:"l2_ttl_hours,omitempty"` // 0 = permanent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheStats) Reset() {
	*x = CacheStats{}
	mi := &file_geoip_geoip_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheStats) ProtoMessage() {}

func (x *CacheStats) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheStats.ProtoReflect.Descriptor instead.
func (*CacheStats) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{13}
}

func (x *CacheStats) GetL1Size() int64 {
	if x != nil {
		return x.L1Size
	}
	return 0
}

func (x *CacheStats) GetL1Capacity() int64 {
	if x != nil {
		return x.L1Capacity
	}
	return 0
}

func (x *CacheStats) GetL1Hits() int64 {
	if x != nil {
		return x.L1Hits
	}
	return 0
}

func (x *CacheStats) GetL1Misses() int64 {
	if x != nil {
		return x.L1Misses
	}
	return 0
}

func (x *CacheStats) GetL2Size() int64 {
	if x != nil {
		return x.L2Size
	}
	return 0
}

func (x *CacheStats) GetL2Enabled() bool {
	if x != nil {
		return x.L2Enabled
	}
	return false
}

func (x *CacheStats) GetL2Path() string {
	if x != nil {
		return x.L2Path
	}
	return ""
}

func (x *CacheStats) GetL2Hits() int64 {
	if x != nil {
		return x.L2Hits
	}
	return 0
}

func (x *CacheStats) GetL2Misses() int64 {
	if x != nil {
		return x.L2Misses
	}
	return 0
}

func (x *CacheStats) GetL2TtlHours() int32 {
	if x != nil {
		return x.L2TtlHours
	}
	return 0
}

type ClearCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layer         CacheLayer             `protobuf:"varint,1,opt,name=layer,proto3,enum=nitella.geoip.CacheLayer" json:"layer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCacheRequest) Reset() {
	*x = ClearCacheRequest{}
	mi := &file_geoip_geoip_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCacheRequest) ProtoMessage() {}

func (x *ClearCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCacheRequest.ProtoReflect.Descriptor instead.
func (*ClearCacheRequest) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{14}
}

func (x *ClearCacheRequest) GetLayer() CacheLayer {
	if x != nil {
		return x.Layer
	}
	return CacheLayer_CACHE_LAYER_ALL
}

type CacheSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	L1Capacity    int32                  `protobuf:"varint,1,opt,name=l1_capacity,json=l1Capacity,proto3" json:"l1_capacity,omitempty"`
	L1TtlHours    int32                  `protobuf:"varint,2,opt,name=l1_ttl_hours,json=l1TtlHours,proto3" json:"l1_ttl_hours,omitempty"`
	L2Enabled     bool                   `protobuf:"varint,3,opt,name=l2_enabled,json=l2Enabled,proto3" json:"l2_enabled,omitempty"`
	L2Path        string                 `protobuf:"bytes,4,opt,name=l2_path,json=l2Path,proto3" json:"l2_path,omitempty"`
	L2TtlHours    int32                  `protobuf:"varint,5,opt,name=l2_ttl_hours,json=l2TtlHours,proto3" json:"l2_ttl_hours,omitempty"` // 0 = permanent (no expiration)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheSettings) Reset() {
	*x = CacheSettings{}
	mi := &file_geoip_geoip_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSettings) ProtoMessage() {}

func (x *CacheSettings) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSettings.ProtoReflect.Descriptor instead.
func (*CacheSettings) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{15}
}

func (x *CacheSettings) GetL1Capacity() int32 {
	if x != nil {
		return x.L1Capacity
	}
	return 0
}

func (x *CacheSettings) GetL1TtlHours() int32 {
	if x != nil {
		return x.L1TtlHours
	}
	return 0
}

func (x *CacheSettings) GetL2Enabled() bool {
	if x != nil {
		return x.L2Enabled
	}
	return false
}

func (x *CacheSettings) GetL2Path() string {
	if x != nil {
		return x.L2Path
	}
	return ""
}

func (x *CacheSettings) GetL2TtlHours() int32 {
	if x != nil {
		return x.L2TtlHours
	}
	return 0
}

type UpdateCacheSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	L1Capacity    int32                  `protobuf:"varint,1,opt,name=l1_capacity,json=l1Capacity,proto3" json:"l1_capacity,omitempty"`
	L1TtlHours    int32                  `protobuf:"varint,2,opt,name=l1_ttl_hours,json=l1TtlHours,proto3" json:"l1_ttl_hours,omitempty"`
	L2Enabled     bool                   `protobuf:"varint,3,opt,name=l2_enabled,json=l2Enabled,proto3" json:"l2_enabled,omitempty"`
	L2Path        string                 `protobuf:"bytes,4,opt,name=l2_path,json=l2Path,proto3" json:"l2_path,omitempty"`
	L2TtlHours    int32                  `protobuf:"varint,5,opt,name=l2_ttl_hours,json=l2TtlHours,proto3" json:"l2_ttl_hours,omitempty"` // 0 = permanent (no expiration)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCacheSettingsRequest) Reset() {
	*x = UpdateCacheSettingsRequest{}
	mi := &file_geoip_geoip_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCacheSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCacheSettingsRequest) ProtoMessage() {}

func (x *UpdateCacheSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCacheSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateCacheSettingsRequest) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateCacheSettingsRequest) GetL1Capacity() int32 {
	if x != nil {
		return x.L1Capacity
	}
	return 0
}

func (x *UpdateCacheSettingsRequest) GetL1TtlHours() int32 {
	if x != nil {
		return x.L1TtlHours
	}
	return 0
}

func (x *UpdateCacheSettingsRequest) GetL2Enabled() bool {
	if x != nil {
		return x.L2Enabled
	}
	return false
}

func (x *UpdateCacheSettingsRequest) GetL2Path() string {
	if x != nil {
		return x.L2Path
	}
	return ""
}

func (x *UpdateCacheSettingsRequest) GetL2TtlHours() int32 {
	if x != nil {
		return x.L2TtlHours
	}
	return 0
}

type StrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []string               `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"` // e.g., ["l1", "l2", "local", "remote"]
	TimeoutMs     int32                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyResponse) Reset() {
	*x = StrategyResponse{}
	mi := &file_geoip_geoip_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyResponse) ProtoMessage() {}

func (x *StrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyResponse.ProtoReflect.Descriptor instead.
func (*StrategyResponse) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{17}
}

func (x *StrategyResponse) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *StrategyResponse) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type SetStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []string               `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStrategyRequest) Reset() {
	*x = SetStrategyRequest{}
	mi := &file_geoip_geoip_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStrategyRequest) ProtoMessage() {}

func (x *SetStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geoip_geoip_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStrategyRequest.ProtoReflect.Descriptor instead.
func (*SetStrategyRequest) Descriptor() ([]byte, []int) {
	return file_geoip_geoip_proto_rawDescGZIP(), []int{18}
}

func (x *SetStrategyRequest) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *SetStrategyRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

var File_geoip_geoip_proto protoreflect.FileDescriptor

const file_geoip_geoip_proto_rawDesc = "" +
	"\n" +
	"\x11geoip/geoip.proto\x12\rnitella.geoip\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13common/common.proto\"\x1f\n" +
	"\rLookupRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\xfe\x01\n" +
	"\rServiceStatus\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\"\n" +
	"\rl1_cache_size\x18\x02 \x01(\x03R\vl1CacheSize\x12\"\n" +
	"\rl2_cache_size\x18\x03 \x01(\x03R\vl2CacheSize\x12)\n" +
	"\x10active_providers\x18\x04 \x03(\tR\x0factiveProviders\x12\x1a\n" +
	"\bstrategy\x18\x05 \x01(\tR\bstrategy\x12&\n" +
	"\x0flocal_db_loaded\x18\x06 \x01(\bR\rlocalDbLoaded\x12 \n" +
	"\fl2_ttl_hours\x18\a \x01(\x05R\n" +
	"l2TtlHours\"V\n" +
	"\x12LoadLocalDBRequest\x12 \n" +
	"\fcity_db_path\x18\x01 \x01(\tR\n" +
	"cityDbPath\x12\x1e\n" +
	"\visp_db_path\x18\x02 \x01(\tR\tispDbPath\"\xab\x01\n" +
	"\rLocalDBStatus\x12\x16\n" +
	"\x06loaded\x18\x01 \x01(\bR\x06loaded\x12 \n" +
	"\fcity_db_path\x18\x02 \x01(\tR\n" +
	"cityDbPath\x12\x1e\n" +
	"\visp_db_path\x18\x03 \x01(\tR\tispDbPath\x12 \n" +
	"\fcity_db_size\x18\x04 \x01(\x03R\n" +
	"cityDbSize\x12\x1e\n" +
	"\visp_db_size\x18\x05 \x01(\x03R\tispDbSize\")\n" +
	"\x13ProviderNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"R\n" +
	"\x15ListProvidersResponse\x129\n" +
	"\tproviders\x18\x01 \x03(\v2\x1b.nitella.geoip.ProviderInfoR\tproviders\"\xe0\x01\n" +
	"\fProviderInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12@\n" +
	"\rfield_mapping\x18\x05 \x01(\v2\x1b.nitella.geoip.FieldMappingR\ffieldMapping\x122\n" +
	"\x05stats\x18\x06 \x01(\v2\x1c.nitella.geoip.ProviderStatsR\x05stats\"\x98\x01\n" +
	"\x12AddProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12@\n" +
	"\rfield_mapping\x18\x04 \x01(\v2\x1b.nitella.geoip.FieldMappingR\ffieldMapping\"+\n" +
	"\x15RemoveProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xb5\x01\n" +
	"\x15UpdateProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12@\n" +
	"\rfield_mapping\x18\x04 \x01(\v2\x1b.nitella.geoip.FieldMappingR\ffieldMapping\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"@\n" +
	"\x17ReorderProvidersRequest\x12%\n" +
	"\x0eprovider_names\x18\x01 \x03(\tR\rproviderNames\"\xa1\x02\n" +
	"\rProviderStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\flookup_count\x18\x02 \x01(\x03R\vlookupCount\x12#\n" +
	"\rsuccess_count\x18\x03 \x01(\x03R\fsuccessCount\x12\x1f\n" +
	"\verror_count\x18\x04 \x01(\x03R\n" +
	"errorCount\x12(\n" +
	"\x10total_latency_ms\x18\x05 \x01(\x03R\x0etotalLatencyMs\x12$\n" +
	"\x0eavg_latency_ms\x18\x06 \x01(\x03R\favgLatencyMs\x12$\n" +
	"\x0elast_used_unix\x18\a \x01(\x03R\flastUsedUnix\x12\x1d\n" +
	"\n" +
	"last_error\x18\b \x01(\tR\tlastError\"\xb4\x02\n" +
	"\fFieldMapping\x12\x18\n" +
	"\acountry\x18\x01 \x03(\tR\acountry\x12!\n" +
	"\fcountry_code\x18\x02 \x03(\tR\vcountryCode\x12\x16\n" +
	"\x06region\x18\x03 \x03(\tR\x06region\x12\x1f\n" +
	"\vregion_name\x18\x04 \x03(\tR\n" +
	"regionName\x12\x12\n" +
	"\x04city\x18\x05 \x03(\tR\x04city\x12\x10\n" +
	"\x03zip\x18\x06 \x03(\tR\x03zip\x12\x1a\n" +
	"\btimezone\x18\a \x03(\tR\btimezone\x12\x1a\n" +
	"\blatitude\x18\b \x03(\tR\blatitude\x12\x1c\n" +
	"\tlongitude\x18\t \x03(\tR\tlongitude\x12\x10\n" +
	"\x03isp\x18\n" +
	" \x03(\tR\x03isp\x12\x10\n" +
	"\x03org\x18\v \x03(\tR\x03org\x12\x0e\n" +
	"\x02as\x18\f \x03(\tR\x02as\"\xa5\x02\n" +
	"\n" +
	"CacheStats\x12\x17\n" +
	"\al1_size\x18\x01 \x01(\x03R\x06l1Size\x12\x1f\n" +
	"\vl1_capacity\x18\x02 \x01(\x03R\n" +
	"l1Capacity\x12\x17\n" +
	"\al1_hits\x18\x03 \x01(\x03R\x06l1Hits\x12\x1b\n" +
	"\tl1_misses\x18\x04 \x01(\x03R\bl1Misses\x12\x17\n" +
	"\al2_size\x18\x05 \x01(\x03R\x06l2Size\x12\x1d\n" +
	"\n" +
	"l2_enabled\x18\x06 \x01(\bR\tl2Enabled\x12\x17\n" +
	"\al2_path\x18\a \x01(\tR\x06l2Path\x12\x17\n" +
	"\al2_hits\x18\b \x01(\x03R\x06l2Hits\x12\x1b\n" +
	"\tl2_misses\x18\t \x01(\x03R\bl2Misses\x12 \n" +
	"\fl2_ttl_hours\x18\n" +
	" \x01(\x05R\n" +
	"l2TtlHours\"D\n" +
	"\x11ClearCacheRequest\x12/\n" +
	"\x05layer\x18\x01 \x01(\x0e2\x19.nitella.geoip.CacheLayerR\x05layer\"\xac\x01\n" +
	"\rCacheSettings\x12\x1f\n" +
	"\vl1_capacity\x18\x01 \x01(\x05R\n" +
	"l1Capacity\x12 \n" +
	"\fl1_ttl_hours\x18\x02 \x01(\x05R\n" +
	"l1TtlHours\x12\x1d\n" +
	"\n" +
	"l2_enabled\x18\x03 \x01(\bR\tl2Enabled\x12\x17\n" +
	"\al2_path\x18\x04 \x01(\tR\x06l2Path\x12 \n" +
	"\fl2_ttl_hours\x18\x05 \x01(\x05R\n" +
	"l2TtlHours\"\xb9\x01\n" +
	"\x1aUpdateCacheSettingsRequest\x12\x1f\n" +
	"\vl1_capacity\x18\x01 \x01(\x05R\n" +
	"l1Capacity\x12 \n" +
	"\fl1_ttl_hours\x18\x02 \x01(\x05R\n" +
	"l1TtlHours\x12\x1d\n" +
	"\n" +
	"l2_enabled\x18\x03 \x01(\bR\tl2Enabled\x12\x17\n" +
	"\al2_path\x18\x04 \x01(\tR\x06l2Path\x12 \n" +
	"\fl2_ttl_hours\x18\x05 \x01(\x05R\n" +
	"l2TtlHours\"G\n" +
	"\x10StrategyResponse\x12\x14\n" +
	"\x05steps\x18\x01 \x03(\tR\x05steps\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x05R\ttimeoutMs\"I\n" +
	"\x12SetStrategyRequest\x12\x14\n" +
	"\x05steps\x18\x01 \x03(\tR\x05steps\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x05R\ttimeoutMs*I\n" +
	"\n" +
	"CacheLayer\x12\x13\n" +
	"\x0fCACHE_LAYER_ALL\x10\x00\x12\x12\n" +
	"\x0eCACHE_LAYER_L1\x10\x01\x12\x12\n" +
	"\x0eCACHE_LAYER_L2\x10\x022\x8b\x01\n" +
	"\fGeoIPService\x128\n" +
	"\x06Lookup\x12\x1c.nitella.geoip.LookupRequest\x1a\x10.nitella.GeoInfo\x12A\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x1c.nitella.geoip.ServiceStatus2\x88\r\n" +
	"\x11GeoIPAdminService\x128\n" +
	"\x06Lookup\x12\x1c.nitella.geoip.LookupRequest\x1a\x10.nitella.GeoInfo\x12A\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x1c.nitella.geoip.ServiceStatus\x12H\n" +
	"\vLoadLocalDB\x12!.nitella.geoip.LoadLocalDBRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\rUnloadLocalDB\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x10GetLocalDBStatus\x12\x16.google.protobuf.Empty\x1a\x1c.nitella.geoip.LocalDBStatus\x12M\n" +
	"\rListProviders\x12\x16.google.protobuf.Empty\x1a$.nitella.geoip.ListProvidersResponse\x12M\n" +
	"\vAddProvider\x12!.nitella.geoip.AddProviderRequest\x1a\x1b.nitella.geoip.ProviderInfo\x12N\n" +
	"\x0eRemoveProvider\x12$.nitella.geoip.RemoveProviderRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\x0eUpdateProvider\x12$.nitella.geoip.UpdateProviderRequest\x1a\x1b.nitella.geoip.ProviderInfo\x12`\n" +
	"\x10ReorderProviders\x12&.nitella.geoip.ReorderProvidersRequest\x1a$.nitella.geoip.ListProvidersResponse\x12L\n" +
	"\x0eEnableProvider\x12\".nitella.geoip.ProviderNameRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x0fDisableProvider\x12\".nitella.geoip.ProviderNameRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x10GetProviderStats\x12\".nitella.geoip.ProviderNameRequest\x1a\x1c.nitella.geoip.ProviderStats\x12B\n" +
	"\rGetCacheStats\x12\x16.google.protobuf.Empty\x1a\x19.nitella.geoip.CacheStats\x12F\n" +
	"\n" +
	"ClearCache\x12 .nitella.geoip.ClearCacheRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x10GetCacheSettings\x12\x16.google.protobuf.Empty\x1a\x1c.nitella.geoip.CacheSettings\x12^\n" +
	"\x13UpdateCacheSettings\x12).nitella.geoip.UpdateCacheSettingsRequest\x1a\x1c.nitella.geoip.CacheSettings\x12:\n" +
	"\bVacuumL2\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\vGetStrategy\x12\x16.google.protobuf.Empty\x1a\x1f.nitella.geoip.StrategyResponse\x12Q\n" +
	"\vSetStrategy\x12!.nitella.geoip.SetStrategyRequest\x1a\x1f.nitella.geoip.StrategyResponse\x12>\n" +
	"\fReloadConfig\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\n" +
	"SaveConfig\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB*Z(github.com/ivere27/nitella/pkg/api/geoipb\x06proto3"

var (
	file_geoip_geoip_proto_rawDescOnce sync.Once
	file_geoip_geoip_proto_rawDescData []byte
)

func file_geoip_geoip_proto_rawDescGZIP() []byte {
	file_geoip_geoip_proto_rawDescOnce.Do(func() {
		file_geoip_geoip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geoip_geoip_proto_rawDesc), len(file_geoip_geoip_proto_rawDesc)))
	})
	return file_geoip_geoip_proto_rawDescData
}

var file_geoip_geoip_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_geoip_geoip_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_geoip_geoip_proto_goTypes = []any{
	(CacheLayer)(0),                    // 0: nitella.geoip.CacheLayer
	(*LookupRequest)(nil),              // 1: nitella.geoip.LookupRequest
	(*ServiceStatus)(nil),              // 2: nitella.geoip.ServiceStatus
	(*LoadLocalDBRequest)(nil),         // 3: nitella.geoip.LoadLocalDBRequest
	(*LocalDBStatus)(nil),              // 4: nitella.geoip.LocalDBStatus
	(*ProviderNameRequest)(nil),        // 5: nitella.geoip.ProviderNameRequest
	(*ListProvidersResponse)(nil),      // 6: nitella.geoip.ListProvidersResponse
	(*ProviderInfo)(nil),               // 7: nitella.geoip.ProviderInfo
	(*AddProviderRequest)(nil),         // 8: nitella.geoip.AddProviderRequest
	(*RemoveProviderRequest)(nil),      // 9: nitella.geoip.RemoveProviderRequest
	(*UpdateProviderRequest)(nil),      // 10: nitella.geoip.UpdateProviderRequest
	(*ReorderProvidersRequest)(nil),    // 11: nitella.geoip.ReorderProvidersRequest
	(*ProviderStats)(nil),              // 12: nitella.geoip.ProviderStats
	(*FieldMapping)(nil),               // 13: nitella.geoip.FieldMapping
	(*CacheStats)(nil),                 // 14: nitella.geoip.CacheStats
	(*ClearCacheRequest)(nil),          // 15: nitella.geoip.ClearCacheRequest
	(*CacheSettings)(nil),              // 16: nitella.geoip.CacheSettings
	(*UpdateCacheSettingsRequest)(nil), // 17: nitella.geoip.UpdateCacheSettingsRequest
	(*StrategyResponse)(nil),           // 18: nitella.geoip.StrategyResponse
	(*SetStrategyRequest)(nil),         // 19: nitella.geoip.SetStrategyRequest
	(*empty.Empty)(nil),                // 20: google.protobuf.Empty
	(*common.GeoInfo)(nil),             // 21: nitella.GeoInfo
}
var file_geoip_geoip_proto_depIdxs = []int32{
	7,  // 0: nitella.geoip.ListProvidersResponse.providers:type_name -> nitella.geoip.ProviderInfo
	13, // 1: nitella.geoip.ProviderInfo.field_mapping:type_name -> nitella.geoip.FieldMapping
	12, // 2: nitella.geoip.ProviderInfo.stats:type_name -> nitella.geoip.ProviderStats
	13, // 3: nitella.geoip.AddProviderRequest.field_mapping:type_name -> nitella.geoip.FieldMapping
	13, // 4: nitella.geoip.UpdateProviderRequest.field_mapping:type_name -> nitella.geoip.FieldMapping
	0,  // 5: nitella.geoip.ClearCacheRequest.layer:type_name -> nitella.geoip.CacheLayer
	1,  // 6: nitella.geoip.GeoIPService.Lookup:input_type -> nitella.geoip.LookupRequest
	20, // 7: nitella.geoip.GeoIPService.GetStatus:input_type -> google.protobuf.Empty
	1,  // 8: nitella.geoip.GeoIPAdminService.Lookup:input_type -> nitella.geoip.LookupRequest
	20, // 9: nitella.geoip.GeoIPAdminService.GetStatus:input_type -> google.protobuf.Empty
	3,  // 10: nitella.geoip.GeoIPAdminService.LoadLocalDB:input_type -> nitella.geoip.LoadLocalDBRequest
	20, // 11: nitella.geoip.GeoIPAdminService.UnloadLocalDB:input_type -> google.protobuf.Empty
	20, // 12: nitella.geoip.GeoIPAdminService.GetLocalDBStatus:input_type -> google.protobuf.Empty
	20, // 13: nitella.geoip.GeoIPAdminService.ListProviders:input_type -> google.protobuf.Empty
	8,  // 14: nitella.geoip.GeoIPAdminService.AddProvider:input_type -> nitella.geoip.AddProviderRequest
	9,  // 15: nitella.geoip.GeoIPAdminService.RemoveProvider:input_type -> nitella.geoip.RemoveProviderRequest
	10, // 16: nitella.geoip.GeoIPAdminService.UpdateProvider:input_type -> nitella.geoip.UpdateProviderRequest
	11, // 17: nitella.geoip.GeoIPAdminService.ReorderProviders:input_type -> nitella.geoip.ReorderProvidersRequest
	5,  // 18: nitella.geoip.GeoIPAdminService.EnableProvider:input_type -> nitella.geoip.ProviderNameRequest
	5,  // 19: nitella.geoip.GeoIPAdminService.DisableProvider:input_type -> nitella.geoip.ProviderNameRequest
	5,  // 20: nitella.geoip.GeoIPAdminService.GetProviderStats:input_type -> nitella.geoip.ProviderNameRequest
	20, // 21: nitella.geoip.GeoIPAdminService.GetCacheStats:input_type -> google.protobuf.Empty
	15, // 22: nitella.geoip.GeoIPAdminService.ClearCache:input_type -> nitella.geoip.ClearCacheRequest
	20, // 23: nitella.geoip.GeoIPAdminService.GetCacheSettings:input_type -> google.protobuf.Empty
	17, // 24: nitella.geoip.GeoIPAdminService.UpdateCacheSettings:input_type -> nitella.geoip.UpdateCacheSettingsRequest
	20, // 25: nitella.geoip.GeoIPAdminService.VacuumL2:input_type -> google.protobuf.Empty
	20, // 26: nitella.geoip.GeoIPAdminService.GetStrategy:input_type -> google.protobuf.Empty
	19, // 27: nitella.geoip.GeoIPAdminService.SetStrategy:input_type -> nitella.geoip.SetStrategyRequest
	20, // 28: nitella.geoip.GeoIPAdminService.ReloadConfig:input_type -> google.protobuf.Empty
	20, // 29: nitella.geoip.GeoIPAdminService.SaveConfig:input_type -> google.protobuf.Empty
	21, // 30: nitella.geoip.GeoIPService.Lookup:output_type -> nitella.GeoInfo
	2,  // 31: nitella.geoip.GeoIPService.GetStatus:output_type -> nitella.geoip.ServiceStatus
	21, // 32: nitella.geoip.GeoIPAdminService.Lookup:output_type -> nitella.GeoInfo
	2,  // 33: nitella.geoip.GeoIPAdminService.GetStatus:output_type -> nitella.geoip.ServiceStatus
	20, // 34: nitella.geoip.GeoIPAdminService.LoadLocalDB:output_type -> google.protobuf.Empty
	20, // 35: nitella.geoip.GeoIPAdminService.UnloadLocalDB:output_type -> google.protobuf.Empty
	4,  // 36: nitella.geoip.GeoIPAdminService.GetLocalDBStatus:output_type -> nitella.geoip.LocalDBStatus
	6,  // 37: nitella.geoip.GeoIPAdminService.ListProviders:output_type -> nitella.geoip.ListProvidersResponse
	7,  // 38: nitella.geoip.GeoIPAdminService.AddProvider:output_type -> nitella.geoip.ProviderInfo
	20, // 39: nitella.geoip.GeoIPAdminService.RemoveProvider:output_type -> google.protobuf.Empty
	7,  // 40: nitella.geoip.GeoIPAdminService.UpdateProvider:output_type -> nitella.geoip.ProviderInfo
	6,  // 41: nitella.geoip.GeoIPAdminService.ReorderProviders:output_type -> nitella.geoip.ListProvidersResponse
	20, // 42: nitella.geoip.GeoIPAdminService.EnableProvider:output_type -> google.protobuf.Empty
	20, // 43: nitella.geoip.GeoIPAdminService.DisableProvider:output_type -> google.protobuf.Empty
	12, // 44: nitella.geoip.GeoIPAdminService.GetProviderStats:output_type -> nitella.geoip.ProviderStats
	14, // 45: nitella.geoip.GeoIPAdminService.GetCacheStats:output_type -> nitella.geoip.CacheStats
	20, // 46: nitella.geoip.GeoIPAdminService.ClearCache:output_type -> google.protobuf.Empty
	16, // 47: nitella.geoip.GeoIPAdminService.GetCacheSettings:output_type -> nitella.geoip.CacheSettings
	16, // 48: nitella.geoip.GeoIPAdminService.UpdateCacheSettings:output_type -> nitella.geoip.CacheSettings
	20, // 49: nitella.geoip.GeoIPAdminService.VacuumL2:output_type -> google.protobuf.Empty
	18, // 50: nitella.geoip.GeoIPAdminService.GetStrategy:output_type -> nitella.geoip.StrategyResponse
	18, // 51: nitella.geoip.GeoIPAdminService.SetStrategy:output_type -> nitella.geoip.StrategyResponse
	20, // 52: nitella.geoip.GeoIPAdminService.ReloadConfig:output_type -> google.protobuf.Empty
	20, // 53: nitella.geoip.GeoIPAdminService.SaveConfig:output_type -> google.protobuf.Empty
	30, // [30:54] is the sub-list for method output_type
	6,  // [6:30] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_geoip_geoip_proto_init() }
func file_geoip_geoip_proto_init() {
	if File_geoip_geoip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geoip_geoip_proto_rawDesc), len(file_geoip_geoip_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_geoip_geoip_proto_goTypes,
		DependencyIndexes: file_geoip_geoip_proto_depIdxs,
		EnumInfos:         file_geoip_geoip_proto_enumTypes,
		MessageInfos:      file_geoip_geoip_proto_msgTypes,
	}.Build()
	File_geoip_geoip_proto = out.File
	file_geoip_geoip_proto_goTypes = nil
	file_geoip_geoip_proto_depIdxs = nil
}
