# syntax=docker/dockerfile:1

ARG BUILDER_IMAGE=nitella-builder:unstable
FROM ${BUILDER_IMAGE} AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN --mount=type=cache,id=go-mod-cache,target=/go/pkg/mod \
    go mod download

COPY . .
RUN --mount=type=cache,id=go-build-cache,target=/root/.cache/go-build \
    --mount=type=cache,id=go-mod-cache,target=/go/pkg/mod \
    go build -o hubctl ./cmd/hubctl

FROM alpine:3.19
RUN apk add --no-cache ca-certificates netcat-openbsd
WORKDIR /app
COPY --from=builder /app/hubctl .

ENTRYPOINT ["./hubctl"]
