# syntax=docker/dockerfile:1

ARG BUILDER_IMAGE=nitella-builder:unstable
FROM --platform=$BUILDPLATFORM ${BUILDER_IMAGE} AS builder
ARG TARGETPLATFORM

WORKDIR /app
COPY go.mod go.sum ./
RUN --mount=type=cache,id=go-mod-cache,target=/go/pkg/mod \
    go mod download

COPY . .
RUN --mount=type=cache,id=go-build-cache,target=/root/.cache/go-build \
    --mount=type=cache,id=go-mod-cache,target=/go/pkg/mod \
    set -eux; \
    CGO_ENABLED=0 xx-go build -ldflags="-s -w" -o hubctl ./cmd/hubctl; \
    xx-verify hubctl

FROM alpine:3.19
RUN apk add --no-cache ca-certificates netcat-openbsd
WORKDIR /app
COPY --from=builder /app/hubctl .

ENTRYPOINT ["./hubctl"]
