// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.

import 'dart:async';
import 'package:synurang/synurang.dart' as synurang;
import 'nitella_local.pb.dart';
import 'package:protobuf/well_known_types/google/protobuf/empty.pb.dart';
import 'package:nitella_app/proxy/proxy.pb.dart' show ConfigureGeoIPResponse, GetGeoIPStatusResponse, RestartListenersResponse, Rule;

class MobileLogicServiceFfi {
  static Future<InitializeResponse> Initialize(InitializeRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/Initialize', bytes);
    return InitializeResponse.fromBuffer(resultBytes);
  }

  static Future<Empty> Shutdown(Empty request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/Shutdown', bytes);
    return Empty.fromBuffer(resultBytes);
  }

  static Future<BootstrapStateResponse> GetBootstrapState(Empty request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetBootstrapState', bytes);
    return BootstrapStateResponse.fromBuffer(resultBytes);
  }

  static Future<IdentityInfo> GetIdentity(Empty request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetIdentity', bytes);
    return IdentityInfo.fromBuffer(resultBytes);
  }

  static Future<CreateIdentityResponse> CreateIdentity(CreateIdentityRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/CreateIdentity', bytes);
    return CreateIdentityResponse.fromBuffer(resultBytes);
  }

  static Future<RestoreIdentityResponse> RestoreIdentity(RestoreIdentityRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/RestoreIdentity', bytes);
    return RestoreIdentityResponse.fromBuffer(resultBytes);
  }

  static Future<ImportIdentityResponse> ImportIdentity(ImportIdentityRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ImportIdentity', bytes);
    return ImportIdentityResponse.fromBuffer(resultBytes);
  }

  static Future<UnlockIdentityResponse> UnlockIdentity(UnlockIdentityRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/UnlockIdentity', bytes);
    return UnlockIdentityResponse.fromBuffer(resultBytes);
  }

  static Future<Empty> LockIdentity(Empty request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/LockIdentity', bytes);
    return Empty.fromBuffer(resultBytes);
  }

  static Future<Empty> ChangePassphrase(ChangePassphraseRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ChangePassphrase', bytes);
    return Empty.fromBuffer(resultBytes);
  }

  static Future<EvaluatePassphraseResponse> EvaluatePassphrase(EvaluatePassphraseRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/EvaluatePassphrase', bytes);
    return EvaluatePassphraseResponse.fromBuffer(resultBytes);
  }

  static Future<Empty> ResetIdentity(Empty request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ResetIdentity', bytes);
    return Empty.fromBuffer(resultBytes);
  }

  static Future<ListNodesResponse> ListNodes(ListNodesRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ListNodes', bytes);
    return ListNodesResponse.fromBuffer(resultBytes);
  }

  static Future<NodeInfo> GetNode(GetNodeRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetNode', bytes);
    return NodeInfo.fromBuffer(resultBytes);
  }

  static Future<NodeDetailSnapshot> GetNodeDetailSnapshot(GetNodeDetailSnapshotRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetNodeDetailSnapshot', bytes);
    return NodeDetailSnapshot.fromBuffer(resultBytes);
  }

  static Future<NodeInfo> UpdateNode(UpdateNodeRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/UpdateNode', bytes);
    return NodeInfo.fromBuffer(resultBytes);
  }

  static Future<Empty> RemoveNode(RemoveNodeRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/RemoveNode', bytes);
    return Empty.fromBuffer(resultBytes);
  }

  static Future<AddNodeDirectResponse> AddNodeDirect(AddNodeDirectRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/AddNodeDirect', bytes);
    return AddNodeDirectResponse.fromBuffer(resultBytes);
  }

  static Future<TestDirectConnectionResponse> TestDirectConnection(TestDirectConnectionRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/TestDirectConnection', bytes);
    return TestDirectConnectionResponse.fromBuffer(resultBytes);
  }

  static Future<ListProxiesResponse> ListProxies(ListProxiesRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ListProxies', bytes);
    return ListProxiesResponse.fromBuffer(resultBytes);
  }

  static Future<GetProxiesSnapshotResponse> GetProxiesSnapshot(GetProxiesSnapshotRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetProxiesSnapshot', bytes);
    return GetProxiesSnapshotResponse.fromBuffer(resultBytes);
  }

  static Future<ProxyInfo> GetProxy(GetProxyRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetProxy', bytes);
    return ProxyInfo.fromBuffer(resultBytes);
  }

  static Future<ProxyInfo> AddProxy(AddProxyRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/AddProxy', bytes);
    return ProxyInfo.fromBuffer(resultBytes);
  }

  static Future<ProxyInfo> UpdateProxy(UpdateProxyRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/UpdateProxy', bytes);
    return ProxyInfo.fromBuffer(resultBytes);
  }

  static Future<SetNodeProxiesRunningResponse> SetNodeProxiesRunning(SetNodeProxiesRunningRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/SetNodeProxiesRunning', bytes);
    return SetNodeProxiesRunningResponse.fromBuffer(resultBytes);
  }

  static Future<Empty> RemoveProxy(RemoveProxyRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/RemoveProxy', bytes);
    return Empty.fromBuffer(resultBytes);
  }

  static Future<ListRulesResponse> ListRules(ListRulesRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ListRules', bytes);
    return ListRulesResponse.fromBuffer(resultBytes);
  }

  static Future<Rule> GetRule(GetRuleRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetRule', bytes);
    return Rule.fromBuffer(resultBytes);
  }

  static Future<Rule> AddRule(AddRuleRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/AddRule', bytes);
    return Rule.fromBuffer(resultBytes);
  }

  static Future<AddQuickRuleResponse> AddQuickRule(AddQuickRuleRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/AddQuickRule', bytes);
    return AddQuickRuleResponse.fromBuffer(resultBytes);
  }

  static Future<Rule> UpdateRule(UpdateRuleRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/UpdateRule', bytes);
    return Rule.fromBuffer(resultBytes);
  }

  static Future<Empty> RemoveRule(RemoveRuleRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/RemoveRule', bytes);
    return Empty.fromBuffer(resultBytes);
  }

  static Future<BlockIPResponse> BlockIP(BlockIPRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/BlockIP', bytes);
    return BlockIPResponse.fromBuffer(resultBytes);
  }

  static Future<BlockISPResponse> BlockISP(BlockISPRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/BlockISP', bytes);
    return BlockISPResponse.fromBuffer(resultBytes);
  }

  static Future<BlockCountryResponse> BlockCountry(BlockCountryRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/BlockCountry', bytes);
    return BlockCountryResponse.fromBuffer(resultBytes);
  }

  static Future<AddGlobalRuleResponse> AddGlobalRule(AddGlobalRuleRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/AddGlobalRule', bytes);
    return AddGlobalRuleResponse.fromBuffer(resultBytes);
  }

  static Future<ListGlobalRulesResponse> ListGlobalRules(ListGlobalRulesRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ListGlobalRules', bytes);
    return ListGlobalRulesResponse.fromBuffer(resultBytes);
  }

  static Future<RemoveGlobalRuleResponse> RemoveGlobalRule(RemoveGlobalRuleRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/RemoveGlobalRule', bytes);
    return RemoveGlobalRuleResponse.fromBuffer(resultBytes);
  }

  static Future<ListPendingApprovalsResponse> ListPendingApprovals(ListPendingApprovalsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ListPendingApprovals', bytes);
    return ListPendingApprovalsResponse.fromBuffer(resultBytes);
  }

  static Future<GetApprovalsSnapshotResponse> GetApprovalsSnapshot(GetApprovalsSnapshotRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetApprovalsSnapshot', bytes);
    return GetApprovalsSnapshotResponse.fromBuffer(resultBytes);
  }

  static Future<ApproveRequestResponse> ApproveRequest(ApproveRequestRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ApproveRequest', bytes);
    return ApproveRequestResponse.fromBuffer(resultBytes);
  }

  static Future<DenyRequestResponse> DenyRequest(DenyRequestRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/DenyRequest', bytes);
    return DenyRequestResponse.fromBuffer(resultBytes);
  }

  static Future<ResolveApprovalDecisionResponse> ResolveApprovalDecision(ResolveApprovalDecisionRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ResolveApprovalDecision', bytes);
    return ResolveApprovalDecisionResponse.fromBuffer(resultBytes);
  }

  static Stream<ApprovalRequest> StreamApprovals(StreamApprovalsRequest request) {
    final bytes = request.writeToBuffer();
    return synurang.invokeBackendServerStream('/nitella.local.MobileLogicService/StreamApprovals', bytes)
        .map((data) => ApprovalRequest.fromBuffer(data));
  }

  static Future<ListApprovalHistoryResponse> ListApprovalHistory(ListApprovalHistoryRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ListApprovalHistory', bytes);
    return ListApprovalHistoryResponse.fromBuffer(resultBytes);
  }

  static Future<ClearApprovalHistoryResponse> ClearApprovalHistory(ClearApprovalHistoryRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ClearApprovalHistory', bytes);
    return ClearApprovalHistoryResponse.fromBuffer(resultBytes);
  }

  static Future<ConnectionStats> GetConnectionStats(GetConnectionStatsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetConnectionStats', bytes);
    return ConnectionStats.fromBuffer(resultBytes);
  }

  static Future<ListConnectionsResponse> ListConnections(ListConnectionsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ListConnections', bytes);
    return ListConnectionsResponse.fromBuffer(resultBytes);
  }

  static Future<GetIPStatsResponse> GetIPStats(GetIPStatsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetIPStats', bytes);
    return GetIPStatsResponse.fromBuffer(resultBytes);
  }

  static Future<GetGeoStatsResponse> GetGeoStats(GetGeoStatsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetGeoStats', bytes);
    return GetGeoStatsResponse.fromBuffer(resultBytes);
  }

  static Stream<ConnectionEvent> StreamConnections(StreamConnectionsRequest request) {
    final bytes = request.writeToBuffer();
    return synurang.invokeBackendServerStream('/nitella.local.MobileLogicService/StreamConnections', bytes)
        .map((data) => ConnectionEvent.fromBuffer(data));
  }

  static Future<CloseConnectionResponse> CloseConnection(CloseConnectionRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/CloseConnection', bytes);
    return CloseConnectionResponse.fromBuffer(resultBytes);
  }

  static Future<CloseAllConnectionsResponse> CloseAllConnections(CloseAllConnectionsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/CloseAllConnections', bytes);
    return CloseAllConnectionsResponse.fromBuffer(resultBytes);
  }

  static Future<CloseAllNodeConnectionsResponse> CloseAllNodeConnections(CloseAllNodeConnectionsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/CloseAllNodeConnections', bytes);
    return CloseAllNodeConnectionsResponse.fromBuffer(resultBytes);
  }

  static Future<StartPairingResponse> StartPairing(StartPairingRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/StartPairing', bytes);
    return StartPairingResponse.fromBuffer(resultBytes);
  }

  static Future<JoinPairingResponse> JoinPairing(JoinPairingRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/JoinPairing', bytes);
    return JoinPairingResponse.fromBuffer(resultBytes);
  }

  static Future<CompletePairingResponse> CompletePairing(CompletePairingRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/CompletePairing', bytes);
    return CompletePairingResponse.fromBuffer(resultBytes);
  }

  static Future<FinalizePairingResponse> FinalizePairing(FinalizePairingRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/FinalizePairing', bytes);
    return FinalizePairingResponse.fromBuffer(resultBytes);
  }

  static Future<Empty> CancelPairing(CancelPairingRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/CancelPairing', bytes);
    return Empty.fromBuffer(resultBytes);
  }

  static Future<GenerateQRCodeResponse> GenerateQRCode(GenerateQRCodeRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GenerateQRCode', bytes);
    return GenerateQRCodeResponse.fromBuffer(resultBytes);
  }

  static Future<ScanQRCodeResponse> ScanQRCode(ScanQRCodeRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ScanQRCode', bytes);
    return ScanQRCodeResponse.fromBuffer(resultBytes);
  }

  static Future<GenerateQRReplyResponse> GenerateQRResponse(GenerateQRReplyRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GenerateQRResponse', bytes);
    return GenerateQRReplyResponse.fromBuffer(resultBytes);
  }

  static Future<ListTemplatesResponse> ListTemplates(ListTemplatesRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ListTemplates', bytes);
    return ListTemplatesResponse.fromBuffer(resultBytes);
  }

  static Future<Template> GetTemplate(GetTemplateRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetTemplate', bytes);
    return Template.fromBuffer(resultBytes);
  }

  static Future<Template> CreateTemplate(CreateTemplateRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/CreateTemplate', bytes);
    return Template.fromBuffer(resultBytes);
  }

  static Future<ApplyTemplateResponse> ApplyTemplate(ApplyTemplateRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ApplyTemplate', bytes);
    return ApplyTemplateResponse.fromBuffer(resultBytes);
  }

  static Future<Empty> DeleteTemplate(DeleteTemplateRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/DeleteTemplate', bytes);
    return Empty.fromBuffer(resultBytes);
  }

  static Future<SyncTemplatesResponse> SyncTemplates(Empty request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/SyncTemplates', bytes);
    return SyncTemplatesResponse.fromBuffer(resultBytes);
  }

  static Future<ExportTemplateYamlResponse> ExportTemplateYaml(ExportTemplateYamlRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ExportTemplateYaml', bytes);
    return ExportTemplateYamlResponse.fromBuffer(resultBytes);
  }

  static Future<ImportTemplateYamlResponse> ImportTemplateYaml(ImportTemplateYamlRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ImportTemplateYaml', bytes);
    return ImportTemplateYamlResponse.fromBuffer(resultBytes);
  }

  static Future<Settings> GetSettings(Empty request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetSettings', bytes);
    return Settings.fromBuffer(resultBytes);
  }

  static Future<SettingsOverviewSnapshot> GetSettingsOverviewSnapshot(Empty request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetSettingsOverviewSnapshot', bytes);
    return SettingsOverviewSnapshot.fromBuffer(resultBytes);
  }

  static Future<Settings> UpdateSettings(UpdateSettingsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/UpdateSettings', bytes);
    return Settings.fromBuffer(resultBytes);
  }

  static Future<Empty> RegisterFCMToken(RegisterFCMTokenRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/RegisterFCMToken', bytes);
    return Empty.fromBuffer(resultBytes);
  }

  static Future<Empty> UnregisterFCMToken(Empty request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/UnregisterFCMToken', bytes);
    return Empty.fromBuffer(resultBytes);
  }

  static Future<ConnectToHubResponse> ConnectToHub(ConnectToHubRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ConnectToHub', bytes);
    return ConnectToHubResponse.fromBuffer(resultBytes);
  }

  static Future<Empty> DisconnectFromHub(Empty request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/DisconnectFromHub', bytes);
    return Empty.fromBuffer(resultBytes);
  }

  static Future<HubStatus> GetHubStatus(Empty request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetHubStatus', bytes);
    return HubStatus.fromBuffer(resultBytes);
  }

  static Future<HubSettingsSnapshot> GetHubSettingsSnapshot(Empty request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetHubSettingsSnapshot', bytes);
    return HubSettingsSnapshot.fromBuffer(resultBytes);
  }

  static Future<HubOverview> GetHubOverview(Empty request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetHubOverview', bytes);
    return HubOverview.fromBuffer(resultBytes);
  }

  static Future<HubDashboardSnapshot> GetHubDashboardSnapshot(GetHubDashboardSnapshotRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetHubDashboardSnapshot', bytes);
    return HubDashboardSnapshot.fromBuffer(resultBytes);
  }

  static Future<RegisterUserResponse> RegisterUser(RegisterUserRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/RegisterUser', bytes);
    return RegisterUserResponse.fromBuffer(resultBytes);
  }

  static Future<FetchHubCAResponse> FetchHubCA(FetchHubCARequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/FetchHubCA', bytes);
    return FetchHubCAResponse.fromBuffer(resultBytes);
  }

  static Future<OnboardHubResponse> OnboardHub(OnboardHubRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/OnboardHub', bytes);
    return OnboardHubResponse.fromBuffer(resultBytes);
  }

  static Future<OnboardHubResponse> EnsureHubConnected(EnsureHubConnectedRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/EnsureHubConnected', bytes);
    return OnboardHubResponse.fromBuffer(resultBytes);
  }

  static Future<OnboardHubResponse> EnsureHubRegistered(EnsureHubRegisteredRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/EnsureHubRegistered', bytes);
    return OnboardHubResponse.fromBuffer(resultBytes);
  }

  static Future<OnboardHubResponse> ResolveHubTrustChallenge(ResolveHubTrustChallengeRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ResolveHubTrustChallenge', bytes);
    return OnboardHubResponse.fromBuffer(resultBytes);
  }

  static Future<P2PStatus> GetP2PStatus(Empty request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetP2PStatus', bytes);
    return P2PStatus.fromBuffer(resultBytes);
  }

  static Future<P2PSettingsSnapshot> GetP2PSettingsSnapshot(Empty request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetP2PSettingsSnapshot', bytes);
    return P2PSettingsSnapshot.fromBuffer(resultBytes);
  }

  static Stream<P2PStatus> StreamP2PStatus(Empty request) {
    final bytes = request.writeToBuffer();
    return synurang.invokeBackendServerStream('/nitella.local.MobileLogicService/StreamP2PStatus', bytes)
        .map((data) => P2PStatus.fromBuffer(data));
  }

  static Future<Empty> SetP2PMode(SetP2PModeRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/SetP2PMode', bytes);
    return Empty.fromBuffer(resultBytes);
  }

  static Future<LookupIPResponse> LookupIP(LookupIPRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/LookupIP', bytes);
    return LookupIPResponse.fromBuffer(resultBytes);
  }

  static Future<ConfigureGeoIPResponse> ConfigureGeoIP(ConfigureGeoIPNodeRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ConfigureGeoIP', bytes);
    return ConfigureGeoIPResponse.fromBuffer(resultBytes);
  }

  static Future<GetGeoIPStatusResponse> GetGeoIPStatus(GetGeoIPStatusNodeRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetGeoIPStatus', bytes);
    return GetGeoIPStatusResponse.fromBuffer(resultBytes);
  }

  static Future<RestartListenersResponse> RestartListeners(RestartListenersNodeRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/RestartListeners', bytes);
    return RestartListenersResponse.fromBuffer(resultBytes);
  }

  static Future<ListLocalProxyConfigsResponse> ListLocalProxyConfigs(ListLocalProxyConfigsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ListLocalProxyConfigs', bytes);
    return ListLocalProxyConfigsResponse.fromBuffer(resultBytes);
  }

  static Future<GetLocalProxyConfigResponse> GetLocalProxyConfig(GetLocalProxyConfigRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetLocalProxyConfig', bytes);
    return GetLocalProxyConfigResponse.fromBuffer(resultBytes);
  }

  static Future<ImportLocalProxyConfigResponse> ImportLocalProxyConfig(ImportLocalProxyConfigRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ImportLocalProxyConfig', bytes);
    return ImportLocalProxyConfigResponse.fromBuffer(resultBytes);
  }

  static Future<SaveLocalProxyConfigResponse> SaveLocalProxyConfig(SaveLocalProxyConfigRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/SaveLocalProxyConfig', bytes);
    return SaveLocalProxyConfigResponse.fromBuffer(resultBytes);
  }

  static Future<DeleteLocalProxyConfigResponse> DeleteLocalProxyConfig(DeleteLocalProxyConfigRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/DeleteLocalProxyConfig', bytes);
    return DeleteLocalProxyConfigResponse.fromBuffer(resultBytes);
  }

  static Future<ValidateLocalProxyConfigResponse> ValidateLocalProxyConfig(ValidateLocalProxyConfigRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ValidateLocalProxyConfig', bytes);
    return ValidateLocalProxyConfigResponse.fromBuffer(resultBytes);
  }

  static Future<PushProxyRevisionResponse> PushProxyRevision(PushProxyRevisionRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/PushProxyRevision', bytes);
    return PushProxyRevisionResponse.fromBuffer(resultBytes);
  }

  static Future<PushLocalProxyRevisionResponse> PushLocalProxyRevision(PushLocalProxyRevisionRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/PushLocalProxyRevision', bytes);
    return PushLocalProxyRevisionResponse.fromBuffer(resultBytes);
  }

  static Future<PullProxyRevisionResponse> PullProxyRevision(PullProxyRevisionRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/PullProxyRevision', bytes);
    return PullProxyRevisionResponse.fromBuffer(resultBytes);
  }

  static Future<DiffProxyRevisionsResponse> DiffProxyRevisions(DiffProxyRevisionsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/DiffProxyRevisions', bytes);
    return DiffProxyRevisionsResponse.fromBuffer(resultBytes);
  }

  static Future<ListProxyRevisionsResponse> ListProxyRevisions(ListProxyRevisionsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ListProxyRevisions', bytes);
    return ListProxyRevisionsResponse.fromBuffer(resultBytes);
  }

  static Future<FlushProxyRevisionsResponse> FlushProxyRevisions(FlushProxyRevisionsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/FlushProxyRevisions', bytes);
    return FlushProxyRevisionsResponse.fromBuffer(resultBytes);
  }

  static Future<ListProxyConfigsResponse> ListProxyConfigs(ListProxyConfigsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ListProxyConfigs', bytes);
    return ListProxyConfigsResponse.fromBuffer(resultBytes);
  }

  static Future<CreateProxyConfigResponse> CreateProxyConfig(CreateProxyConfigRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/CreateProxyConfig', bytes);
    return CreateProxyConfigResponse.fromBuffer(resultBytes);
  }

  static Future<DeleteProxyConfigResponse> DeleteProxyConfig(DeleteProxyConfigRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/DeleteProxyConfig', bytes);
    return DeleteProxyConfigResponse.fromBuffer(resultBytes);
  }

  static Future<ApplyProxyToNodeResponse> ApplyProxyToNode(ApplyProxyToNodeRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ApplyProxyToNode', bytes);
    return ApplyProxyToNodeResponse.fromBuffer(resultBytes);
  }

  static Future<UnapplyProxyFromNodeResponse> UnapplyProxyFromNode(UnapplyProxyFromNodeRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/UnapplyProxyFromNode', bytes);
    return UnapplyProxyFromNodeResponse.fromBuffer(resultBytes);
  }

  static Future<GetAppliedProxiesResponse> GetAppliedProxies(GetAppliedProxiesRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetAppliedProxies', bytes);
    return GetAppliedProxiesResponse.fromBuffer(resultBytes);
  }

  static Future<AllowIPResponse> AllowIP(AllowIPRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/AllowIP', bytes);
    return AllowIPResponse.fromBuffer(resultBytes);
  }

  static Stream<NodeMetrics> StreamMetrics(StreamMetricsRequest request) {
    final bytes = request.writeToBuffer();
    return synurang.invokeBackendServerStream('/nitella.local.MobileLogicService/StreamMetrics', bytes)
        .map((data) => NodeMetrics.fromBuffer(data));
  }

  static Future<DebugRuntimeStats> GetDebugRuntimeStats(GetDebugRuntimeStatsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetDebugRuntimeStats', bytes);
    return DebugRuntimeStats.fromBuffer(resultBytes);
  }

  static Future<GetLogsStatsResponse> GetLogsStats(GetLogsStatsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetLogsStats', bytes);
    return GetLogsStatsResponse.fromBuffer(resultBytes);
  }

  static Future<ListLogsResponse> ListLogs(ListLogsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/ListLogs', bytes);
    return ListLogsResponse.fromBuffer(resultBytes);
  }

  static Future<DeleteLogsResponse> DeleteLogs(DeleteLogsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/DeleteLogs', bytes);
    return DeleteLogsResponse.fromBuffer(resultBytes);
  }

  static Future<CleanupOldLogsResponse> CleanupOldLogs(CleanupOldLogsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/CleanupOldLogs', bytes);
    return CleanupOldLogsResponse.fromBuffer(resultBytes);
  }

  static Future<GetNodeFromHubResponse> GetNodeFromHub(GetNodeFromHubRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/GetNodeFromHub', bytes);
    return GetNodeFromHubResponse.fromBuffer(resultBytes);
  }

  static Future<RegisterNodeWithHubResponse> RegisterNodeWithHub(RegisterNodeWithHubRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.local.MobileLogicService/RegisterNodeWithHub', bytes);
    return RegisterNodeWithHubResponse.fromBuffer(resultBytes);
  }

}

