// Code generated by protoc-gen-synurang-ffi. DO NOT EDIT.

import 'dart:async';
import 'dart:typed_data';
import 'package:synurang/synurang.dart' as synurang;
import 'process.pb.dart';

class ProcessControlFfi {
  static Future<StartListenerResponse> StartListener(StartListenerRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.process.ProcessControl/StartListener', bytes);
    return StartListenerResponse.fromBuffer(resultBytes);
  }

  static Future<StopListenerResponse> StopListener(StopListenerRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.process.ProcessControl/StopListener', bytes);
    return StopListenerResponse.fromBuffer(resultBytes);
  }

  static Future<HealthCheckResponse> HealthCheck(HealthCheckRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.process.ProcessControl/HealthCheck', bytes);
    return HealthCheckResponse.fromBuffer(resultBytes);
  }

  static Future<GetMetricsResponse> GetMetrics(GetMetricsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.process.ProcessControl/GetMetrics', bytes);
    return GetMetricsResponse.fromBuffer(resultBytes);
  }

  static Future<AddRuleResponse> AddRule(AddRuleRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.process.ProcessControl/AddRule', bytes);
    return AddRuleResponse.fromBuffer(resultBytes);
  }

  static Future<RemoveRuleResponse> RemoveRule(RemoveRuleRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.process.ProcessControl/RemoveRule', bytes);
    return RemoveRuleResponse.fromBuffer(resultBytes);
  }

  static Future<ListRulesResponse> ListRules(ListRulesRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.process.ProcessControl/ListRules', bytes);
    return ListRulesResponse.fromBuffer(resultBytes);
  }

  static Future<GetActiveConnectionsResponse> GetActiveConnections(GetActiveConnectionsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.process.ProcessControl/GetActiveConnections', bytes);
    return GetActiveConnectionsResponse.fromBuffer(resultBytes);
  }

  static Future<CloseConnectionResponse> CloseConnection(CloseConnectionRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.process.ProcessControl/CloseConnection', bytes);
    return CloseConnectionResponse.fromBuffer(resultBytes);
  }

  static Future<CloseAllConnectionsResponse> CloseAllConnections(CloseAllConnectionsRequest request) async {
    final bytes = request.writeToBuffer();
    final resultBytes = await synurang.invokeBackendAsync('/nitella.process.ProcessControl/CloseAllConnections', bytes);
    return CloseAllConnectionsResponse.fromBuffer(resultBytes);
  }

  static Stream<Event> StreamEvents(StreamEventsRequest request) {
    final bytes = request.writeToBuffer();
    return synurang.invokeBackendServerStream('/nitella.process.ProcessControl/StreamEvents', bytes)
        .map((data) => Event.fromBuffer(data));
  }

}

