// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: process/process.proto

package process

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	common "github.com/ivere27/nitella/pkg/api/common"
	proxy "github.com/ivere27/nitella/pkg/api/proxy"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartListenerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ListenAddr     string                 `protobuf:"bytes,3,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	DefaultBackend string                 `protobuf:"bytes,4,opt,name=default_backend,json=defaultBackend,proto3" json:"default_backend,omitempty"`
	DefaultAction  common.ActionType      `protobuf:"varint,5,opt,name=default_action,json=defaultAction,proto3,enum=nitella.ActionType" json:"default_action,omitempty"`
	DefaultMock    *proxy.MockConfig      `protobuf:"bytes,6,opt,name=default_mock,json=defaultMock,proto3" json:"default_mock,omitempty"`
	CertPem        string                 `protobuf:"bytes,7,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	KeyPem         string                 `protobuf:"bytes,8,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
	CaPem          string                 `protobuf:"bytes,9,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	ClientAuthType proxy.ClientAuthType   `protobuf:"varint,10,opt,name=client_auth_type,json=clientAuthType,proto3,enum=nitella.proxy.ClientAuthType" json:"client_auth_type,omitempty"`
	FallbackAction common.FallbackAction  `protobuf:"varint,11,opt,name=fallback_action,json=fallbackAction,proto3,enum=nitella.FallbackAction" json:"fallback_action,omitempty"`
	FallbackMock   common.MockPreset      `protobuf:"varint,12,opt,name=fallback_mock,json=fallbackMock,proto3,enum=nitella.MockPreset" json:"fallback_mock,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartListenerRequest) Reset() {
	*x = StartListenerRequest{}
	mi := &file_process_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartListenerRequest) ProtoMessage() {}

func (x *StartListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartListenerRequest.ProtoReflect.Descriptor instead.
func (*StartListenerRequest) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{0}
}

func (x *StartListenerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartListenerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartListenerRequest) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *StartListenerRequest) GetDefaultBackend() string {
	if x != nil {
		return x.DefaultBackend
	}
	return ""
}

func (x *StartListenerRequest) GetDefaultAction() common.ActionType {
	if x != nil {
		return x.DefaultAction
	}
	return common.ActionType(0)
}

func (x *StartListenerRequest) GetDefaultMock() *proxy.MockConfig {
	if x != nil {
		return x.DefaultMock
	}
	return nil
}

func (x *StartListenerRequest) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *StartListenerRequest) GetKeyPem() string {
	if x != nil {
		return x.KeyPem
	}
	return ""
}

func (x *StartListenerRequest) GetCaPem() string {
	if x != nil {
		return x.CaPem
	}
	return ""
}

func (x *StartListenerRequest) GetClientAuthType() proxy.ClientAuthType {
	if x != nil {
		return x.ClientAuthType
	}
	return proxy.ClientAuthType(0)
}

func (x *StartListenerRequest) GetFallbackAction() common.FallbackAction {
	if x != nil {
		return x.FallbackAction
	}
	return common.FallbackAction(0)
}

func (x *StartListenerRequest) GetFallbackMock() common.MockPreset {
	if x != nil {
		return x.FallbackMock
	}
	return common.MockPreset(0)
}

type StartListenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartListenerResponse) Reset() {
	*x = StartListenerResponse{}
	mi := &file_process_process_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartListenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartListenerResponse) ProtoMessage() {}

func (x *StartListenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartListenerResponse.ProtoReflect.Descriptor instead.
func (*StartListenerResponse) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{1}
}

func (x *StartListenerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartListenerResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StopListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopListenerRequest) Reset() {
	*x = StopListenerRequest{}
	mi := &file_process_process_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopListenerRequest) ProtoMessage() {}

func (x *StopListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopListenerRequest.ProtoReflect.Descriptor instead.
func (*StopListenerRequest) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{2}
}

type StopListenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopListenerResponse) Reset() {
	*x = StopListenerResponse{}
	mi := &file_process_process_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopListenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopListenerResponse) ProtoMessage() {}

func (x *StopListenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopListenerResponse.ProtoReflect.Descriptor instead.
func (*StopListenerResponse) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{3}
}

func (x *StopListenerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_process_process_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{4}
}

type HealthCheckResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok", "error", "idle"
	ActiveConnections int32                  `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_process_process_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_process_process_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{6}
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *proxy.ProxyStatus     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_process_process_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{7}
}

func (x *GetMetricsResponse) GetStatus() *proxy.ProxyStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type AddRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *proxy.Rule            `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRuleRequest) Reset() {
	*x = AddRuleRequest{}
	mi := &file_process_process_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRuleRequest) ProtoMessage() {}

func (x *AddRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRuleRequest.ProtoReflect.Descriptor instead.
func (*AddRuleRequest) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{8}
}

func (x *AddRuleRequest) GetRule() *proxy.Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type AddRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRuleResponse) Reset() {
	*x = AddRuleResponse{}
	mi := &file_process_process_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRuleResponse) ProtoMessage() {}

func (x *AddRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRuleResponse.ProtoReflect.Descriptor instead.
func (*AddRuleResponse) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{9}
}

func (x *AddRuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddRuleResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RemoveRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRuleRequest) Reset() {
	*x = RemoveRuleRequest{}
	mi := &file_process_process_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRuleRequest) ProtoMessage() {}

func (x *RemoveRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRuleRequest.ProtoReflect.Descriptor instead.
func (*RemoveRuleRequest) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveRuleRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

type RemoveRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRuleResponse) Reset() {
	*x = RemoveRuleResponse{}
	mi := &file_process_process_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRuleResponse) ProtoMessage() {}

func (x *RemoveRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRuleResponse.ProtoReflect.Descriptor instead.
func (*RemoveRuleResponse) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveRuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_process_process_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{12}
}

type ListRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*proxy.Rule          `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_process_process_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{13}
}

func (x *ListRulesResponse) GetRules() []*proxy.Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type GetActiveConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveConnectionsRequest) Reset() {
	*x = GetActiveConnectionsRequest{}
	mi := &file_process_process_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveConnectionsRequest) ProtoMessage() {}

func (x *GetActiveConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveConnectionsRequest.ProtoReflect.Descriptor instead.
func (*GetActiveConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{14}
}

type GetActiveConnectionsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Connections   []*proxy.ActiveConnection `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveConnectionsResponse) Reset() {
	*x = GetActiveConnectionsResponse{}
	mi := &file_process_process_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveConnectionsResponse) ProtoMessage() {}

func (x *GetActiveConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveConnectionsResponse.ProtoReflect.Descriptor instead.
func (*GetActiveConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{15}
}

func (x *GetActiveConnectionsResponse) GetConnections() []*proxy.ActiveConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type CloseConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        string                 `protobuf:"bytes,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseConnectionRequest) Reset() {
	*x = CloseConnectionRequest{}
	mi := &file_process_process_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseConnectionRequest) ProtoMessage() {}

func (x *CloseConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseConnectionRequest.ProtoReflect.Descriptor instead.
func (*CloseConnectionRequest) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{16}
}

func (x *CloseConnectionRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

type CloseConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseConnectionResponse) Reset() {
	*x = CloseConnectionResponse{}
	mi := &file_process_process_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseConnectionResponse) ProtoMessage() {}

func (x *CloseConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseConnectionResponse.ProtoReflect.Descriptor instead.
func (*CloseConnectionResponse) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{17}
}

func (x *CloseConnectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloseConnectionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CloseAllConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseAllConnectionsRequest) Reset() {
	*x = CloseAllConnectionsRequest{}
	mi := &file_process_process_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAllConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAllConnectionsRequest) ProtoMessage() {}

func (x *CloseAllConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAllConnectionsRequest.ProtoReflect.Descriptor instead.
func (*CloseAllConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{18}
}

type CloseAllConnectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseAllConnectionsResponse) Reset() {
	*x = CloseAllConnectionsResponse{}
	mi := &file_process_process_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAllConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAllConnectionsResponse) ProtoMessage() {}

func (x *CloseAllConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAllConnectionsResponse.ProtoReflect.Descriptor instead.
func (*CloseAllConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{19}
}

func (x *CloseAllConnectionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloseAllConnectionsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_process_process_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{20}
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*Event_Connection
	//	*Event_Log
	//	*Event_Metrics
	Type          isEvent_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_process_process_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{21}
}

func (x *Event) GetType() isEvent_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Event) GetConnection() *proxy.ConnectionEvent {
	if x != nil {
		if x, ok := x.Type.(*Event_Connection); ok {
			return x.Connection
		}
	}
	return nil
}

func (x *Event) GetLog() *LogEvent {
	if x != nil {
		if x, ok := x.Type.(*Event_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *Event) GetMetrics() *MetricsEvent {
	if x != nil {
		if x, ok := x.Type.(*Event_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

type isEvent_Type interface {
	isEvent_Type()
}

type Event_Connection struct {
	Connection *proxy.ConnectionEvent `protobuf:"bytes,1,opt,name=connection,proto3,oneof"`
}

type Event_Log struct {
	Log *LogEvent `protobuf:"bytes,2,opt,name=log,proto3,oneof"`
}

type Event_Metrics struct {
	Metrics *MetricsEvent `protobuf:"bytes,3,opt,name=metrics,proto3,oneof"`
}

func (*Event_Connection) isEvent_Type() {}

func (*Event_Log) isEvent_Type() {}

func (*Event_Metrics) isEvent_Type() {}

type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"` // "debug", "info", "warn", "error"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_process_process_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{22}
}

func (x *LogEvent) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEvent) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type MetricsEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActiveConnections int64                  `protobuf:"varint,1,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	TotalConnections  int64                  `protobuf:"varint,2,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`
	BytesIn           int64                  `protobuf:"varint,3,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut          int64                  `protobuf:"varint,4,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	Timestamp         *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetricsEvent) Reset() {
	*x = MetricsEvent{}
	mi := &file_process_process_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsEvent) ProtoMessage() {}

func (x *MetricsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_process_process_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsEvent.ProtoReflect.Descriptor instead.
func (*MetricsEvent) Descriptor() ([]byte, []int) {
	return file_process_process_proto_rawDescGZIP(), []int{23}
}

func (x *MetricsEvent) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *MetricsEvent) GetTotalConnections() int64 {
	if x != nil {
		return x.TotalConnections
	}
	return 0
}

func (x *MetricsEvent) GetBytesIn() int64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *MetricsEvent) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *MetricsEvent) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_process_process_proto protoreflect.FileDescriptor

const file_process_process_proto_rawDesc = "" +
	"\n" +
	"\x15process/process.proto\x12\x0fnitella.process\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11proxy/proxy.proto\x1a\x13common/common.proto\"\x8e\x04\n" +
	"\x14StartListenerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vlisten_addr\x18\x03 \x01(\tR\n" +
	"listenAddr\x12'\n" +
	"\x0fdefault_backend\x18\x04 \x01(\tR\x0edefaultBackend\x12:\n" +
	"\x0edefault_action\x18\x05 \x01(\x0e2\x13.nitella.ActionTypeR\rdefaultAction\x12<\n" +
	"\fdefault_mock\x18\x06 \x01(\v2\x19.nitella.proxy.MockConfigR\vdefaultMock\x12\x19\n" +
	"\bcert_pem\x18\a \x01(\tR\acertPem\x12\x17\n" +
	"\akey_pem\x18\b \x01(\tR\x06keyPem\x12\x15\n" +
	"\x06ca_pem\x18\t \x01(\tR\x05caPem\x12G\n" +
	"\x10client_auth_type\x18\n" +
	" \x01(\x0e2\x1d.nitella.proxy.ClientAuthTypeR\x0eclientAuthType\x12@\n" +
	"\x0ffallback_action\x18\v \x01(\x0e2\x17.nitella.FallbackActionR\x0efallbackAction\x128\n" +
	"\rfallback_mock\x18\f \x01(\x0e2\x13.nitella.MockPresetR\ffallbackMock\"V\n" +
	"\x15StartListenerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x15\n" +
	"\x13StopListenerRequest\"0\n" +
	"\x14StopListenerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12HealthCheckRequest\"\\\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x05R\x11activeConnections\"\x13\n" +
	"\x11GetMetricsRequest\"H\n" +
	"\x12GetMetricsResponse\x122\n" +
	"\x06status\x18\x01 \x01(\v2\x1a.nitella.proxy.ProxyStatusR\x06status\"9\n" +
	"\x0eAddRuleRequest\x12'\n" +
	"\x04rule\x18\x01 \x01(\v2\x13.nitella.proxy.RuleR\x04rule\"P\n" +
	"\x0fAddRuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\",\n" +
	"\x11RemoveRuleRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\".\n" +
	"\x12RemoveRuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x12\n" +
	"\x10ListRulesRequest\">\n" +
	"\x11ListRulesResponse\x12)\n" +
	"\x05rules\x18\x01 \x03(\v2\x13.nitella.proxy.RuleR\x05rules\"\x1d\n" +
	"\x1bGetActiveConnectionsRequest\"a\n" +
	"\x1cGetActiveConnectionsResponse\x12A\n" +
	"\vconnections\x18\x01 \x03(\v2\x1f.nitella.proxy.ActiveConnectionR\vconnections\"1\n" +
	"\x16CloseConnectionRequest\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\tR\x06connId\"X\n" +
	"\x17CloseConnectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x1c\n" +
	"\x1aCloseAllConnectionsRequest\"\\\n" +
	"\x1bCloseAllConnectionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x15\n" +
	"\x13StreamEventsRequest\"\xbb\x01\n" +
	"\x05Event\x12@\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\x1e.nitella.proxy.ConnectionEventH\x00R\n" +
	"connection\x12-\n" +
	"\x03log\x18\x02 \x01(\v2\x19.nitella.process.LogEventH\x00R\x03log\x129\n" +
	"\ametrics\x18\x03 \x01(\v2\x1d.nitella.process.MetricsEventH\x00R\ametricsB\x06\n" +
	"\x04type\"t\n" +
	"\bLogEvent\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xdc\x01\n" +
	"\fMetricsEvent\x12-\n" +
	"\x12active_connections\x18\x01 \x01(\x03R\x11activeConnections\x12+\n" +
	"\x11total_connections\x18\x02 \x01(\x03R\x10totalConnections\x12\x19\n" +
	"\bbytes_in\x18\x03 \x01(\x03R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\x04 \x01(\x03R\bbytesOut\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\x94\b\n" +
	"\x0eProcessControl\x12^\n" +
	"\rStartListener\x12%.nitella.process.StartListenerRequest\x1a&.nitella.process.StartListenerResponse\x12[\n" +
	"\fStopListener\x12$.nitella.process.StopListenerRequest\x1a%.nitella.process.StopListenerResponse\x12X\n" +
	"\vHealthCheck\x12#.nitella.process.HealthCheckRequest\x1a$.nitella.process.HealthCheckResponse\x12U\n" +
	"\n" +
	"GetMetrics\x12\".nitella.process.GetMetricsRequest\x1a#.nitella.process.GetMetricsResponse\x12L\n" +
	"\aAddRule\x12\x1f.nitella.process.AddRuleRequest\x1a .nitella.process.AddRuleResponse\x12U\n" +
	"\n" +
	"RemoveRule\x12\".nitella.process.RemoveRuleRequest\x1a#.nitella.process.RemoveRuleResponse\x12R\n" +
	"\tListRules\x12!.nitella.process.ListRulesRequest\x1a\".nitella.process.ListRulesResponse\x12s\n" +
	"\x14GetActiveConnections\x12,.nitella.process.GetActiveConnectionsRequest\x1a-.nitella.process.GetActiveConnectionsResponse\x12d\n" +
	"\x0fCloseConnection\x12'.nitella.process.CloseConnectionRequest\x1a(.nitella.process.CloseConnectionResponse\x12p\n" +
	"\x13CloseAllConnections\x12+.nitella.process.CloseAllConnectionsRequest\x1a,.nitella.process.CloseAllConnectionsResponse\x12N\n" +
	"\fStreamEvents\x12$.nitella.process.StreamEventsRequest\x1a\x16.nitella.process.Event0\x01B,Z*github.com/ivere27/nitella/pkg/api/processb\x06proto3"

var (
	file_process_process_proto_rawDescOnce sync.Once
	file_process_process_proto_rawDescData []byte
)

func file_process_process_proto_rawDescGZIP() []byte {
	file_process_process_proto_rawDescOnce.Do(func() {
		file_process_process_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_process_process_proto_rawDesc), len(file_process_process_proto_rawDesc)))
	})
	return file_process_process_proto_rawDescData
}

var file_process_process_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_process_process_proto_goTypes = []any{
	(*StartListenerRequest)(nil),         // 0: nitella.process.StartListenerRequest
	(*StartListenerResponse)(nil),        // 1: nitella.process.StartListenerResponse
	(*StopListenerRequest)(nil),          // 2: nitella.process.StopListenerRequest
	(*StopListenerResponse)(nil),         // 3: nitella.process.StopListenerResponse
	(*HealthCheckRequest)(nil),           // 4: nitella.process.HealthCheckRequest
	(*HealthCheckResponse)(nil),          // 5: nitella.process.HealthCheckResponse
	(*GetMetricsRequest)(nil),            // 6: nitella.process.GetMetricsRequest
	(*GetMetricsResponse)(nil),           // 7: nitella.process.GetMetricsResponse
	(*AddRuleRequest)(nil),               // 8: nitella.process.AddRuleRequest
	(*AddRuleResponse)(nil),              // 9: nitella.process.AddRuleResponse
	(*RemoveRuleRequest)(nil),            // 10: nitella.process.RemoveRuleRequest
	(*RemoveRuleResponse)(nil),           // 11: nitella.process.RemoveRuleResponse
	(*ListRulesRequest)(nil),             // 12: nitella.process.ListRulesRequest
	(*ListRulesResponse)(nil),            // 13: nitella.process.ListRulesResponse
	(*GetActiveConnectionsRequest)(nil),  // 14: nitella.process.GetActiveConnectionsRequest
	(*GetActiveConnectionsResponse)(nil), // 15: nitella.process.GetActiveConnectionsResponse
	(*CloseConnectionRequest)(nil),       // 16: nitella.process.CloseConnectionRequest
	(*CloseConnectionResponse)(nil),      // 17: nitella.process.CloseConnectionResponse
	(*CloseAllConnectionsRequest)(nil),   // 18: nitella.process.CloseAllConnectionsRequest
	(*CloseAllConnectionsResponse)(nil),  // 19: nitella.process.CloseAllConnectionsResponse
	(*StreamEventsRequest)(nil),          // 20: nitella.process.StreamEventsRequest
	(*Event)(nil),                        // 21: nitella.process.Event
	(*LogEvent)(nil),                     // 22: nitella.process.LogEvent
	(*MetricsEvent)(nil),                 // 23: nitella.process.MetricsEvent
	(common.ActionType)(0),               // 24: nitella.ActionType
	(*proxy.MockConfig)(nil),             // 25: nitella.proxy.MockConfig
	(proxy.ClientAuthType)(0),            // 26: nitella.proxy.ClientAuthType
	(common.FallbackAction)(0),           // 27: nitella.FallbackAction
	(common.MockPreset)(0),               // 28: nitella.MockPreset
	(*proxy.ProxyStatus)(nil),            // 29: nitella.proxy.ProxyStatus
	(*proxy.Rule)(nil),                   // 30: nitella.proxy.Rule
	(*proxy.ActiveConnection)(nil),       // 31: nitella.proxy.ActiveConnection
	(*proxy.ConnectionEvent)(nil),        // 32: nitella.proxy.ConnectionEvent
	(*timestamp.Timestamp)(nil),          // 33: google.protobuf.Timestamp
}
var file_process_process_proto_depIdxs = []int32{
	24, // 0: nitella.process.StartListenerRequest.default_action:type_name -> nitella.ActionType
	25, // 1: nitella.process.StartListenerRequest.default_mock:type_name -> nitella.proxy.MockConfig
	26, // 2: nitella.process.StartListenerRequest.client_auth_type:type_name -> nitella.proxy.ClientAuthType
	27, // 3: nitella.process.StartListenerRequest.fallback_action:type_name -> nitella.FallbackAction
	28, // 4: nitella.process.StartListenerRequest.fallback_mock:type_name -> nitella.MockPreset
	29, // 5: nitella.process.GetMetricsResponse.status:type_name -> nitella.proxy.ProxyStatus
	30, // 6: nitella.process.AddRuleRequest.rule:type_name -> nitella.proxy.Rule
	30, // 7: nitella.process.ListRulesResponse.rules:type_name -> nitella.proxy.Rule
	31, // 8: nitella.process.GetActiveConnectionsResponse.connections:type_name -> nitella.proxy.ActiveConnection
	32, // 9: nitella.process.Event.connection:type_name -> nitella.proxy.ConnectionEvent
	22, // 10: nitella.process.Event.log:type_name -> nitella.process.LogEvent
	23, // 11: nitella.process.Event.metrics:type_name -> nitella.process.MetricsEvent
	33, // 12: nitella.process.LogEvent.timestamp:type_name -> google.protobuf.Timestamp
	33, // 13: nitella.process.MetricsEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 14: nitella.process.ProcessControl.StartListener:input_type -> nitella.process.StartListenerRequest
	2,  // 15: nitella.process.ProcessControl.StopListener:input_type -> nitella.process.StopListenerRequest
	4,  // 16: nitella.process.ProcessControl.HealthCheck:input_type -> nitella.process.HealthCheckRequest
	6,  // 17: nitella.process.ProcessControl.GetMetrics:input_type -> nitella.process.GetMetricsRequest
	8,  // 18: nitella.process.ProcessControl.AddRule:input_type -> nitella.process.AddRuleRequest
	10, // 19: nitella.process.ProcessControl.RemoveRule:input_type -> nitella.process.RemoveRuleRequest
	12, // 20: nitella.process.ProcessControl.ListRules:input_type -> nitella.process.ListRulesRequest
	14, // 21: nitella.process.ProcessControl.GetActiveConnections:input_type -> nitella.process.GetActiveConnectionsRequest
	16, // 22: nitella.process.ProcessControl.CloseConnection:input_type -> nitella.process.CloseConnectionRequest
	18, // 23: nitella.process.ProcessControl.CloseAllConnections:input_type -> nitella.process.CloseAllConnectionsRequest
	20, // 24: nitella.process.ProcessControl.StreamEvents:input_type -> nitella.process.StreamEventsRequest
	1,  // 25: nitella.process.ProcessControl.StartListener:output_type -> nitella.process.StartListenerResponse
	3,  // 26: nitella.process.ProcessControl.StopListener:output_type -> nitella.process.StopListenerResponse
	5,  // 27: nitella.process.ProcessControl.HealthCheck:output_type -> nitella.process.HealthCheckResponse
	7,  // 28: nitella.process.ProcessControl.GetMetrics:output_type -> nitella.process.GetMetricsResponse
	9,  // 29: nitella.process.ProcessControl.AddRule:output_type -> nitella.process.AddRuleResponse
	11, // 30: nitella.process.ProcessControl.RemoveRule:output_type -> nitella.process.RemoveRuleResponse
	13, // 31: nitella.process.ProcessControl.ListRules:output_type -> nitella.process.ListRulesResponse
	15, // 32: nitella.process.ProcessControl.GetActiveConnections:output_type -> nitella.process.GetActiveConnectionsResponse
	17, // 33: nitella.process.ProcessControl.CloseConnection:output_type -> nitella.process.CloseConnectionResponse
	19, // 34: nitella.process.ProcessControl.CloseAllConnections:output_type -> nitella.process.CloseAllConnectionsResponse
	21, // 35: nitella.process.ProcessControl.StreamEvents:output_type -> nitella.process.Event
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_process_process_proto_init() }
func file_process_process_proto_init() {
	if File_process_process_proto != nil {
		return
	}
	file_process_process_proto_msgTypes[21].OneofWrappers = []any{
		(*Event_Connection)(nil),
		(*Event_Log)(nil),
		(*Event_Metrics)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_process_process_proto_rawDesc), len(file_process_process_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_process_process_proto_goTypes,
		DependencyIndexes: file_process_process_proto_depIdxs,
		MessageInfos:      file_process_process_proto_msgTypes,
	}.Build()
	File_process_process_proto = out.File
	file_process_process_proto_goTypes = nil
	file_process_process_proto_depIdxs = nil
}
