// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: process/process.proto

package process

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcessControl_StartListener_FullMethodName        = "/nitella.process.ProcessControl/StartListener"
	ProcessControl_StopListener_FullMethodName         = "/nitella.process.ProcessControl/StopListener"
	ProcessControl_HealthCheck_FullMethodName          = "/nitella.process.ProcessControl/HealthCheck"
	ProcessControl_GetMetrics_FullMethodName           = "/nitella.process.ProcessControl/GetMetrics"
	ProcessControl_AddRule_FullMethodName              = "/nitella.process.ProcessControl/AddRule"
	ProcessControl_RemoveRule_FullMethodName           = "/nitella.process.ProcessControl/RemoveRule"
	ProcessControl_ListRules_FullMethodName            = "/nitella.process.ProcessControl/ListRules"
	ProcessControl_GetActiveConnections_FullMethodName = "/nitella.process.ProcessControl/GetActiveConnections"
	ProcessControl_CloseConnection_FullMethodName      = "/nitella.process.ProcessControl/CloseConnection"
	ProcessControl_CloseAllConnections_FullMethodName  = "/nitella.process.ProcessControl/CloseAllConnections"
	ProcessControl_StreamEvents_FullMethodName         = "/nitella.process.ProcessControl/StreamEvents"
)

// ProcessControlClient is the client API for ProcessControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProcessControl is the service for Parent <-> Child process communication
// Used for child process isolation mode where each listener runs in a separate process
type ProcessControlClient interface {
	// Lifecycle
	StartListener(ctx context.Context, in *StartListenerRequest, opts ...grpc.CallOption) (*StartListenerResponse, error)
	StopListener(ctx context.Context, in *StopListenerRequest, opts ...grpc.CallOption) (*StopListenerResponse, error)
	// Health and Metrics
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	// Rule Management
	AddRule(ctx context.Context, in *AddRuleRequest, opts ...grpc.CallOption) (*AddRuleResponse, error)
	RemoveRule(ctx context.Context, in *RemoveRuleRequest, opts ...grpc.CallOption) (*RemoveRuleResponse, error)
	ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	// Connection Management
	GetActiveConnections(ctx context.Context, in *GetActiveConnectionsRequest, opts ...grpc.CallOption) (*GetActiveConnectionsResponse, error)
	CloseConnection(ctx context.Context, in *CloseConnectionRequest, opts ...grpc.CallOption) (*CloseConnectionResponse, error)
	CloseAllConnections(ctx context.Context, in *CloseAllConnectionsRequest, opts ...grpc.CallOption) (*CloseAllConnectionsResponse, error)
	// Streaming events from Child -> Parent (connections, logs, metrics)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type processControlClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessControlClient(cc grpc.ClientConnInterface) ProcessControlClient {
	return &processControlClient{cc}
}

func (c *processControlClient) StartListener(ctx context.Context, in *StartListenerRequest, opts ...grpc.CallOption) (*StartListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartListenerResponse)
	err := c.cc.Invoke(ctx, ProcessControl_StartListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processControlClient) StopListener(ctx context.Context, in *StopListenerRequest, opts ...grpc.CallOption) (*StopListenerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopListenerResponse)
	err := c.cc.Invoke(ctx, ProcessControl_StopListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processControlClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ProcessControl_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processControlClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, ProcessControl_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processControlClient) AddRule(ctx context.Context, in *AddRuleRequest, opts ...grpc.CallOption) (*AddRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRuleResponse)
	err := c.cc.Invoke(ctx, ProcessControl_AddRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processControlClient) RemoveRule(ctx context.Context, in *RemoveRuleRequest, opts ...grpc.CallOption) (*RemoveRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRuleResponse)
	err := c.cc.Invoke(ctx, ProcessControl_RemoveRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processControlClient) ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, ProcessControl_ListRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processControlClient) GetActiveConnections(ctx context.Context, in *GetActiveConnectionsRequest, opts ...grpc.CallOption) (*GetActiveConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveConnectionsResponse)
	err := c.cc.Invoke(ctx, ProcessControl_GetActiveConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processControlClient) CloseConnection(ctx context.Context, in *CloseConnectionRequest, opts ...grpc.CallOption) (*CloseConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseConnectionResponse)
	err := c.cc.Invoke(ctx, ProcessControl_CloseConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processControlClient) CloseAllConnections(ctx context.Context, in *CloseAllConnectionsRequest, opts ...grpc.CallOption) (*CloseAllConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseAllConnectionsResponse)
	err := c.cc.Invoke(ctx, ProcessControl_CloseAllConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processControlClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProcessControl_ServiceDesc.Streams[0], ProcessControl_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessControl_StreamEventsClient = grpc.ServerStreamingClient[Event]

// ProcessControlServer is the server API for ProcessControl service.
// All implementations must embed UnimplementedProcessControlServer
// for forward compatibility.
//
// ProcessControl is the service for Parent <-> Child process communication
// Used for child process isolation mode where each listener runs in a separate process
type ProcessControlServer interface {
	// Lifecycle
	StartListener(context.Context, *StartListenerRequest) (*StartListenerResponse, error)
	StopListener(context.Context, *StopListenerRequest) (*StopListenerResponse, error)
	// Health and Metrics
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	// Rule Management
	AddRule(context.Context, *AddRuleRequest) (*AddRuleResponse, error)
	RemoveRule(context.Context, *RemoveRuleRequest) (*RemoveRuleResponse, error)
	ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	// Connection Management
	GetActiveConnections(context.Context, *GetActiveConnectionsRequest) (*GetActiveConnectionsResponse, error)
	CloseConnection(context.Context, *CloseConnectionRequest) (*CloseConnectionResponse, error)
	CloseAllConnections(context.Context, *CloseAllConnectionsRequest) (*CloseAllConnectionsResponse, error)
	// Streaming events from Child -> Parent (connections, logs, metrics)
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedProcessControlServer()
}

// UnimplementedProcessControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessControlServer struct{}

func (UnimplementedProcessControlServer) StartListener(context.Context, *StartListenerRequest) (*StartListenerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartListener not implemented")
}
func (UnimplementedProcessControlServer) StopListener(context.Context, *StopListenerRequest) (*StopListenerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopListener not implemented")
}
func (UnimplementedProcessControlServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedProcessControlServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedProcessControlServer) AddRule(context.Context, *AddRuleRequest) (*AddRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRule not implemented")
}
func (UnimplementedProcessControlServer) RemoveRule(context.Context, *RemoveRuleRequest) (*RemoveRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRule not implemented")
}
func (UnimplementedProcessControlServer) ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRules not implemented")
}
func (UnimplementedProcessControlServer) GetActiveConnections(context.Context, *GetActiveConnectionsRequest) (*GetActiveConnectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveConnections not implemented")
}
func (UnimplementedProcessControlServer) CloseConnection(context.Context, *CloseConnectionRequest) (*CloseConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseConnection not implemented")
}
func (UnimplementedProcessControlServer) CloseAllConnections(context.Context, *CloseAllConnectionsRequest) (*CloseAllConnectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseAllConnections not implemented")
}
func (UnimplementedProcessControlServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedProcessControlServer) mustEmbedUnimplementedProcessControlServer() {}
func (UnimplementedProcessControlServer) testEmbeddedByValue()                        {}

// UnsafeProcessControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessControlServer will
// result in compilation errors.
type UnsafeProcessControlServer interface {
	mustEmbedUnimplementedProcessControlServer()
}

func RegisterProcessControlServer(s grpc.ServiceRegistrar, srv ProcessControlServer) {
	// If the following call panics, it indicates UnimplementedProcessControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessControl_ServiceDesc, srv)
}

func _ProcessControl_StartListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessControlServer).StartListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessControl_StartListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessControlServer).StartListener(ctx, req.(*StartListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessControl_StopListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessControlServer).StopListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessControl_StopListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessControlServer).StopListener(ctx, req.(*StopListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessControl_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessControlServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessControl_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessControlServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessControl_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessControlServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessControl_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessControlServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessControl_AddRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessControlServer).AddRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessControl_AddRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessControlServer).AddRule(ctx, req.(*AddRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessControl_RemoveRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessControlServer).RemoveRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessControl_RemoveRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessControlServer).RemoveRule(ctx, req.(*RemoveRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessControl_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessControlServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessControl_ListRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessControlServer).ListRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessControl_GetActiveConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessControlServer).GetActiveConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessControl_GetActiveConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessControlServer).GetActiveConnections(ctx, req.(*GetActiveConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessControl_CloseConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessControlServer).CloseConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessControl_CloseConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessControlServer).CloseConnection(ctx, req.(*CloseConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessControl_CloseAllConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseAllConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessControlServer).CloseAllConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessControl_CloseAllConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessControlServer).CloseAllConnections(ctx, req.(*CloseAllConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProcessControl_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessControlServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProcessControl_StreamEventsServer = grpc.ServerStreamingServer[Event]

// ProcessControl_ServiceDesc is the grpc.ServiceDesc for ProcessControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nitella.process.ProcessControl",
	HandlerType: (*ProcessControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartListener",
			Handler:    _ProcessControl_StartListener_Handler,
		},
		{
			MethodName: "StopListener",
			Handler:    _ProcessControl_StopListener_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ProcessControl_HealthCheck_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _ProcessControl_GetMetrics_Handler,
		},
		{
			MethodName: "AddRule",
			Handler:    _ProcessControl_AddRule_Handler,
		},
		{
			MethodName: "RemoveRule",
			Handler:    _ProcessControl_RemoveRule_Handler,
		},
		{
			MethodName: "ListRules",
			Handler:    _ProcessControl_ListRules_Handler,
		},
		{
			MethodName: "GetActiveConnections",
			Handler:    _ProcessControl_GetActiveConnections_Handler,
		},
		{
			MethodName: "CloseConnection",
			Handler:    _ProcessControl_CloseConnection_Handler,
		},
		{
			MethodName: "CloseAllConnections",
			Handler:    _ProcessControl_CloseAllConnections_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _ProcessControl_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "process/process.proto",
}
