// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: hub/hub_node.proto

package hub

import (
	_ "github.com/golang/protobuf/ptypes/timestamp"
	common "github.com/ivere27/nitella/pkg/api/common"
	proxy "github.com/ivere27/nitella/pkg/api/proxy"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeCommand for E2E Encrypted Payload (Inner)
type NodeCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*NodeCommand_AddRule
	//	*NodeCommand_RemoveRule
	//	*NodeCommand_FetchRules
	//	*NodeCommand_GetConnections
	//	*NodeCommand_CloseConnection
	//	*NodeCommand_CloseAll
	//	*NodeCommand_GetIpStats
	//	*NodeCommand_GetGeoStats
	//	*NodeCommand_GetStatsSummary
	//	*NodeCommand_ResolveApproval
	//	*NodeCommand_ListProxies
	//	*NodeCommand_CreateProxy
	//	*NodeCommand_UpdateProxy
	//	*NodeCommand_DeleteProxy
	//	*NodeCommand_EnableProxy
	//	*NodeCommand_DisableProxy
	Command       isNodeCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCommand) Reset() {
	*x = NodeCommand{}
	mi := &file_hub_hub_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCommand) ProtoMessage() {}

func (x *NodeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCommand.ProtoReflect.Descriptor instead.
func (*NodeCommand) Descriptor() ([]byte, []int) {
	return file_hub_hub_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeCommand) GetCommand() isNodeCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *NodeCommand) GetAddRule() *proxy.AddRuleRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_AddRule); ok {
			return x.AddRule
		}
	}
	return nil
}

func (x *NodeCommand) GetRemoveRule() *proxy.RemoveRuleRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_RemoveRule); ok {
			return x.RemoveRule
		}
	}
	return nil
}

func (x *NodeCommand) GetFetchRules() *proxy.ListRulesRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_FetchRules); ok {
			return x.FetchRules
		}
	}
	return nil
}

func (x *NodeCommand) GetGetConnections() *proxy.GetActiveConnectionsRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_GetConnections); ok {
			return x.GetConnections
		}
	}
	return nil
}

func (x *NodeCommand) GetCloseConnection() *proxy.CloseConnectionRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_CloseConnection); ok {
			return x.CloseConnection
		}
	}
	return nil
}

func (x *NodeCommand) GetCloseAll() *proxy.CloseAllConnectionsRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_CloseAll); ok {
			return x.CloseAll
		}
	}
	return nil
}

func (x *NodeCommand) GetGetIpStats() *proxy.GetIPStatsRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_GetIpStats); ok {
			return x.GetIpStats
		}
	}
	return nil
}

func (x *NodeCommand) GetGetGeoStats() *proxy.GetGeoStatsRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_GetGeoStats); ok {
			return x.GetGeoStats
		}
	}
	return nil
}

func (x *NodeCommand) GetGetStatsSummary() *proxy.GetStatsSummaryRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_GetStatsSummary); ok {
			return x.GetStatsSummary
		}
	}
	return nil
}

func (x *NodeCommand) GetResolveApproval() *proxy.ResolveApprovalRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_ResolveApproval); ok {
			return x.ResolveApproval
		}
	}
	return nil
}

func (x *NodeCommand) GetListProxies() *proxy.ListProxiesRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_ListProxies); ok {
			return x.ListProxies
		}
	}
	return nil
}

func (x *NodeCommand) GetCreateProxy() *proxy.CreateProxyRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_CreateProxy); ok {
			return x.CreateProxy
		}
	}
	return nil
}

func (x *NodeCommand) GetUpdateProxy() *proxy.UpdateProxyRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_UpdateProxy); ok {
			return x.UpdateProxy
		}
	}
	return nil
}

func (x *NodeCommand) GetDeleteProxy() *proxy.DeleteProxyRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_DeleteProxy); ok {
			return x.DeleteProxy
		}
	}
	return nil
}

func (x *NodeCommand) GetEnableProxy() *proxy.EnableProxyRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_EnableProxy); ok {
			return x.EnableProxy
		}
	}
	return nil
}

func (x *NodeCommand) GetDisableProxy() *proxy.DisableProxyRequest {
	if x != nil {
		if x, ok := x.Command.(*NodeCommand_DisableProxy); ok {
			return x.DisableProxy
		}
	}
	return nil
}

type isNodeCommand_Command interface {
	isNodeCommand_Command()
}

type NodeCommand_AddRule struct {
	AddRule *proxy.AddRuleRequest `protobuf:"bytes,1,opt,name=add_rule,json=addRule,proto3,oneof"`
}

type NodeCommand_RemoveRule struct {
	RemoveRule *proxy.RemoveRuleRequest `protobuf:"bytes,2,opt,name=remove_rule,json=removeRule,proto3,oneof"`
}

type NodeCommand_FetchRules struct {
	FetchRules *proxy.ListRulesRequest `protobuf:"bytes,3,opt,name=fetch_rules,json=fetchRules,proto3,oneof"`
}

type NodeCommand_GetConnections struct {
	// Connection Management
	GetConnections *proxy.GetActiveConnectionsRequest `protobuf:"bytes,4,opt,name=get_connections,json=getConnections,proto3,oneof"`
}

type NodeCommand_CloseConnection struct {
	CloseConnection *proxy.CloseConnectionRequest `protobuf:"bytes,5,opt,name=close_connection,json=closeConnection,proto3,oneof"`
}

type NodeCommand_CloseAll struct {
	CloseAll *proxy.CloseAllConnectionsRequest `protobuf:"bytes,6,opt,name=close_all,json=closeAll,proto3,oneof"`
}

type NodeCommand_GetIpStats struct {
	// Statistics Access (For UI)
	GetIpStats *proxy.GetIPStatsRequest `protobuf:"bytes,7,opt,name=get_ip_stats,json=getIpStats,proto3,oneof"`
}

type NodeCommand_GetGeoStats struct {
	GetGeoStats *proxy.GetGeoStatsRequest `protobuf:"bytes,8,opt,name=get_geo_stats,json=getGeoStats,proto3,oneof"`
}

type NodeCommand_GetStatsSummary struct {
	GetStatsSummary *proxy.GetStatsSummaryRequest `protobuf:"bytes,9,opt,name=get_stats_summary,json=getStatsSummary,proto3,oneof"`
}

type NodeCommand_ResolveApproval struct {
	ResolveApproval *proxy.ResolveApprovalRequest `protobuf:"bytes,10,opt,name=resolve_approval,json=resolveApproval,proto3,oneof"`
}

type NodeCommand_ListProxies struct {
	// Proxy Management
	ListProxies *proxy.ListProxiesRequest `protobuf:"bytes,11,opt,name=list_proxies,json=listProxies,proto3,oneof"`
}

type NodeCommand_CreateProxy struct {
	CreateProxy *proxy.CreateProxyRequest `protobuf:"bytes,12,opt,name=create_proxy,json=createProxy,proto3,oneof"`
}

type NodeCommand_UpdateProxy struct {
	UpdateProxy *proxy.UpdateProxyRequest `protobuf:"bytes,13,opt,name=update_proxy,json=updateProxy,proto3,oneof"`
}

type NodeCommand_DeleteProxy struct {
	DeleteProxy *proxy.DeleteProxyRequest `protobuf:"bytes,14,opt,name=delete_proxy,json=deleteProxy,proto3,oneof"`
}

type NodeCommand_EnableProxy struct {
	EnableProxy *proxy.EnableProxyRequest `protobuf:"bytes,15,opt,name=enable_proxy,json=enableProxy,proto3,oneof"`
}

type NodeCommand_DisableProxy struct {
	DisableProxy *proxy.DisableProxyRequest `protobuf:"bytes,16,opt,name=disable_proxy,json=disableProxy,proto3,oneof"`
}

func (*NodeCommand_AddRule) isNodeCommand_Command() {}

func (*NodeCommand_RemoveRule) isNodeCommand_Command() {}

func (*NodeCommand_FetchRules) isNodeCommand_Command() {}

func (*NodeCommand_GetConnections) isNodeCommand_Command() {}

func (*NodeCommand_CloseConnection) isNodeCommand_Command() {}

func (*NodeCommand_CloseAll) isNodeCommand_Command() {}

func (*NodeCommand_GetIpStats) isNodeCommand_Command() {}

func (*NodeCommand_GetGeoStats) isNodeCommand_Command() {}

func (*NodeCommand_GetStatsSummary) isNodeCommand_Command() {}

func (*NodeCommand_ResolveApproval) isNodeCommand_Command() {}

func (*NodeCommand_ListProxies) isNodeCommand_Command() {}

func (*NodeCommand_CreateProxy) isNodeCommand_Command() {}

func (*NodeCommand_UpdateProxy) isNodeCommand_Command() {}

func (*NodeCommand_DeleteProxy) isNodeCommand_Command() {}

func (*NodeCommand_EnableProxy) isNodeCommand_Command() {}

func (*NodeCommand_DisableProxy) isNodeCommand_Command() {}

// Registration
type NodeRegisterRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RegistrationCode  string                 `protobuf:"bytes,1,opt,name=registration_code,json=registrationCode,proto3" json:"registration_code,omitempty"`    // Optional (if checking status)
	CsrPem            string                 `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`                                  // Required if code is empty (New)
	EncryptedMetadata []byte                 `protobuf:"bytes,3,opt,name=encrypted_metadata,json=encryptedMetadata,proto3" json:"encrypted_metadata,omitempty"` // E2E Encrypted Name
	ListenPorts       []int32                `protobuf:"varint,4,rep,packed,name=listen_ports,json=listenPorts,proto3" json:"listen_ports,omitempty"`
	Version           string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"` // Node version
	InviteCode        string                 `protobuf:"bytes,6,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	PairingCode       string                 `protobuf:"bytes,7,opt,name=pairing_code,json=pairingCode,proto3" json:"pairing_code,omitempty"` // For Secure Pairing Mode
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeRegisterRequest) Reset() {
	*x = NodeRegisterRequest{}
	mi := &file_hub_hub_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegisterRequest) ProtoMessage() {}

func (x *NodeRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegisterRequest.ProtoReflect.Descriptor instead.
func (*NodeRegisterRequest) Descriptor() ([]byte, []int) {
	return file_hub_hub_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeRegisterRequest) GetRegistrationCode() string {
	if x != nil {
		return x.RegistrationCode
	}
	return ""
}

func (x *NodeRegisterRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *NodeRegisterRequest) GetEncryptedMetadata() []byte {
	if x != nil {
		return x.EncryptedMetadata
	}
	return nil
}

func (x *NodeRegisterRequest) GetListenPorts() []int32 {
	if x != nil {
		return x.ListenPorts
	}
	return nil
}

func (x *NodeRegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeRegisterRequest) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *NodeRegisterRequest) GetPairingCode() string {
	if x != nil {
		return x.PairingCode
	}
	return ""
}

type NodeRegisterResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RegistrationCode string                 `protobuf:"bytes,1,opt,name=registration_code,json=registrationCode,proto3" json:"registration_code,omitempty"`
	Status           RegistrationStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=nitella.hub.RegistrationStatus" json:"status,omitempty"` // PENDING, APPROVED, REJECTED
	CertPem          string                 `protobuf:"bytes,3,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`                     // If approved
	CaPem            string                 `protobuf:"bytes,4,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`                           // If approved
	WatchSecret      string                 `protobuf:"bytes,5,opt,name=watch_secret,json=watchSecret,proto3" json:"watch_secret,omitempty"`         // Secret required for WatchRegistration (only registrant knows)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeRegisterResponse) Reset() {
	*x = NodeRegisterResponse{}
	mi := &file_hub_hub_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegisterResponse) ProtoMessage() {}

func (x *NodeRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegisterResponse.ProtoReflect.Descriptor instead.
func (*NodeRegisterResponse) Descriptor() ([]byte, []int) {
	return file_hub_hub_node_proto_rawDescGZIP(), []int{2}
}

func (x *NodeRegisterResponse) GetRegistrationCode() string {
	if x != nil {
		return x.RegistrationCode
	}
	return ""
}

func (x *NodeRegisterResponse) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED
}

func (x *NodeRegisterResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *NodeRegisterResponse) GetCaPem() string {
	if x != nil {
		return x.CaPem
	}
	return ""
}

func (x *NodeRegisterResponse) GetWatchSecret() string {
	if x != nil {
		return x.WatchSecret
	}
	return ""
}

type WatchRegistrationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RegistrationCode string                 `protobuf:"bytes,1,opt,name=registration_code,json=registrationCode,proto3" json:"registration_code,omitempty"`
	WatchSecret      string                 `protobuf:"bytes,2,opt,name=watch_secret,json=watchSecret,proto3" json:"watch_secret,omitempty"` // Must match the secret returned during Register()
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WatchRegistrationRequest) Reset() {
	*x = WatchRegistrationRequest{}
	mi := &file_hub_hub_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRegistrationRequest) ProtoMessage() {}

func (x *WatchRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRegistrationRequest.ProtoReflect.Descriptor instead.
func (*WatchRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_hub_hub_node_proto_rawDescGZIP(), []int{3}
}

func (x *WatchRegistrationRequest) GetRegistrationCode() string {
	if x != nil {
		return x.RegistrationCode
	}
	return ""
}

func (x *WatchRegistrationRequest) GetWatchSecret() string {
	if x != nil {
		return x.WatchSecret
	}
	return ""
}

type WatchRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        RegistrationStatus     `protobuf:"varint,1,opt,name=status,proto3,enum=nitella.hub.RegistrationStatus" json:"status,omitempty"` // PENDING, APPROVED, REJECTED
	CertPem       string                 `protobuf:"bytes,2,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	CaPem         string                 `protobuf:"bytes,3,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRegistrationResponse) Reset() {
	*x = WatchRegistrationResponse{}
	mi := &file_hub_hub_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRegistrationResponse) ProtoMessage() {}

func (x *WatchRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRegistrationResponse.ProtoReflect.Descriptor instead.
func (*WatchRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_hub_hub_node_proto_rawDescGZIP(), []int{4}
}

func (x *WatchRegistrationResponse) GetStatus() RegistrationStatus {
	if x != nil {
		return x.Status
	}
	return RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED
}

func (x *WatchRegistrationResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *WatchRegistrationResponse) GetCaPem() string {
	if x != nil {
		return x.CaPem
	}
	return ""
}

type CheckCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"` // SHA256 of SPKI
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCertificateRequest) Reset() {
	*x = CheckCertificateRequest{}
	mi := &file_hub_hub_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCertificateRequest) ProtoMessage() {}

func (x *CheckCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCertificateRequest.ProtoReflect.Descriptor instead.
func (*CheckCertificateRequest) Descriptor() ([]byte, []int) {
	return file_hub_hub_node_proto_rawDescGZIP(), []int{5}
}

func (x *CheckCertificateRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type CheckCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	CertPem       string                 `protobuf:"bytes,2,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	CaPem         string                 `protobuf:"bytes,3,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCertificateResponse) Reset() {
	*x = CheckCertificateResponse{}
	mi := &file_hub_hub_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCertificateResponse) ProtoMessage() {}

func (x *CheckCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCertificateResponse.ProtoReflect.Descriptor instead.
func (*CheckCertificateResponse) Descriptor() ([]byte, []int) {
	return file_hub_hub_node_proto_rawDescGZIP(), []int{6}
}

func (x *CheckCertificateResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *CheckCertificateResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *CheckCertificateResponse) GetCaPem() string {
	if x != nil {
		return x.CaPem
	}
	return ""
}

// Heartbeat
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        NodeStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=nitella.hub.NodeStatus" json:"status,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_hub_hub_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_hub_hub_node_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *HeartbeatRequest) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RulesChanged  bool                   `protobuf:"varint,1,opt,name=rules_changed,json=rulesChanged,proto3" json:"rules_changed,omitempty"`    // Hint to sync rules
	ConfigChanged bool                   `protobuf:"varint,2,opt,name=config_changed,json=configChanged,proto3" json:"config_changed,omitempty"` // Hint to reload config
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_hub_hub_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_hub_hub_node_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatResponse) GetRulesChanged() bool {
	if x != nil {
		return x.RulesChanged
	}
	return false
}

func (x *HeartbeatResponse) GetConfigChanged() bool {
	if x != nil {
		return x.ConfigChanged
	}
	return false
}

// Commands
type ReceiveCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveCommandsRequest) Reset() {
	*x = ReceiveCommandsRequest{}
	mi := &file_hub_hub_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveCommandsRequest) ProtoMessage() {}

func (x *ReceiveCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveCommandsRequest.ProtoReflect.Descriptor instead.
func (*ReceiveCommandsRequest) Descriptor() ([]byte, []int) {
	return file_hub_hub_node_proto_rawDescGZIP(), []int{9}
}

func (x *ReceiveCommandsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// Revocations
type StreamRevocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRevocationsRequest) Reset() {
	*x = StreamRevocationsRequest{}
	mi := &file_hub_hub_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRevocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRevocationsRequest) ProtoMessage() {}

func (x *StreamRevocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRevocationsRequest.ProtoReflect.Descriptor instead.
func (*StreamRevocationsRequest) Descriptor() ([]byte, []int) {
	return file_hub_hub_node_proto_rawDescGZIP(), []int{10}
}

func (x *StreamRevocationsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_hub_hub_node_proto protoreflect.FileDescriptor

const file_hub_hub_node_proto_rawDesc = "" +
	"\n" +
	"\x12hub/hub_node.proto\x12\vnitella.hub\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14hub/hub_common.proto\x1a\x11proxy/proxy.proto\x1a\x13common/common.proto\"\xbd\t\n" +
	"\vNodeCommand\x12:\n" +
	"\badd_rule\x18\x01 \x01(\v2\x1d.nitella.proxy.AddRuleRequestH\x00R\aaddRule\x12C\n" +
	"\vremove_rule\x18\x02 \x01(\v2 .nitella.proxy.RemoveRuleRequestH\x00R\n" +
	"removeRule\x12B\n" +
	"\vfetch_rules\x18\x03 \x01(\v2\x1f.nitella.proxy.ListRulesRequestH\x00R\n" +
	"fetchRules\x12U\n" +
	"\x0fget_connections\x18\x04 \x01(\v2*.nitella.proxy.GetActiveConnectionsRequestH\x00R\x0egetConnections\x12R\n" +
	"\x10close_connection\x18\x05 \x01(\v2%.nitella.proxy.CloseConnectionRequestH\x00R\x0fcloseConnection\x12H\n" +
	"\tclose_all\x18\x06 \x01(\v2).nitella.proxy.CloseAllConnectionsRequestH\x00R\bcloseAll\x12D\n" +
	"\fget_ip_stats\x18\a \x01(\v2 .nitella.proxy.GetIPStatsRequestH\x00R\n" +
	"getIpStats\x12G\n" +
	"\rget_geo_stats\x18\b \x01(\v2!.nitella.proxy.GetGeoStatsRequestH\x00R\vgetGeoStats\x12S\n" +
	"\x11get_stats_summary\x18\t \x01(\v2%.nitella.proxy.GetStatsSummaryRequestH\x00R\x0fgetStatsSummary\x12R\n" +
	"\x10resolve_approval\x18\n" +
	" \x01(\v2%.nitella.proxy.ResolveApprovalRequestH\x00R\x0fresolveApproval\x12F\n" +
	"\flist_proxies\x18\v \x01(\v2!.nitella.proxy.ListProxiesRequestH\x00R\vlistProxies\x12F\n" +
	"\fcreate_proxy\x18\f \x01(\v2!.nitella.proxy.CreateProxyRequestH\x00R\vcreateProxy\x12F\n" +
	"\fupdate_proxy\x18\r \x01(\v2!.nitella.proxy.UpdateProxyRequestH\x00R\vupdateProxy\x12F\n" +
	"\fdelete_proxy\x18\x0e \x01(\v2!.nitella.proxy.DeleteProxyRequestH\x00R\vdeleteProxy\x12F\n" +
	"\fenable_proxy\x18\x0f \x01(\v2!.nitella.proxy.EnableProxyRequestH\x00R\venableProxy\x12I\n" +
	"\rdisable_proxy\x18\x10 \x01(\v2\".nitella.proxy.DisableProxyRequestH\x00R\fdisableProxyB\t\n" +
	"\acommand\"\x8b\x02\n" +
	"\x13NodeRegisterRequest\x12+\n" +
	"\x11registration_code\x18\x01 \x01(\tR\x10registrationCode\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\tR\x06csrPem\x12-\n" +
	"\x12encrypted_metadata\x18\x03 \x01(\fR\x11encryptedMetadata\x12!\n" +
	"\flisten_ports\x18\x04 \x03(\x05R\vlistenPorts\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1f\n" +
	"\vinvite_code\x18\x06 \x01(\tR\n" +
	"inviteCode\x12!\n" +
	"\fpairing_code\x18\a \x01(\tR\vpairingCode\"\xd1\x01\n" +
	"\x14NodeRegisterResponse\x12+\n" +
	"\x11registration_code\x18\x01 \x01(\tR\x10registrationCode\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.nitella.hub.RegistrationStatusR\x06status\x12\x19\n" +
	"\bcert_pem\x18\x03 \x01(\tR\acertPem\x12\x15\n" +
	"\x06ca_pem\x18\x04 \x01(\tR\x05caPem\x12!\n" +
	"\fwatch_secret\x18\x05 \x01(\tR\vwatchSecret\"j\n" +
	"\x18WatchRegistrationRequest\x12+\n" +
	"\x11registration_code\x18\x01 \x01(\tR\x10registrationCode\x12!\n" +
	"\fwatch_secret\x18\x02 \x01(\tR\vwatchSecret\"\x86\x01\n" +
	"\x19WatchRegistrationResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.nitella.hub.RegistrationStatusR\x06status\x12\x19\n" +
	"\bcert_pem\x18\x02 \x01(\tR\acertPem\x12\x15\n" +
	"\x06ca_pem\x18\x03 \x01(\tR\x05caPem\";\n" +
	"\x17CheckCertificateRequest\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\"b\n" +
	"\x18CheckCertificateResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x19\n" +
	"\bcert_pem\x18\x02 \x01(\tR\acertPem\x12\x15\n" +
	"\x06ca_pem\x18\x03 \x01(\tR\x05caPem\"\x83\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.nitella.hub.NodeStatusR\x06status\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"_\n" +
	"\x11HeartbeatResponse\x12#\n" +
	"\rrules_changed\x18\x01 \x01(\bR\frulesChanged\x12%\n" +
	"\x0econfig_changed\x18\x02 \x01(\bR\rconfigChanged\"1\n" +
	"\x16ReceiveCommandsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"3\n" +
	"\x18StreamRevocationsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId2\xe9\x06\n" +
	"\vNodeService\x12O\n" +
	"\bRegister\x12 .nitella.hub.NodeRegisterRequest\x1a!.nitella.hub.NodeRegisterResponse\x12d\n" +
	"\x11WatchRegistration\x12%.nitella.hub.WatchRegistrationRequest\x1a&.nitella.hub.WatchRegistrationResponse0\x01\x12_\n" +
	"\x10CheckCertificate\x12$.nitella.hub.CheckCertificateRequest\x1a%.nitella.hub.CheckCertificateResponse\x12J\n" +
	"\tHeartbeat\x12\x1d.nitella.hub.HeartbeatRequest\x1a\x1e.nitella.hub.HeartbeatResponse\x12N\n" +
	"\x0fReceiveCommands\x12#.nitella.hub.ReceiveCommandsRequest\x1a\x14.nitella.hub.Command0\x01\x12D\n" +
	"\x10RespondToCommand\x12\x1c.nitella.hub.CommandResponse\x1a\x12.nitella.hub.Empty\x12B\n" +
	"\vPushMetrics\x12\x1d.nitella.hub.EncryptedMetrics\x1a\x12.nitella.hub.Empty(\x01\x12@\n" +
	"\bPushLogs\x12\x1e.nitella.hub.EncryptedLogEntry\x1a\x12.nitella.hub.Empty(\x01\x12/\n" +
	"\tPushAlert\x12\x0e.nitella.Alert\x1a\x12.nitella.hub.Empty\x12Z\n" +
	"\x11StreamRevocations\x12%.nitella.hub.StreamRevocationsRequest\x1a\x1c.nitella.hub.RevocationEvent0\x01\x12M\n" +
	"\x0fStreamSignaling\x12\x1a.nitella.hub.SignalMessage\x1a\x1a.nitella.hub.SignalMessage(\x010\x01B(Z&github.com/ivere27/nitella/pkg/api/hubb\x06proto3"

var (
	file_hub_hub_node_proto_rawDescOnce sync.Once
	file_hub_hub_node_proto_rawDescData []byte
)

func file_hub_hub_node_proto_rawDescGZIP() []byte {
	file_hub_hub_node_proto_rawDescOnce.Do(func() {
		file_hub_hub_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_hub_node_proto_rawDesc), len(file_hub_hub_node_proto_rawDesc)))
	})
	return file_hub_hub_node_proto_rawDescData
}

var file_hub_hub_node_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_hub_hub_node_proto_goTypes = []any{
	(*NodeCommand)(nil),                       // 0: nitella.hub.NodeCommand
	(*NodeRegisterRequest)(nil),               // 1: nitella.hub.NodeRegisterRequest
	(*NodeRegisterResponse)(nil),              // 2: nitella.hub.NodeRegisterResponse
	(*WatchRegistrationRequest)(nil),          // 3: nitella.hub.WatchRegistrationRequest
	(*WatchRegistrationResponse)(nil),         // 4: nitella.hub.WatchRegistrationResponse
	(*CheckCertificateRequest)(nil),           // 5: nitella.hub.CheckCertificateRequest
	(*CheckCertificateResponse)(nil),          // 6: nitella.hub.CheckCertificateResponse
	(*HeartbeatRequest)(nil),                  // 7: nitella.hub.HeartbeatRequest
	(*HeartbeatResponse)(nil),                 // 8: nitella.hub.HeartbeatResponse
	(*ReceiveCommandsRequest)(nil),            // 9: nitella.hub.ReceiveCommandsRequest
	(*StreamRevocationsRequest)(nil),          // 10: nitella.hub.StreamRevocationsRequest
	(*proxy.AddRuleRequest)(nil),              // 11: nitella.proxy.AddRuleRequest
	(*proxy.RemoveRuleRequest)(nil),           // 12: nitella.proxy.RemoveRuleRequest
	(*proxy.ListRulesRequest)(nil),            // 13: nitella.proxy.ListRulesRequest
	(*proxy.GetActiveConnectionsRequest)(nil), // 14: nitella.proxy.GetActiveConnectionsRequest
	(*proxy.CloseConnectionRequest)(nil),      // 15: nitella.proxy.CloseConnectionRequest
	(*proxy.CloseAllConnectionsRequest)(nil),  // 16: nitella.proxy.CloseAllConnectionsRequest
	(*proxy.GetIPStatsRequest)(nil),           // 17: nitella.proxy.GetIPStatsRequest
	(*proxy.GetGeoStatsRequest)(nil),          // 18: nitella.proxy.GetGeoStatsRequest
	(*proxy.GetStatsSummaryRequest)(nil),      // 19: nitella.proxy.GetStatsSummaryRequest
	(*proxy.ResolveApprovalRequest)(nil),      // 20: nitella.proxy.ResolveApprovalRequest
	(*proxy.ListProxiesRequest)(nil),          // 21: nitella.proxy.ListProxiesRequest
	(*proxy.CreateProxyRequest)(nil),          // 22: nitella.proxy.CreateProxyRequest
	(*proxy.UpdateProxyRequest)(nil),          // 23: nitella.proxy.UpdateProxyRequest
	(*proxy.DeleteProxyRequest)(nil),          // 24: nitella.proxy.DeleteProxyRequest
	(*proxy.EnableProxyRequest)(nil),          // 25: nitella.proxy.EnableProxyRequest
	(*proxy.DisableProxyRequest)(nil),         // 26: nitella.proxy.DisableProxyRequest
	(RegistrationStatus)(0),                   // 27: nitella.hub.RegistrationStatus
	(NodeStatus)(0),                           // 28: nitella.hub.NodeStatus
	(*CommandResponse)(nil),                   // 29: nitella.hub.CommandResponse
	(*EncryptedMetrics)(nil),                  // 30: nitella.hub.EncryptedMetrics
	(*EncryptedLogEntry)(nil),                 // 31: nitella.hub.EncryptedLogEntry
	(*common.Alert)(nil),                      // 32: nitella.Alert
	(*SignalMessage)(nil),                     // 33: nitella.hub.SignalMessage
	(*Command)(nil),                           // 34: nitella.hub.Command
	(*Empty)(nil),                             // 35: nitella.hub.Empty
	(*RevocationEvent)(nil),                   // 36: nitella.hub.RevocationEvent
}
var file_hub_hub_node_proto_depIdxs = []int32{
	11, // 0: nitella.hub.NodeCommand.add_rule:type_name -> nitella.proxy.AddRuleRequest
	12, // 1: nitella.hub.NodeCommand.remove_rule:type_name -> nitella.proxy.RemoveRuleRequest
	13, // 2: nitella.hub.NodeCommand.fetch_rules:type_name -> nitella.proxy.ListRulesRequest
	14, // 3: nitella.hub.NodeCommand.get_connections:type_name -> nitella.proxy.GetActiveConnectionsRequest
	15, // 4: nitella.hub.NodeCommand.close_connection:type_name -> nitella.proxy.CloseConnectionRequest
	16, // 5: nitella.hub.NodeCommand.close_all:type_name -> nitella.proxy.CloseAllConnectionsRequest
	17, // 6: nitella.hub.NodeCommand.get_ip_stats:type_name -> nitella.proxy.GetIPStatsRequest
	18, // 7: nitella.hub.NodeCommand.get_geo_stats:type_name -> nitella.proxy.GetGeoStatsRequest
	19, // 8: nitella.hub.NodeCommand.get_stats_summary:type_name -> nitella.proxy.GetStatsSummaryRequest
	20, // 9: nitella.hub.NodeCommand.resolve_approval:type_name -> nitella.proxy.ResolveApprovalRequest
	21, // 10: nitella.hub.NodeCommand.list_proxies:type_name -> nitella.proxy.ListProxiesRequest
	22, // 11: nitella.hub.NodeCommand.create_proxy:type_name -> nitella.proxy.CreateProxyRequest
	23, // 12: nitella.hub.NodeCommand.update_proxy:type_name -> nitella.proxy.UpdateProxyRequest
	24, // 13: nitella.hub.NodeCommand.delete_proxy:type_name -> nitella.proxy.DeleteProxyRequest
	25, // 14: nitella.hub.NodeCommand.enable_proxy:type_name -> nitella.proxy.EnableProxyRequest
	26, // 15: nitella.hub.NodeCommand.disable_proxy:type_name -> nitella.proxy.DisableProxyRequest
	27, // 16: nitella.hub.NodeRegisterResponse.status:type_name -> nitella.hub.RegistrationStatus
	27, // 17: nitella.hub.WatchRegistrationResponse.status:type_name -> nitella.hub.RegistrationStatus
	28, // 18: nitella.hub.HeartbeatRequest.status:type_name -> nitella.hub.NodeStatus
	1,  // 19: nitella.hub.NodeService.Register:input_type -> nitella.hub.NodeRegisterRequest
	3,  // 20: nitella.hub.NodeService.WatchRegistration:input_type -> nitella.hub.WatchRegistrationRequest
	5,  // 21: nitella.hub.NodeService.CheckCertificate:input_type -> nitella.hub.CheckCertificateRequest
	7,  // 22: nitella.hub.NodeService.Heartbeat:input_type -> nitella.hub.HeartbeatRequest
	9,  // 23: nitella.hub.NodeService.ReceiveCommands:input_type -> nitella.hub.ReceiveCommandsRequest
	29, // 24: nitella.hub.NodeService.RespondToCommand:input_type -> nitella.hub.CommandResponse
	30, // 25: nitella.hub.NodeService.PushMetrics:input_type -> nitella.hub.EncryptedMetrics
	31, // 26: nitella.hub.NodeService.PushLogs:input_type -> nitella.hub.EncryptedLogEntry
	32, // 27: nitella.hub.NodeService.PushAlert:input_type -> nitella.Alert
	10, // 28: nitella.hub.NodeService.StreamRevocations:input_type -> nitella.hub.StreamRevocationsRequest
	33, // 29: nitella.hub.NodeService.StreamSignaling:input_type -> nitella.hub.SignalMessage
	2,  // 30: nitella.hub.NodeService.Register:output_type -> nitella.hub.NodeRegisterResponse
	4,  // 31: nitella.hub.NodeService.WatchRegistration:output_type -> nitella.hub.WatchRegistrationResponse
	6,  // 32: nitella.hub.NodeService.CheckCertificate:output_type -> nitella.hub.CheckCertificateResponse
	8,  // 33: nitella.hub.NodeService.Heartbeat:output_type -> nitella.hub.HeartbeatResponse
	34, // 34: nitella.hub.NodeService.ReceiveCommands:output_type -> nitella.hub.Command
	35, // 35: nitella.hub.NodeService.RespondToCommand:output_type -> nitella.hub.Empty
	35, // 36: nitella.hub.NodeService.PushMetrics:output_type -> nitella.hub.Empty
	35, // 37: nitella.hub.NodeService.PushLogs:output_type -> nitella.hub.Empty
	35, // 38: nitella.hub.NodeService.PushAlert:output_type -> nitella.hub.Empty
	36, // 39: nitella.hub.NodeService.StreamRevocations:output_type -> nitella.hub.RevocationEvent
	33, // 40: nitella.hub.NodeService.StreamSignaling:output_type -> nitella.hub.SignalMessage
	30, // [30:41] is the sub-list for method output_type
	19, // [19:30] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_hub_hub_node_proto_init() }
func file_hub_hub_node_proto_init() {
	if File_hub_hub_node_proto != nil {
		return
	}
	file_hub_hub_common_proto_init()
	file_hub_hub_node_proto_msgTypes[0].OneofWrappers = []any{
		(*NodeCommand_AddRule)(nil),
		(*NodeCommand_RemoveRule)(nil),
		(*NodeCommand_FetchRules)(nil),
		(*NodeCommand_GetConnections)(nil),
		(*NodeCommand_CloseConnection)(nil),
		(*NodeCommand_CloseAll)(nil),
		(*NodeCommand_GetIpStats)(nil),
		(*NodeCommand_GetGeoStats)(nil),
		(*NodeCommand_GetStatsSummary)(nil),
		(*NodeCommand_ResolveApproval)(nil),
		(*NodeCommand_ListProxies)(nil),
		(*NodeCommand_CreateProxy)(nil),
		(*NodeCommand_UpdateProxy)(nil),
		(*NodeCommand_DeleteProxy)(nil),
		(*NodeCommand_EnableProxy)(nil),
		(*NodeCommand_DisableProxy)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_hub_node_proto_rawDesc), len(file_hub_hub_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_hub_node_proto_goTypes,
		DependencyIndexes: file_hub_hub_node_proto_depIdxs,
		MessageInfos:      file_hub_hub_node_proto_msgTypes,
	}.Build()
	File_hub_hub_node_proto = out.File
	file_hub_hub_node_proto_goTypes = nil
	file_hub_hub_node_proto_depIdxs = nil
}
