// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: hub/hub_node.proto

package hub

import (
	context "context"
	common "github.com/ivere27/nitella/pkg/api/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_Register_FullMethodName          = "/nitella.hub.NodeService/Register"
	NodeService_WatchRegistration_FullMethodName = "/nitella.hub.NodeService/WatchRegistration"
	NodeService_CheckCertificate_FullMethodName  = "/nitella.hub.NodeService/CheckCertificate"
	NodeService_Heartbeat_FullMethodName         = "/nitella.hub.NodeService/Heartbeat"
	NodeService_ReceiveCommands_FullMethodName   = "/nitella.hub.NodeService/ReceiveCommands"
	NodeService_RespondToCommand_FullMethodName  = "/nitella.hub.NodeService/RespondToCommand"
	NodeService_PushMetrics_FullMethodName       = "/nitella.hub.NodeService/PushMetrics"
	NodeService_PushLogs_FullMethodName          = "/nitella.hub.NodeService/PushLogs"
	NodeService_PushAlert_FullMethodName         = "/nitella.hub.NodeService/PushAlert"
	NodeService_StreamRevocations_FullMethodName = "/nitella.hub.NodeService/StreamRevocations"
	NodeService_StreamSignaling_FullMethodName   = "/nitella.hub.NodeService/StreamSignaling"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	// Registration
	Register(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterResponse, error)
	WatchRegistration(ctx context.Context, in *WatchRegistrationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchRegistrationResponse], error)
	CheckCertificate(ctx context.Context, in *CheckCertificateRequest, opts ...grpc.CallOption) (*CheckCertificateResponse, error)
	// Heartbeat / Status
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Command Reception (Hub -> Node)
	ReceiveCommands(ctx context.Context, in *ReceiveCommandsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Command], error)
	// Command Response (Node -> Hub) - For Sync E2E
	RespondToCommand(ctx context.Context, in *CommandResponse, opts ...grpc.CallOption) (*Empty, error)
	// Metrics/Logs Push (Node -> Hub) - Zero-Trust: Encrypted
	PushMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EncryptedMetrics, Empty], error)
	PushLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EncryptedLogEntry, Empty], error)
	PushAlert(ctx context.Context, in *common.Alert, opts ...grpc.CallOption) (*Empty, error)
	// Certificate Revocation (Hub -> Node broadcast)
	StreamRevocations(ctx context.Context, in *StreamRevocationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RevocationEvent], error)
	// P2P Signaling (Node <-> Hub <-> Mobile)
	StreamSignaling(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SignalMessage, SignalMessage], error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) Register(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeRegisterResponse)
	err := c.cc.Invoke(ctx, NodeService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) WatchRegistration(ctx context.Context, in *WatchRegistrationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchRegistrationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_WatchRegistration_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRegistrationRequest, WatchRegistrationResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchRegistrationClient = grpc.ServerStreamingClient[WatchRegistrationResponse]

func (c *nodeServiceClient) CheckCertificate(ctx context.Context, in *CheckCertificateRequest, opts ...grpc.CallOption) (*CheckCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckCertificateResponse)
	err := c.cc.Invoke(ctx, NodeService_CheckCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, NodeService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) ReceiveCommands(ctx context.Context, in *ReceiveCommandsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[1], NodeService_ReceiveCommands_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReceiveCommandsRequest, Command]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_ReceiveCommandsClient = grpc.ServerStreamingClient[Command]

func (c *nodeServiceClient) RespondToCommand(ctx context.Context, in *CommandResponse, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NodeService_RespondToCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) PushMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EncryptedMetrics, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[2], NodeService_PushMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EncryptedMetrics, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_PushMetricsClient = grpc.ClientStreamingClient[EncryptedMetrics, Empty]

func (c *nodeServiceClient) PushLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EncryptedLogEntry, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[3], NodeService_PushLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EncryptedLogEntry, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_PushLogsClient = grpc.ClientStreamingClient[EncryptedLogEntry, Empty]

func (c *nodeServiceClient) PushAlert(ctx context.Context, in *common.Alert, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, NodeService_PushAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StreamRevocations(ctx context.Context, in *StreamRevocationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RevocationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[4], NodeService_StreamRevocations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRevocationsRequest, RevocationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamRevocationsClient = grpc.ServerStreamingClient[RevocationEvent]

func (c *nodeServiceClient) StreamSignaling(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SignalMessage, SignalMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[5], NodeService_StreamSignaling_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SignalMessage, SignalMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamSignalingClient = grpc.BidiStreamingClient[SignalMessage, SignalMessage]

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
type NodeServiceServer interface {
	// Registration
	Register(context.Context, *NodeRegisterRequest) (*NodeRegisterResponse, error)
	WatchRegistration(*WatchRegistrationRequest, grpc.ServerStreamingServer[WatchRegistrationResponse]) error
	CheckCertificate(context.Context, *CheckCertificateRequest) (*CheckCertificateResponse, error)
	// Heartbeat / Status
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Command Reception (Hub -> Node)
	ReceiveCommands(*ReceiveCommandsRequest, grpc.ServerStreamingServer[Command]) error
	// Command Response (Node -> Hub) - For Sync E2E
	RespondToCommand(context.Context, *CommandResponse) (*Empty, error)
	// Metrics/Logs Push (Node -> Hub) - Zero-Trust: Encrypted
	PushMetrics(grpc.ClientStreamingServer[EncryptedMetrics, Empty]) error
	PushLogs(grpc.ClientStreamingServer[EncryptedLogEntry, Empty]) error
	PushAlert(context.Context, *common.Alert) (*Empty, error)
	// Certificate Revocation (Hub -> Node broadcast)
	StreamRevocations(*StreamRevocationsRequest, grpc.ServerStreamingServer[RevocationEvent]) error
	// P2P Signaling (Node <-> Hub <-> Mobile)
	StreamSignaling(grpc.BidiStreamingServer[SignalMessage, SignalMessage]) error
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) Register(context.Context, *NodeRegisterRequest) (*NodeRegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedNodeServiceServer) WatchRegistration(*WatchRegistrationRequest, grpc.ServerStreamingServer[WatchRegistrationResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchRegistration not implemented")
}
func (UnimplementedNodeServiceServer) CheckCertificate(context.Context, *CheckCertificateRequest) (*CheckCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckCertificate not implemented")
}
func (UnimplementedNodeServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNodeServiceServer) ReceiveCommands(*ReceiveCommandsRequest, grpc.ServerStreamingServer[Command]) error {
	return status.Error(codes.Unimplemented, "method ReceiveCommands not implemented")
}
func (UnimplementedNodeServiceServer) RespondToCommand(context.Context, *CommandResponse) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondToCommand not implemented")
}
func (UnimplementedNodeServiceServer) PushMetrics(grpc.ClientStreamingServer[EncryptedMetrics, Empty]) error {
	return status.Error(codes.Unimplemented, "method PushMetrics not implemented")
}
func (UnimplementedNodeServiceServer) PushLogs(grpc.ClientStreamingServer[EncryptedLogEntry, Empty]) error {
	return status.Error(codes.Unimplemented, "method PushLogs not implemented")
}
func (UnimplementedNodeServiceServer) PushAlert(context.Context, *common.Alert) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PushAlert not implemented")
}
func (UnimplementedNodeServiceServer) StreamRevocations(*StreamRevocationsRequest, grpc.ServerStreamingServer[RevocationEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamRevocations not implemented")
}
func (UnimplementedNodeServiceServer) StreamSignaling(grpc.BidiStreamingServer[SignalMessage, SignalMessage]) error {
	return status.Error(codes.Unimplemented, "method StreamSignaling not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Register(ctx, req.(*NodeRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_WatchRegistration_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRegistrationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).WatchRegistration(m, &grpc.GenericServerStream[WatchRegistrationRequest, WatchRegistrationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_WatchRegistrationServer = grpc.ServerStreamingServer[WatchRegistrationResponse]

func _NodeService_CheckCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CheckCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_CheckCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CheckCertificate(ctx, req.(*CheckCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_ReceiveCommands_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReceiveCommandsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).ReceiveCommands(m, &grpc.GenericServerStream[ReceiveCommandsRequest, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_ReceiveCommandsServer = grpc.ServerStreamingServer[Command]

func _NodeService_RespondToCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RespondToCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RespondToCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RespondToCommand(ctx, req.(*CommandResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_PushMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).PushMetrics(&grpc.GenericServerStream[EncryptedMetrics, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_PushMetricsServer = grpc.ClientStreamingServer[EncryptedMetrics, Empty]

func _NodeService_PushLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).PushLogs(&grpc.GenericServerStream[EncryptedLogEntry, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_PushLogsServer = grpc.ClientStreamingServer[EncryptedLogEntry, Empty]

func _NodeService_PushAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Alert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).PushAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_PushAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).PushAlert(ctx, req.(*common.Alert))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StreamRevocations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRevocationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).StreamRevocations(m, &grpc.GenericServerStream[StreamRevocationsRequest, RevocationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamRevocationsServer = grpc.ServerStreamingServer[RevocationEvent]

func _NodeService_StreamSignaling_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeServiceServer).StreamSignaling(&grpc.GenericServerStream[SignalMessage, SignalMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StreamSignalingServer = grpc.BidiStreamingServer[SignalMessage, SignalMessage]

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nitella.hub.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _NodeService_Register_Handler,
		},
		{
			MethodName: "CheckCertificate",
			Handler:    _NodeService_CheckCertificate_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _NodeService_Heartbeat_Handler,
		},
		{
			MethodName: "RespondToCommand",
			Handler:    _NodeService_RespondToCommand_Handler,
		},
		{
			MethodName: "PushAlert",
			Handler:    _NodeService_PushAlert_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchRegistration",
			Handler:       _NodeService_WatchRegistration_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReceiveCommands",
			Handler:       _NodeService_ReceiveCommands_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PushMetrics",
			Handler:       _NodeService_PushMetrics_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PushLogs",
			Handler:       _NodeService_PushLogs_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamRevocations",
			Handler:       _NodeService_StreamRevocations_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamSignaling",
			Handler:       _NodeService_StreamSignaling_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "hub/hub_node.proto",
}
