// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: hub/hub_common.proto

package hub

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	common "github.com/ivere27/nitella/pkg/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrationStatus int32

const (
	RegistrationStatus_REGISTRATION_STATUS_UNSPECIFIED RegistrationStatus = 0
	RegistrationStatus_REGISTRATION_STATUS_PENDING     RegistrationStatus = 1
	RegistrationStatus_REGISTRATION_STATUS_APPROVED    RegistrationStatus = 2
	RegistrationStatus_REGISTRATION_STATUS_REJECTED    RegistrationStatus = 3
)

// Enum value maps for RegistrationStatus.
var (
	RegistrationStatus_name = map[int32]string{
		0: "REGISTRATION_STATUS_UNSPECIFIED",
		1: "REGISTRATION_STATUS_PENDING",
		2: "REGISTRATION_STATUS_APPROVED",
		3: "REGISTRATION_STATUS_REJECTED",
	}
	RegistrationStatus_value = map[string]int32{
		"REGISTRATION_STATUS_UNSPECIFIED": 0,
		"REGISTRATION_STATUS_PENDING":     1,
		"REGISTRATION_STATUS_APPROVED":    2,
		"REGISTRATION_STATUS_REJECTED":    3,
	}
)

func (x RegistrationStatus) Enum() *RegistrationStatus {
	p := new(RegistrationStatus)
	*p = x
	return p
}

func (x RegistrationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistrationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_hub_common_proto_enumTypes[0].Descriptor()
}

func (RegistrationStatus) Type() protoreflect.EnumType {
	return &file_hub_hub_common_proto_enumTypes[0]
}

func (x RegistrationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistrationStatus.Descriptor instead.
func (RegistrationStatus) EnumDescriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{0}
}

type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED NodeStatus = 0
	NodeStatus_NODE_STATUS_OFFLINE     NodeStatus = 1
	NodeStatus_NODE_STATUS_ONLINE      NodeStatus = 2
	NodeStatus_NODE_STATUS_BLOCKED     NodeStatus = 3
	NodeStatus_NODE_STATUS_CONNECTING  NodeStatus = 4
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_OFFLINE",
		2: "NODE_STATUS_ONLINE",
		3: "NODE_STATUS_BLOCKED",
		4: "NODE_STATUS_CONNECTING",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED": 0,
		"NODE_STATUS_OFFLINE":     1,
		"NODE_STATUS_ONLINE":      2,
		"NODE_STATUS_BLOCKED":     3,
		"NODE_STATUS_CONNECTING":  4,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_hub_common_proto_enumTypes[1].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_hub_hub_common_proto_enumTypes[1]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{1}
}

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED            CommandType = 0
	CommandType_COMMAND_TYPE_EXECUTE                CommandType = 1
	CommandType_COMMAND_TYPE_ADD_RULE               CommandType = 2
	CommandType_COMMAND_TYPE_REMOVE_RULE            CommandType = 3
	CommandType_COMMAND_TYPE_GET_ACTIVE_CONNECTIONS CommandType = 4
	CommandType_COMMAND_TYPE_CLOSE_CONNECTION       CommandType = 5
	CommandType_COMMAND_TYPE_CLOSE_ALL_CONNECTIONS  CommandType = 6
	CommandType_COMMAND_TYPE_STATS_CONTROL          CommandType = 7
	CommandType_COMMAND_TYPE_LIST_PROXIES           CommandType = 8
	// Proxy Template Management
	CommandType_COMMAND_TYPE_APPLY_PROXY   CommandType = 20 // Apply proxy config to node
	CommandType_COMMAND_TYPE_UNAPPLY_PROXY CommandType = 21 // Remove proxy config from node
	CommandType_COMMAND_TYPE_GET_APPLIED   CommandType = 22 // List applied proxy configs
	CommandType_COMMAND_TYPE_PROXY_UPDATE  CommandType = 23 // Notification: proxy config updated
	// Approval Workflow
	CommandType_COMMAND_TYPE_RESOLVE_APPROVAL CommandType = 30 // Resolve a pending approval request
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0:  "COMMAND_TYPE_UNSPECIFIED",
		1:  "COMMAND_TYPE_EXECUTE",
		2:  "COMMAND_TYPE_ADD_RULE",
		3:  "COMMAND_TYPE_REMOVE_RULE",
		4:  "COMMAND_TYPE_GET_ACTIVE_CONNECTIONS",
		5:  "COMMAND_TYPE_CLOSE_CONNECTION",
		6:  "COMMAND_TYPE_CLOSE_ALL_CONNECTIONS",
		7:  "COMMAND_TYPE_STATS_CONTROL",
		8:  "COMMAND_TYPE_LIST_PROXIES",
		20: "COMMAND_TYPE_APPLY_PROXY",
		21: "COMMAND_TYPE_UNAPPLY_PROXY",
		22: "COMMAND_TYPE_GET_APPLIED",
		23: "COMMAND_TYPE_PROXY_UPDATE",
		30: "COMMAND_TYPE_RESOLVE_APPROVAL",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":            0,
		"COMMAND_TYPE_EXECUTE":                1,
		"COMMAND_TYPE_ADD_RULE":               2,
		"COMMAND_TYPE_REMOVE_RULE":            3,
		"COMMAND_TYPE_GET_ACTIVE_CONNECTIONS": 4,
		"COMMAND_TYPE_CLOSE_CONNECTION":       5,
		"COMMAND_TYPE_CLOSE_ALL_CONNECTIONS":  6,
		"COMMAND_TYPE_STATS_CONTROL":          7,
		"COMMAND_TYPE_LIST_PROXIES":           8,
		"COMMAND_TYPE_APPLY_PROXY":            20,
		"COMMAND_TYPE_UNAPPLY_PROXY":          21,
		"COMMAND_TYPE_GET_APPLIED":            22,
		"COMMAND_TYPE_PROXY_UPDATE":           23,
		"COMMAND_TYPE_RESOLVE_APPROVAL":       30,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_hub_common_proto_enumTypes[2].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_hub_hub_common_proto_enumTypes[2]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{2}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_hub_hub_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{0}
}

// Node represents a managed proxy node
type Node struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EncryptedMetadata []byte                 `protobuf:"bytes,2,opt,name=encrypted_metadata,json=encryptedMetadata,proto3" json:"encrypted_metadata,omitempty"` // E2E Encrypted Name and other metadata
	OwnerId           string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Status            NodeStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=nitella.hub.NodeStatus" json:"status,omitempty"` // online, offline, connecting
	LastSeen          *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	PublicIp          string                 `protobuf:"bytes,6,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	ListenPorts       []int32                `protobuf:"varint,7,rep,packed,name=listen_ports,json=listenPorts,proto3" json:"listen_ports,omitempty"`
	GeoipEnabled      bool                   `protobuf:"varint,8,opt,name=geoip_enabled,json=geoipEnabled,proto3" json:"geoip_enabled,omitempty"`
	Version           string                 `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt         *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_hub_hub_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetEncryptedMetadata() []byte {
	if x != nil {
		return x.EncryptedMetadata
	}
	return nil
}

func (x *Node) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Node) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *Node) GetLastSeen() *timestamp.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Node) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *Node) GetListenPorts() []int32 {
	if x != nil {
		return x.ListenPorts
	}
	return nil
}

func (x *Node) GetGeoipEnabled() bool {
	if x != nil {
		return x.GeoipEnabled
	}
	return false
}

func (x *Node) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Node) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Metrics data (plaintext - for local use only)
type Metrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp         *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ConnectionsActive int64                  `protobuf:"varint,3,opt,name=connections_active,json=connectionsActive,proto3" json:"connections_active,omitempty"`
	ConnectionsTotal  int64                  `protobuf:"varint,4,opt,name=connections_total,json=connectionsTotal,proto3" json:"connections_total,omitempty"`
	BytesIn           int64                  `protobuf:"varint,5,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut          int64                  `protobuf:"varint,6,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	BlockedCount      int64                  `protobuf:"varint,7,opt,name=blocked_count,json=blockedCount,proto3" json:"blocked_count,omitempty"`
	RulesHitCount     map[string]int64       `protobuf:"bytes,8,rep,name=rules_hit_count,json=rulesHitCount,proto3" json:"rules_hit_count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_hub_hub_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{2}
}

func (x *Metrics) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Metrics) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Metrics) GetConnectionsActive() int64 {
	if x != nil {
		return x.ConnectionsActive
	}
	return 0
}

func (x *Metrics) GetConnectionsTotal() int64 {
	if x != nil {
		return x.ConnectionsTotal
	}
	return 0
}

func (x *Metrics) GetBytesIn() int64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *Metrics) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *Metrics) GetBlockedCount() int64 {
	if x != nil {
		return x.BlockedCount
	}
	return 0
}

func (x *Metrics) GetRulesHitCount() map[string]int64 {
	if x != nil {
		return x.RulesHitCount
	}
	return nil
}

// Encrypted Metrics for Hub storage (Zero-Trust)
type EncryptedMetrics struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	NodeId        string                   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     *timestamp.Timestamp     `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Encrypted     *common.EncryptedPayload `protobuf:"bytes,3,opt,name=encrypted,proto3" json:"encrypted,omitempty"` // Encrypted Metrics blob
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedMetrics) Reset() {
	*x = EncryptedMetrics{}
	mi := &file_hub_hub_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedMetrics) ProtoMessage() {}

func (x *EncryptedMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedMetrics.ProtoReflect.Descriptor instead.
func (*EncryptedMetrics) Descriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{3}
}

func (x *EncryptedMetrics) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EncryptedMetrics) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EncryptedMetrics) GetEncrypted() *common.EncryptedPayload {
	if x != nil {
		return x.Encrypted
	}
	return nil
}

// Log entry (plaintext - for local/internal use only)
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_hub_hub_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{4}
}

func (x *LogEntry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LogEntry) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Encrypted Log Entry for Hub relay (Zero-Trust)
// Hub cannot read log contents - only User can decrypt
type EncryptedLogEntry struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	NodeId        string                   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     *timestamp.Timestamp     `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Encrypted     *common.EncryptedPayload `protobuf:"bytes,3,opt,name=encrypted,proto3" json:"encrypted,omitempty"` // Encrypted LogEntry blob
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedLogEntry) Reset() {
	*x = EncryptedLogEntry{}
	mi := &file_hub_hub_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedLogEntry) ProtoMessage() {}

func (x *EncryptedLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedLogEntry.ProtoReflect.Descriptor instead.
func (*EncryptedLogEntry) Descriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{5}
}

func (x *EncryptedLogEntry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EncryptedLogEntry) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EncryptedLogEntry) GetEncrypted() *common.EncryptedPayload {
	if x != nil {
		return x.Encrypted
	}
	return nil
}

// User
type User struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BlindIndex       string                 `protobuf:"bytes,2,opt,name=blind_index,json=blindIndex,proto3" json:"blind_index,omitempty"`                   // Hash(Email + Salt)
	EncryptedProfile []byte                 `protobuf:"bytes,3,opt,name=encrypted_profile,json=encryptedProfile,proto3" json:"encrypted_profile,omitempty"` // Encrypted Email, Avatar, etc.
	Role             string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`                                                 // admin, user, viewer
	Tier             string                 `protobuf:"bytes,5,opt,name=tier,proto3" json:"tier,omitempty"`                                                 // free, pro, business
	MaxNodes         int32                  `protobuf:"varint,6,opt,name=max_nodes,json=maxNodes,proto3" json:"max_nodes,omitempty"`
	LastLogin        *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	CreatedAt        *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_hub_hub_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetBlindIndex() string {
	if x != nil {
		return x.BlindIndex
	}
	return ""
}

func (x *User) GetEncryptedProfile() []byte {
	if x != nil {
		return x.EncryptedProfile
	}
	return nil
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *User) GetMaxNodes() int32 {
	if x != nil {
		return x.MaxNodes
	}
	return 0
}

func (x *User) GetLastLogin() *timestamp.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Response from Node to Hub (and back to Mobile)
type CommandResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	CommandId     string                   `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	EncryptedData *common.EncryptedPayload `protobuf:"bytes,2,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"` // E2E encrypted return data (contains serialized CommandResult)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_hub_hub_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{7}
}

func (x *CommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResponse) GetEncryptedData() *common.EncryptedPayload {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

// CommandResult matches the structure of CommandResponse but is intended to be encrypted
type CommandResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "OK", "ERROR"
	ErrorMessage    string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ResponsePayload []byte                 `protobuf:"bytes,3,opt,name=response_payload,json=responsePayload,proto3" json:"response_payload,omitempty"` // The actual data (e.g. serialized list_proxies_response)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_hub_hub_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{8}
}

func (x *CommandResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CommandResult) GetResponsePayload() []byte {
	if x != nil {
		return x.ResponsePayload
	}
	return nil
}

// Command from Hub to Node (E2E encrypted only)
type Command struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Encrypted     *common.EncryptedPayload `protobuf:"bytes,2,opt,name=encrypted,proto3" json:"encrypted,omitempty"` // Always encrypted
	ExpiresAt     *timestamp.Timestamp     `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_hub_hub_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{9}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetEncrypted() *common.EncryptedPayload {
	if x != nil {
		return x.Encrypted
	}
	return nil
}

func (x *Command) GetExpiresAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type EncryptedCommandPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=nitella.hub.CommandType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedCommandPayload) Reset() {
	*x = EncryptedCommandPayload{}
	mi := &file_hub_hub_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedCommandPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedCommandPayload) ProtoMessage() {}

func (x *EncryptedCommandPayload) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedCommandPayload.ProtoReflect.Descriptor instead.
func (*EncryptedCommandPayload) Descriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{10}
}

func (x *EncryptedCommandPayload) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *EncryptedCommandPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Certificate Revocation Event
type RevocationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber  string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	RevokedAt     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevocationEvent) Reset() {
	*x = RevocationEvent{}
	mi := &file_hub_hub_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevocationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevocationEvent) ProtoMessage() {}

func (x *RevocationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevocationEvent.ProtoReflect.Descriptor instead.
func (*RevocationEvent) Descriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{11}
}

func (x *RevocationEvent) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *RevocationEvent) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *RevocationEvent) GetRevokedAt() *timestamp.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *RevocationEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// WebRTC Signaling
type SignalMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`               // NodeID (from App to Hub) or ClientID (from Node to Hub)
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`               // Populated by Hub
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                                       // "offer", "answer", "candidate"
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                 // JSON SDP or Candidate
	SourceUserId  string                 `protobuf:"bytes,5,opt,name=source_user_id,json=sourceUserId,proto3" json:"source_user_id,omitempty"` // Populated by Hub (UserID) - For P2P Identity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMessage) Reset() {
	*x = SignalMessage{}
	mi := &file_hub_hub_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMessage) ProtoMessage() {}

func (x *SignalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMessage.ProtoReflect.Descriptor instead.
func (*SignalMessage) Descriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{12}
}

func (x *SignalMessage) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *SignalMessage) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *SignalMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SignalMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SignalMessage) GetSourceUserId() string {
	if x != nil {
		return x.SourceUserId
	}
	return ""
}

// PairingRequest: Node -> CLI (encrypted with PAKE shared secret)
type PairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsrPem        string                 `protobuf:"bytes,1,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`                        // Node's CSR for signing
	NodePublicKey []byte                 `protobuf:"bytes,2,opt,name=node_public_key,json=nodePublicKey,proto3" json:"node_public_key,omitempty"` // Node's Ed25519 public key
	NodeVersion   string                 `protobuf:"bytes,3,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairingRequest) Reset() {
	*x = PairingRequest{}
	mi := &file_hub_hub_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingRequest) ProtoMessage() {}

func (x *PairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingRequest.ProtoReflect.Descriptor instead.
func (*PairingRequest) Descriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{13}
}

func (x *PairingRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *PairingRequest) GetNodePublicKey() []byte {
	if x != nil {
		return x.NodePublicKey
	}
	return nil
}

func (x *PairingRequest) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

// PairingResponse: CLI -> Node (encrypted with PAKE shared secret)
// Contains everything the node needs to operate securely
type PairingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CertPem         string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`                           // Signed certificate for the node
	CaPem           string                 `protobuf:"bytes,2,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`                                 // CA certificate for verification
	ViewerPublicKey []byte                 `protobuf:"bytes,3,opt,name=viewer_public_key,json=viewerPublicKey,proto3" json:"viewer_public_key,omitempty"` // CLI's Ed25519 public key for encrypting metrics/alerts
	RoutingToken    string                 `protobuf:"bytes,4,opt,name=routing_token,json=routingToken,proto3" json:"routing_token,omitempty"`            // Blind routing token for Hub communication
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PairingResponse) Reset() {
	*x = PairingResponse{}
	mi := &file_hub_hub_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingResponse) ProtoMessage() {}

func (x *PairingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_hub_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingResponse.ProtoReflect.Descriptor instead.
func (*PairingResponse) Descriptor() ([]byte, []int) {
	return file_hub_hub_common_proto_rawDescGZIP(), []int{14}
}

func (x *PairingResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *PairingResponse) GetCaPem() string {
	if x != nil {
		return x.CaPem
	}
	return ""
}

func (x *PairingResponse) GetViewerPublicKey() []byte {
	if x != nil {
		return x.ViewerPublicKey
	}
	return nil
}

func (x *PairingResponse) GetRoutingToken() string {
	if x != nil {
		return x.RoutingToken
	}
	return ""
}

var File_hub_hub_common_proto protoreflect.FileDescriptor

const file_hub_hub_common_proto_rawDesc = "" +
	"\n" +
	"\x14hub/hub_common.proto\x12\vnitella.hub\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\a\n" +
	"\x05Empty\"\x84\x03\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x12encrypted_metadata\x18\x02 \x01(\fR\x11encryptedMetadata\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12/\n" +
	"\x06status\x18\x04 \x01(\x0e2\x17.nitella.hub.NodeStatusR\x06status\x127\n" +
	"\tlast_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x1b\n" +
	"\tpublic_ip\x18\x06 \x01(\tR\bpublicIp\x12!\n" +
	"\flisten_ports\x18\a \x03(\x05R\vlistenPorts\x12#\n" +
	"\rgeoip_enabled\x18\b \x01(\bR\fgeoipEnabled\x12\x18\n" +
	"\aversion\x18\t \x01(\tR\aversion\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa8\x03\n" +
	"\aMetrics\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12-\n" +
	"\x12connections_active\x18\x03 \x01(\x03R\x11connectionsActive\x12+\n" +
	"\x11connections_total\x18\x04 \x01(\x03R\x10connectionsTotal\x12\x19\n" +
	"\bbytes_in\x18\x05 \x01(\x03R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\x06 \x01(\x03R\bbytesOut\x12#\n" +
	"\rblocked_count\x18\a \x01(\x03R\fblockedCount\x12O\n" +
	"\x0frules_hit_count\x18\b \x03(\v2'.nitella.hub.Metrics.RulesHitCountEntryR\rrulesHitCount\x1a@\n" +
	"\x12RulesHitCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x9e\x01\n" +
	"\x10EncryptedMetrics\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x127\n" +
	"\tencrypted\x18\x03 \x01(\v2\x19.nitella.EncryptedPayloadR\tencrypted\"\x83\x02\n" +
	"\bLogEntry\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x129\n" +
	"\x06fields\x18\x05 \x03(\v2!.nitella.hub.LogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x01\n" +
	"\x11EncryptedLogEntry\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x127\n" +
	"\tencrypted\x18\x03 \x01(\v2\x19.nitella.EncryptedPayloadR\tencrypted\"\x9f\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vblind_index\x18\x02 \x01(\tR\n" +
	"blindIndex\x12+\n" +
	"\x11encrypted_profile\x18\x03 \x01(\fR\x10encryptedProfile\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x12\n" +
	"\x04tier\x18\x05 \x01(\tR\x04tier\x12\x1b\n" +
	"\tmax_nodes\x18\x06 \x01(\x05R\bmaxNodes\x129\n" +
	"\n" +
	"last_login\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"r\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12@\n" +
	"\x0eencrypted_data\x18\x02 \x01(\v2\x19.nitella.EncryptedPayloadR\rencryptedData\"w\n" +
	"\rCommandResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12)\n" +
	"\x10response_payload\x18\x03 \x01(\fR\x0fresponsePayload\"\x8d\x01\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\tencrypted\x18\x02 \x01(\v2\x19.nitella.EncryptedPayloadR\tencrypted\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"a\n" +
	"\x17EncryptedCommandPayload\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.nitella.hub.CommandTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xab\x01\n" +
	"\x0fRevocationEvent\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x129\n" +
	"\n" +
	"revoked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x9d\x01\n" +
	"\rSignalMessage\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12$\n" +
	"\x0esource_user_id\x18\x05 \x01(\tR\fsourceUserId\"t\n" +
	"\x0ePairingRequest\x12\x17\n" +
	"\acsr_pem\x18\x01 \x01(\tR\x06csrPem\x12&\n" +
	"\x0fnode_public_key\x18\x02 \x01(\fR\rnodePublicKey\x12!\n" +
	"\fnode_version\x18\x03 \x01(\tR\vnodeVersion\"\x94\x01\n" +
	"\x0fPairingResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem\x12\x15\n" +
	"\x06ca_pem\x18\x02 \x01(\tR\x05caPem\x12*\n" +
	"\x11viewer_public_key\x18\x03 \x01(\fR\x0fviewerPublicKey\x12#\n" +
	"\rrouting_token\x18\x04 \x01(\tR\froutingToken*\x9e\x01\n" +
	"\x12RegistrationStatus\x12#\n" +
	"\x1fREGISTRATION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bREGISTRATION_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cREGISTRATION_STATUS_APPROVED\x10\x02\x12 \n" +
	"\x1cREGISTRATION_STATUS_REJECTED\x10\x03*\x8f\x01\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13NODE_STATUS_OFFLINE\x10\x01\x12\x16\n" +
	"\x12NODE_STATUS_ONLINE\x10\x02\x12\x17\n" +
	"\x13NODE_STATUS_BLOCKED\x10\x03\x12\x1a\n" +
	"\x16NODE_STATUS_CONNECTING\x10\x04*\xcf\x03\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14COMMAND_TYPE_EXECUTE\x10\x01\x12\x19\n" +
	"\x15COMMAND_TYPE_ADD_RULE\x10\x02\x12\x1c\n" +
	"\x18COMMAND_TYPE_REMOVE_RULE\x10\x03\x12'\n" +
	"#COMMAND_TYPE_GET_ACTIVE_CONNECTIONS\x10\x04\x12!\n" +
	"\x1dCOMMAND_TYPE_CLOSE_CONNECTION\x10\x05\x12&\n" +
	"\"COMMAND_TYPE_CLOSE_ALL_CONNECTIONS\x10\x06\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_STATS_CONTROL\x10\a\x12\x1d\n" +
	"\x19COMMAND_TYPE_LIST_PROXIES\x10\b\x12\x1c\n" +
	"\x18COMMAND_TYPE_APPLY_PROXY\x10\x14\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_UNAPPLY_PROXY\x10\x15\x12\x1c\n" +
	"\x18COMMAND_TYPE_GET_APPLIED\x10\x16\x12\x1d\n" +
	"\x19COMMAND_TYPE_PROXY_UPDATE\x10\x17\x12!\n" +
	"\x1dCOMMAND_TYPE_RESOLVE_APPROVAL\x10\x1eB(Z&github.com/ivere27/nitella/pkg/api/hubb\x06proto3"

var (
	file_hub_hub_common_proto_rawDescOnce sync.Once
	file_hub_hub_common_proto_rawDescData []byte
)

func file_hub_hub_common_proto_rawDescGZIP() []byte {
	file_hub_hub_common_proto_rawDescOnce.Do(func() {
		file_hub_hub_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_hub_common_proto_rawDesc), len(file_hub_hub_common_proto_rawDesc)))
	})
	return file_hub_hub_common_proto_rawDescData
}

var file_hub_hub_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_hub_hub_common_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_hub_hub_common_proto_goTypes = []any{
	(RegistrationStatus)(0),         // 0: nitella.hub.RegistrationStatus
	(NodeStatus)(0),                 // 1: nitella.hub.NodeStatus
	(CommandType)(0),                // 2: nitella.hub.CommandType
	(*Empty)(nil),                   // 3: nitella.hub.Empty
	(*Node)(nil),                    // 4: nitella.hub.Node
	(*Metrics)(nil),                 // 5: nitella.hub.Metrics
	(*EncryptedMetrics)(nil),        // 6: nitella.hub.EncryptedMetrics
	(*LogEntry)(nil),                // 7: nitella.hub.LogEntry
	(*EncryptedLogEntry)(nil),       // 8: nitella.hub.EncryptedLogEntry
	(*User)(nil),                    // 9: nitella.hub.User
	(*CommandResponse)(nil),         // 10: nitella.hub.CommandResponse
	(*CommandResult)(nil),           // 11: nitella.hub.CommandResult
	(*Command)(nil),                 // 12: nitella.hub.Command
	(*EncryptedCommandPayload)(nil), // 13: nitella.hub.EncryptedCommandPayload
	(*RevocationEvent)(nil),         // 14: nitella.hub.RevocationEvent
	(*SignalMessage)(nil),           // 15: nitella.hub.SignalMessage
	(*PairingRequest)(nil),          // 16: nitella.hub.PairingRequest
	(*PairingResponse)(nil),         // 17: nitella.hub.PairingResponse
	nil,                             // 18: nitella.hub.Metrics.RulesHitCountEntry
	nil,                             // 19: nitella.hub.LogEntry.FieldsEntry
	(*timestamp.Timestamp)(nil),     // 20: google.protobuf.Timestamp
	(*common.EncryptedPayload)(nil), // 21: nitella.EncryptedPayload
}
var file_hub_hub_common_proto_depIdxs = []int32{
	1,  // 0: nitella.hub.Node.status:type_name -> nitella.hub.NodeStatus
	20, // 1: nitella.hub.Node.last_seen:type_name -> google.protobuf.Timestamp
	20, // 2: nitella.hub.Node.created_at:type_name -> google.protobuf.Timestamp
	20, // 3: nitella.hub.Metrics.timestamp:type_name -> google.protobuf.Timestamp
	18, // 4: nitella.hub.Metrics.rules_hit_count:type_name -> nitella.hub.Metrics.RulesHitCountEntry
	20, // 5: nitella.hub.EncryptedMetrics.timestamp:type_name -> google.protobuf.Timestamp
	21, // 6: nitella.hub.EncryptedMetrics.encrypted:type_name -> nitella.EncryptedPayload
	20, // 7: nitella.hub.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	19, // 8: nitella.hub.LogEntry.fields:type_name -> nitella.hub.LogEntry.FieldsEntry
	20, // 9: nitella.hub.EncryptedLogEntry.timestamp:type_name -> google.protobuf.Timestamp
	21, // 10: nitella.hub.EncryptedLogEntry.encrypted:type_name -> nitella.EncryptedPayload
	20, // 11: nitella.hub.User.last_login:type_name -> google.protobuf.Timestamp
	20, // 12: nitella.hub.User.created_at:type_name -> google.protobuf.Timestamp
	21, // 13: nitella.hub.CommandResponse.encrypted_data:type_name -> nitella.EncryptedPayload
	21, // 14: nitella.hub.Command.encrypted:type_name -> nitella.EncryptedPayload
	20, // 15: nitella.hub.Command.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 16: nitella.hub.EncryptedCommandPayload.type:type_name -> nitella.hub.CommandType
	20, // 17: nitella.hub.RevocationEvent.revoked_at:type_name -> google.protobuf.Timestamp
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_hub_hub_common_proto_init() }
func file_hub_hub_common_proto_init() {
	if File_hub_hub_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_hub_common_proto_rawDesc), len(file_hub_hub_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hub_hub_common_proto_goTypes,
		DependencyIndexes: file_hub_hub_common_proto_depIdxs,
		EnumInfos:         file_hub_hub_common_proto_enumTypes,
		MessageInfos:      file_hub_hub_common_proto_msgTypes,
	}.Build()
	File_hub_hub_common_proto = out.File
	file_hub_hub_common_proto_goTypes = nil
	file_hub_hub_common_proto_depIdxs = nil
}
