// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: proxy/proxy.proto

package proxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProxyControlService_SendCommand_FullMethodName       = "/nitella.proxy.ProxyControlService/SendCommand"
	ProxyControlService_StreamConnections_FullMethodName = "/nitella.proxy.ProxyControlService/StreamConnections"
	ProxyControlService_StreamMetrics_FullMethodName     = "/nitella.proxy.ProxyControlService/StreamMetrics"
)

// ProxyControlServiceClient is the client API for ProxyControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyControlServiceClient interface {
	// E2E Encrypted Command (same envelope as Hub relay)
	SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error)
	// Observability (E2E encrypted streams)
	StreamConnections(ctx context.Context, in *StreamConnectionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptedStreamPayload], error)
	StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptedStreamPayload], error)
}

type proxyControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyControlServiceClient(cc grpc.ClientConnInterface) ProxyControlServiceClient {
	return &proxyControlServiceClient{cc}
}

func (c *proxyControlServiceClient) SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCommandResponse)
	err := c.cc.Invoke(ctx, ProxyControlService_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyControlServiceClient) StreamConnections(ctx context.Context, in *StreamConnectionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptedStreamPayload], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProxyControlService_ServiceDesc.Streams[0], ProxyControlService_StreamConnections_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamConnectionsRequest, EncryptedStreamPayload]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProxyControlService_StreamConnectionsClient = grpc.ServerStreamingClient[EncryptedStreamPayload]

func (c *proxyControlServiceClient) StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncryptedStreamPayload], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProxyControlService_ServiceDesc.Streams[1], ProxyControlService_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMetricsRequest, EncryptedStreamPayload]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProxyControlService_StreamMetricsClient = grpc.ServerStreamingClient[EncryptedStreamPayload]

// ProxyControlServiceServer is the server API for ProxyControlService service.
// All implementations must embed UnimplementedProxyControlServiceServer
// for forward compatibility.
type ProxyControlServiceServer interface {
	// E2E Encrypted Command (same envelope as Hub relay)
	SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error)
	// Observability (E2E encrypted streams)
	StreamConnections(*StreamConnectionsRequest, grpc.ServerStreamingServer[EncryptedStreamPayload]) error
	StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[EncryptedStreamPayload]) error
	mustEmbedUnimplementedProxyControlServiceServer()
}

// UnimplementedProxyControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyControlServiceServer struct{}

func (UnimplementedProxyControlServiceServer) SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedProxyControlServiceServer) StreamConnections(*StreamConnectionsRequest, grpc.ServerStreamingServer[EncryptedStreamPayload]) error {
	return status.Error(codes.Unimplemented, "method StreamConnections not implemented")
}
func (UnimplementedProxyControlServiceServer) StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[EncryptedStreamPayload]) error {
	return status.Error(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedProxyControlServiceServer) mustEmbedUnimplementedProxyControlServiceServer() {}
func (UnimplementedProxyControlServiceServer) testEmbeddedByValue()                             {}

// UnsafeProxyControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyControlServiceServer will
// result in compilation errors.
type UnsafeProxyControlServiceServer interface {
	mustEmbedUnimplementedProxyControlServiceServer()
}

func RegisterProxyControlServiceServer(s grpc.ServiceRegistrar, srv ProxyControlServiceServer) {
	// If the following call panics, it indicates UnimplementedProxyControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyControlService_ServiceDesc, srv)
}

func _ProxyControlService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyControlServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyControlService_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyControlServiceServer).SendCommand(ctx, req.(*SendCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyControlService_StreamConnections_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamConnectionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProxyControlServiceServer).StreamConnections(m, &grpc.GenericServerStream[StreamConnectionsRequest, EncryptedStreamPayload]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProxyControlService_StreamConnectionsServer = grpc.ServerStreamingServer[EncryptedStreamPayload]

func _ProxyControlService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProxyControlServiceServer).StreamMetrics(m, &grpc.GenericServerStream[StreamMetricsRequest, EncryptedStreamPayload]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProxyControlService_StreamMetricsServer = grpc.ServerStreamingServer[EncryptedStreamPayload]

// ProxyControlService_ServiceDesc is the grpc.ServiceDesc for ProxyControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nitella.proxy.ProxyControlService",
	HandlerType: (*ProxyControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommand",
			Handler:    _ProxyControlService_SendCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConnections",
			Handler:       _ProxyControlService_StreamConnections_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamMetrics",
			Handler:       _ProxyControlService_StreamMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proxy/proxy.proto",
}
